export const projectEstimateStyles = {
  luxuryPage: { width: 794, minHeight: 1123, boxSizing: "border-box", color: "#0f172a", background: "#ffffff", boxShadow: "0 22px 55px rgba(15,23,42,0.22)", padding: 54, display: "flex", flexDirection: "column", gap: 24, flex: "0 0 auto", overflow: "hidden", position: "relative" },
  luxuryProjectInfoPage: { height: 1123, minHeight: 1123, padding: 44, gap: 16 },
  luxuryCoverPage: { padding: 0, backgroundSize: "cover", backgroundPosition: "center", backgroundRepeat: "no-repeat" },
  luxuryCoverOverlay: { minHeight: 1123, boxSizing: "border-box", padding: 60, display: "flex", flexDirection: "column", justifyContent: "space-between", color: "#ffffff" },
  luxuryLogoLockup: { display: "flex", alignItems: "center", gap: 16, minHeight: 76, fontSize: 19, fontWeight: 950, letterSpacing: "0.06em", textTransform: "uppercase" },
  luxuryLogoImage: { width: 108, height: 74, objectFit: "contain", display: "block", flex: "0 0 auto" },
  luxuryLogoMark: { width: 74, height: 74, border: "1px solid rgba(200,157,74,0.9)", color: "#c89d4a", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 900, letterSpacing: 0 },
  luxuryCoverContent: { maxWidth: 580, display: "grid", gap: 18 },
  luxuryThankYouContent: { maxWidth: 620, display: "grid", gap: 18, alignSelf: "center", textAlign: "center" },
  luxuryEyebrow: { fontSize: 13, fontWeight: 950, letterSpacing: "0.16em", textTransform: "uppercase" },
  luxuryCoverTitle: { margin: 0, color: "#ffffff", fontSize: 62, lineHeight: 0.98, fontWeight: 950, letterSpacing: 0, display: "grid", gap: 6, textShadow: "0 8px 24px rgba(0,0,0,0.42)" },
  luxuryProjectEstimateCoverTitle: { margin: 0, color: "#ffffff", display: "grid", gap: 6, textAlign: "left", fontFamily: "inherit", textShadow: "0 8px 24px rgba(0,0,0,0.42)" },
  luxuryProjectEstimateCoverTitleLine: { display: "block", color: "#ffffff", fontSize: 62, lineHeight: 0.98, fontWeight: 950, letterSpacing: 0, fontFamily: "inherit", textAlign: "left", textShadow: "0 8px 24px rgba(0,0,0,0.42)" },
  luxuryAccentRule: { width: 132, height: 5, borderRadius: 999 },
  luxuryCoverClient: { margin: 0, color: "#ffffff", fontSize: 25, lineHeight: 1.35, fontWeight: 850, whiteSpace: "pre-line" },
  luxuryCoverAddress: { margin: 0, color: "#e2e8f0", fontSize: 19, lineHeight: 1.55, fontWeight: 550, whiteSpace: "pre-line" },
  luxuryCoverMeta: { display: "flex", justifyContent: "space-between", gap: 18, borderTop: "1px solid rgba(255,255,255,0.35)", paddingTop: 18, color: "#f8fafc", fontSize: 16, fontWeight: 800, letterSpacing: "0.03em", textTransform: "uppercase" },
  luxuryPageHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 18, minHeight: 76 },
  luxuryHeaderTitle: { fontSize: 15, fontWeight: 950, letterSpacing: "0.14em", textTransform: "uppercase" },
  luxurySectionTitle: { margin: 0, color: "#0f172a", fontSize: 40, lineHeight: 1.08, fontWeight: 950, letterSpacing: 0 },
  luxuryBodyText: { margin: 0, color: "#334155", fontSize: 18, lineHeight: 1.62, fontWeight: 520, whiteSpace: "pre-line" },
  luxuryProjectIntro: { display: "grid", gridTemplateColumns: "0.74fr 1fr", gap: 24, alignItems: "end", borderBottom: "1px solid #e2e8f0", paddingBottom: 18 },
  luxuryInfoGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 9 },
  luxuryInfoCard: { minHeight: 78, border: "1px solid #e2e8f0", borderRadius: 12, background: "#f8fafc", padding: 12, display: "grid", gap: 5, alignContent: "start" },
  luxuryInfoIcon: { fontSize: 11, fontWeight: 950, letterSpacing: "0.16em", textTransform: "uppercase" },
  luxuryInfoDetail: { color: "#475569", fontSize: 13, lineHeight: 1.35, fontWeight: 800 },
  luxuryFeatureBox: { border: "2px solid #c89d4a", borderRadius: 16, background: "#ffffff", padding: 22, display: "grid", gap: 8, color: "#0f172a", fontSize: 17, lineHeight: 1.55 },
  luxuryProjectInfoFeatureBox: { padding: 16, gap: 4, marginTop: "auto" },
  luxuryEstimateSummaryPage: { gap: 10, padding: 40 },
  luxuryEstimateSummaryIntro: { gap: 18, paddingBottom: 12 },
  luxuryEstimateSummaryTitle: { fontSize: 34, lineHeight: 1.04 },
  luxuryEstimateSummaryBody: { fontSize: 16, lineHeight: 1.42 },
  luxuryEstimateSummaryInfoGrid: { gap: 7 },
  luxuryEstimateSummaryInfoCard: { minHeight: 65, padding: 9, gap: 3, borderRadius: 10 },
  luxuryEstimateSummaryNoticeBox: { padding: 13, gap: 4 },
  luxuryNoticeHeading: { margin: 0, fontSize: 22, lineHeight: 1.15, fontWeight: 950 },
  luxuryNoticeBody: { margin: 0, textAlign: "left", fontSize: 14, lineHeight: 1.38, fontWeight: 550, color: "#334155" },
  luxuryAboutWhyPage: { height: 1123, minHeight: 1123, padding: 40, gap: 16, background: "#fbfaf6" },
  luxuryAboutWhyTop: { display: "grid", gridTemplateColumns: "0.95fr 1fr", gap: 24, alignItems: "start", minHeight: 320 },
  luxuryAboutWhyCopy: { display: "grid", gap: 10, alignContent: "start" },
  luxuryAboutWhyTitle: { margin: 0, color: "#0f172a", fontSize: 33, lineHeight: 1.03, fontWeight: 950, letterSpacing: 0 },
  luxuryAboutWhyBody: { margin: 0, color: "#334155", fontSize: 14.5, lineHeight: 1.42, fontWeight: 540, whiteSpace: "pre-line" },
  luxuryAboutWhyLogoStrip: { marginTop: 8, borderTop: "1px solid #e2e8f0", paddingTop: 12 },
  luxuryAboutWhyImageStack: { position: "relative", minHeight: 320 },
  luxuryAboutWhyHeroImage: { width: "86%", height: 280, objectFit: "cover", display: "block", borderRadius: "76px 16px 76px 16px", border: "1px solid #e2e8f0", boxShadow: "0 24px 50px rgba(15,23,42,0.18)" },
  luxuryAboutWhyImageInset: { position: "absolute", right: 0, bottom: 0, width: "46%", height: 136, objectFit: "cover", display: "block", borderRadius: "16px 54px 16px 54px", border: "6px solid #fbfaf6", boxShadow: "0 18px 38px rgba(15,23,42,0.20)" },
  luxuryAboutWhyLower: { display: "grid", gap: 12, borderTop: "1px solid #e2e8f0", paddingTop: 14 },
  luxuryAboutWhySubhead: { margin: "4px 0 0", color: "#0f172a", fontSize: 23, lineHeight: 1.08, fontWeight: 950 },
  luxuryAboutWhyCardGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 8 },
  luxuryAboutWhyCard: { minHeight: 124, border: "1px solid #e7dcc5", borderRadius: 14, background: "#ffffff", padding: 9, display: "grid", gap: 4, alignContent: "start", boxShadow: "0 12px 24px rgba(15,23,42,0.07)", overflow: "hidden" },
  luxuryAboutWhyCardTitle: { color: "#0f172a", fontSize: 12.5, lineHeight: 1.15, fontWeight: 950 },
  luxuryAboutWhyCardBody: { margin: 0, color: "#334155", fontSize: 11.4, lineHeight: 1.32, fontWeight: 560 },
  luxuryAboutWhyIcon: { width: 28, height: 28, borderRadius: 999, color: "#07111f", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 950 },
  luxuryAboutWhyStatsBar: { marginTop: "auto", display: "grid", gridTemplateColumns: "repeat(6, minmax(0, 1fr))", gap: 7, paddingTop: 10, borderTop: "2px solid #e2e8f0" },
  luxuryAboutWhyStatCard: { display: "grid", gap: 4, textAlign: "center", color: "#334155", fontSize: 9.8, fontWeight: 900, textTransform: "uppercase", letterSpacing: "0.03em", background: "#fffaf0", border: "1px solid #ead9b5", borderRadius: 12, padding: "8px 5px" },
  luxuryImageFrame: { width: "100%", height: 420, objectFit: "cover", borderRadius: "90px 18px 90px 18px", border: "1px solid #e2e8f0", display: "block" },
  luxuryImageFrameWide: { height: 320, borderRadius: 20 },
  luxuryImageFrameTall: { height: 520 },
  luxuryImageFrameDeep: { height: 610, borderRadius: 22 },
  luxuryImagePlaceholder: { width: "100%", minHeight: 360, boxSizing: "border-box", border: "2px dashed #cbd5e1", borderRadius: "90px 18px 90px 18px", background: "#f8fafc", color: "#64748b", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 900 },
  luxuryCardGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 14, marginTop: 8 },
  luxuryDarkCard: { border: "1px solid rgba(255,255,255,0.16)", borderRadius: 18, background: "linear-gradient(145deg, rgba(255,255,255,0.12), rgba(255,255,255,0.045))", padding: 18, minHeight: 172, display: "grid", gap: 8, alignContent: "start", color: "#e2e8f0", boxShadow: "0 18px 38px rgba(0,0,0,0.18)" },
  luxuryIconDot: { width: 44, height: 44, borderRadius: 999, color: "#07111f", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 950 },
  luxuryWhyPage: { backgroundSize: "cover", backgroundPosition: "center", backgroundRepeat: "no-repeat" },
  luxuryWhyHero: { maxWidth: 720, display: "grid", gap: 12, color: "#e2e8f0" },
  luxuryWhyStatsBar: { marginTop: "auto", display: "grid", gridTemplateColumns: "repeat(6, minmax(0, 1fr))", gap: 8, padding: 16, border: "1px solid rgba(255,255,255,0.42)", background: "linear-gradient(135deg, #c89d4a 0%, #f8d58a 100%)", boxShadow: "0 24px 48px rgba(0,0,0,0.28)" },
  luxuryWhyStatCard: { display: "grid", gap: 5, textAlign: "center", color: "#07111f", fontSize: 11, fontWeight: 900, textTransform: "uppercase", letterSpacing: "0.04em" },
  luxuryDesignTextBlock: { marginTop: 34, paddingTop: 18, display: "grid", gridTemplateColumns: "0.82fr 1fr", gap: 30, alignItems: "end", borderTop: "1px solid #e2e8f0" },
  luxuryStandardInclusionsPage: { padding: 34, gap: 12 },
  standardPricedUsing: { border: "2px solid #c89d4a", borderRadius: 999, background: "#ffffff", color: "#0f172a", padding: "9px 14px", fontSize: 14, fontWeight: 950, width: "fit-content" },
  luxuryPriceHero: { border: "1px solid rgba(255,255,255,0.16)", borderRadius: 22, background: "rgba(255,255,255,0.07)", padding: 28, display: "grid", gap: 8, textAlign: "center" },
  luxuryPriceGrid: { display: "grid", gap: 10 },
  luxuryProgressHeading: { margin: "6px 0 0", color: "#ffffff", fontSize: 26, lineHeight: 1.15, fontWeight: 950, letterSpacing: 0 },
  luxuryPriceHeaderRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 90px 150px", alignItems: "center", gap: 16, color: "#f8d58a", fontSize: 12, fontWeight: 950, letterSpacing: "0.12em", textTransform: "uppercase", borderBottom: "1px solid rgba(248,213,138,0.32)", paddingBottom: 8 },
  luxuryPriceRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 90px 150px", alignItems: "center", gap: 16, borderBottom: "1px solid rgba(255,255,255,0.15)", padding: "13px 0", color: "#e2e8f0", fontSize: 16, fontWeight: 750 },
  luxurySignatureGrid: { display: "grid", gridTemplateColumns: "1fr 220px", gap: 22, margin: "30px 0" },
  luxurySignatureLine: { minHeight: 110, borderBottom: "2px solid #0f172a", color: "#64748b", display: "flex", alignItems: "flex-end", paddingBottom: 10, fontWeight: 850 },
};
