import { BlockTypes } from "./blockTypes";
import { COMPETITOR_COMPARISON_TEMPLATE_PROPS } from "./competitorComparison";
import { getPlatformChartPlans } from "../../../data/platformPricing";

export const BlockDefinitions = {
  [BlockTypes.NAV_BAR]: {
    name: "Navigation Bar",
    icon: "🧭",
    category: "Section",
    description: "Top navigation with brand, links, and CTA",
    defaultProps: {
      variant: "split-dark",
      fullWidthBackground: true,
      showLogo: false,
      logo: "",
      logoWidth: 44,
      stickyMode: "normal",
      mobileMenuStyle: "hamburger",
      brand: "Your Brand",
      brandFontSize: 18,
      links: [
        { label: "Home", href: "/", highlighted: true, children: [] },
        { label: "About Us", href: "/about" },
        { label: "Modules", href: "/modules" },
        { label: "Contact Us", href: "/contact" },
      ],
      linkFontSize: 16,
      linkHoverEffect: "fill",
      linkHoverBackgroundColor: "rgba(255,255,255,0.14)",
      linkHoverTextColor: "#ffffff",
      activeLinkBackgroundColor: "rgba(255,255,255,0.18)",
      activeLinkTextColor: "#ffffff",
      ctaText: "Get Started",
      ctaLink: "#contact",
      ctaFontSize: 16,
      backgroundColor: "#0b1220",
      borderColor: "rgba(148,163,184,0.24)",
      textColor: "#e2e8f0",
      buttonColor: "#ffffff",
      buttonTextColor: "#0f172a",
    },
  },
  [BlockTypes.HERO]: {
    name: "Hero Section",
    icon: "🎬",
    category: "Section",
    description: "Full-width hero background container",
    defaultProps: {
      backgroundStyle: "gradient",
      minHeight: "520px",
    },
  },
  [BlockTypes.PARALLAX]: {
    name: "Parallax Section",
    icon: "🌊",
    category: "Section",
    description: "Movable parallax text over a background image",
    defaultProps: {
      headline: "Parallax Headline",
      subheadline: "Drag this text box anywhere over the background.",
      ctaText: "Get Started",
      ctaLink: "#",
      headlineAlignment: "center",
      verticalAlign: "center",
      contentX: 50,
      contentY: 58,
      contentWidth: 680,
      contentHeight: 220,
      floatingImage: "",
      floatingX: 76,
      floatingY: 58,
      floatingWidth: 220,
      floatingHeight: 220,
      headlineColor: "#ffffff",
      headlineFontFamily: "system-ui, -apple-system, sans-serif",
      headlineFontWeight: "700",
      headlineFontSize: 52,
      subheadlineFontSize: 20,
      textColor: "#e2e8f0",
      fontFamily: "system-ui, -apple-system, sans-serif",
      fontWeight: "400",
      buttonColor: "#2563eb",
      buttonTextColor: "#ffffff",
      fullWidthBackground: true,
      enableParallax: true,
      backgroundStyle: "image",
      backgroundColor: "#0f172a",
      backgroundImage: "https://placehold.co/1600x900/0f172a/1e293b?text=%20",
      backgroundVideoUrl: "",
      backgroundPosition: "center center",
      minHeight: "480px",
    },
  },
  [BlockTypes.SPLIT_BLOCK]: {
    name: "Split Block",
    icon: "↔️",
    category: "Section",
    description: "Half parallax image, half content with FAQ accordion",
    defaultProps: {
      splitColorPreset: "green",
      eyebrow: "Our Specialties",
      headline: "Why Choose Us?",
      subheadline: "Add a short description about what makes your business stand out. Edit this text to share your unique value proposition.",
      headlineBlock: {
        content: "Why Choose Us?",
        animation: "fade-up",
        animationDelay: 0,
        animationSpeed: 0.8,
        fontFamily: "Poppins, sans-serif",
        fontWeight: "400",
        fontSize: 48,
        lineHeight: 1.2,
        color: "#61ce70",
        alignment: "left",
      },
      bodyBlock: {
        content: "Add a short description about what makes your business stand out. Edit this text to share your unique value proposition.",
        animation: "fade-in",
        animationDelay: 0.12,
        animationSpeed: 0.9,
        fontFamily: "Arial",
        fontWeight: "400",
        fontSize: 18,
        lineHeight: 1.6,
        color: "#bdbcbf",
        alignment: "left",
      },
      splitLayout: "43-57",
      fullWidthBackground: true,
      enableParallax: false,
      backgroundStyle: "image",
      backgroundColor: "#000000",
      backgroundImage: "",
      backgroundPosition: "center center",
      backgroundSize: "cover",
      backgroundRepeat: "no-repeat",
      parallaxStrength: 0.78,
      minHeight: "1040px",
      contentPanelBackgroundColor: "transparent",
      sectionBackgroundColor: "#000000",
      headlineColor: "#61ce70",
      eyebrowColor: "linear-gradient(90deg, #22c55e 0%, #bef264 100%)",
      textColor: "#bdbcbf",
      faqMaxWidth: 323,
      faqStartCollapsed: false,
      faqAllowMultipleOpen: false,
      itemBackgroundColor: "transparent",
      itemBorderColor: "rgba(0, 66, 96, 0.39)",
      arrowBackgroundColor: "linear-gradient(135deg, #163628 0%, #22c55e 52%, #bef264 100%)",
      chevronColor: "#ffffff",
      faqVariant: "source-split",
      faqAnimation: "fade-up",
      faqAnimationDelay: 0.18,
      faqAnimationSpeed: 0.9,
      faqPanelBackgroundColor: "rgba(3, 18, 28, 0.26)",
      faqBlock: {
        faqVariant: "source-split",
        faqStartCollapsed: false,
        faqAllowMultipleOpen: false,
        sectionAnimation: "fade-up",
        sectionAnimationDelay: 0.12,
        sectionAnimationSpeed: 0.9,
        faqAnimation: "fade-up",
        faqAnimationDelay: 0.18,
        faqAnimationSpeed: 0.9,
        faqPanelBackgroundColor: "rgba(3, 18, 28, 0.26)",
        itemBackgroundColor: "transparent",
        itemBorderColor: "rgba(0, 66, 96, 0.39)",
        arrowBackgroundColor: "linear-gradient(135deg, #163628 0%, #22c55e 52%, #bef264 100%)",
        chevronColor: "#ffffff",
        questionColor: "#ffffff",
        questionFontWeight: "700",
        questionFontSize: 24,
        questionLineHeight: 1.4,
        answerColor: "#bdbcbf",
        answerFontSize: 18,
        answerLineHeight: 1.6,
        faqMaxWidth: 323,
        items: [
          { id: "split-faq-1", question: "Question one?", answer: "Answer to question one goes here.", heading: "Question one?", content: "Answer to question one goes here." },
          { id: "split-faq-2", question: "Question two?", answer: "Answer to question two goes here.", heading: "Question two?", content: "Answer to question two goes here." },
          { id: "split-faq-3", question: "Question three?", answer: "Answer to question three goes here.", heading: "Question three?", content: "Answer to question three goes here." },
        ],
      },
      questionColor: "#ffffff",
      questionFontWeight: "700",
      questionFontSize: 24,
      answerColor: "#bdbcbf",
      answerFontSize: 18,
      headlineFontFamily: "Poppins, sans-serif",
      headlineFontWeight: "400",
      headlineFontSize: 48,
      subheadlineFontSize: 18,
      items: [
        { id: "split-faq-1", question: "Question one?", answer: "Answer to question one goes here.", heading: "Question one?", content: "Answer to question one goes here." },
        { id: "split-faq-2", question: "Question two?", answer: "Answer to question two goes here.", heading: "Question two?", content: "Answer to question two goes here." },
        { id: "split-faq-3", question: "Question three?", answer: "Answer to question three goes here.", heading: "Question three?", content: "Answer to question three goes here." },
      ],
    },
  },
  [BlockTypes.TEXT]: {
    name: "Text Section",
    icon: "📝",
    category: "Content",
    description: "Rich text content area",
    defaultProps: {
      text: "Enter your text here. You can use multiple paragraphs and formatting.",
      alignment: "left", // left, center, right
      textSize: "medium", // legacy fallback
      textFontSize: 18,
      fontFamily: "system-ui", // system-ui, Georgia, Arial, etc
      fontWeight: "400", // 300, 400, 500, 600, 700, 800, 900
      minHeight: "160px",
      fullWidthBackground: false,
      enableParallax: false,
      textColor: "#e6eef5",
      backgroundColor: "#111827",
      backgroundImage: "",
      paddingTop: 20,
      paddingBottom: 20,
      textLineHeight: 1.35,
      verticalAlign: "top",
      contentY: 32,
      contentHeight: 120,
      textAnimation: "fade-in",
    },
  },
  [BlockTypes.IMAGE]: {
    name: "Image",
    icon: "🖼️",
    category: "Media",
    description: "Add a full-width image with caption",
    defaultProps: {
      src: "",
      alt: "Image",
      width: "100%",
      height: "auto",
      autoHeight: true,
      objectFit: "contain",
      objectPosition: "center center",
      imageStyle: "bleed",
      caption: "",
      fullWidthBackground: true,
      seamlessEdges: true,
      backgroundColor: "transparent",
    },
  },
  [BlockTypes.CTA_BUTTON]: {
    name: "Call-to-Action Button",
    icon: "🔘",
    category: "Conversion",
    description: "Prominent button to drive action",
    defaultProps: {
      eyebrow: "Ready to take the next step?",
      title: "Turn attention into action",
      description: "Use this CTA block to push visitors toward a booking, quote, purchase, or signup.",
      text: "Click Here",
      link: "#",
      note: "Fast setup. Clear next step. Better conversions.",
      style: "spotlight-pill",
      size: "large", // small, medium, large
      alignment: "center",
      backgroundColor: "linear-gradient(135deg,#eff6ff,#ffffff)",
      textColor: "#0f172a",
      buttonColor: "linear-gradient(135deg,#0ea5e9,#2563eb)",
      buttonTextColor: "#ffffff",
      borderColor: "rgba(191,219,254,0.9)",
      fullWidthBackground: false,
    },
  },
  [BlockTypes.FEATURE_LIST]: {
    name: "List Block",
    icon: "☰",
    category: "Content",
    description: "Card-style list section similar to the email editor",
    defaultProps: {
      title: "Key Features",
      items: [
        {
          title: "Feature 1",
          body: "Add a short supporting sentence for this feature.",
          image: "https://placehold.co/960x720/e0f2fe/0f172a?text=Feature+1",
        },
        {
          title: "Feature 2",
          body: "Use each card to explain a specific benefit or deliverable.",
          image: "https://placehold.co/960x720/fef3c7/1f2937?text=Feature+2",
        },
        {
          title: "Feature 3",
          body: "Images can be swapped per card to create a richer section.",
          image: "https://placehold.co/960x720/dcfce7/14532d?text=Feature+3",
        },
      ],
      layout: "vertical",
      featureVariant: "cards",
      sectionWidth: "boxed",
      fullWidthBackground: false,
      cardsPerRowDesktop: 3,
      cardsPerRowTablet: 2,
      cardsPerRowMobile: 1,
      cardSize: "auto",
      customCardWidth: 320,
      horizontalGap: 18,
      verticalGap: 18,
      contentMaxWidth: 1200,
      cardHeightMode: "auto",
      featureCardHeight: null,
      featureCardMaxHeight: null,
      horizontalAlignment: "stretch",
      bulletStyle: "check",
      spacingScale: "normal",
      backgroundColor: "#ffffff",
      itemBackgroundColor: "#eff6ff",
      textColor: "#0f172a",
      borderColor: "#dbeafe",
    },
  },
  [BlockTypes.TESTIMONIAL]: {
    name: "Testimonial",
    icon: "💬",
    category: "Social Proof",
    description: "Customer testimonial or quote",
    defaultProps: {
      text: "We switched to Gr8 Result six months ago and cut our tool stack from 9 apps to 1. Our team saves 12 hours a week and our lead-to-close rate is up 40%.",
      author: "David Waite",
      role: "CEO, Waite and Sea Health & Fitness",
      avatar: "https://bvtxfphktypdqmlnveqf.supabase.co/storage/v1/object/public/assets/35ab846e-0764-498b-b1f8-7d2cf27d85a5/web-1779061738959-default-avatar.png",
      rating: 5,
      testimonialVariant: "cards",
      spacingScale: "normal",
      backgroundColor: "#0a0a0f",
      textColor: "#ffffff",
      cardBackgroundColor: "#0f1729",
      cardBorderColor: "rgba(99,102,241,.2)",
      accentColor: "#6366f1",
      eyebrow: "Client Stories",
      title: "The platform agencies can't stop talking about",
      sectionAnimation: "fade-up",
      autoplay: true,
      autoplaySpeed: 5000,
      testimonialColumns: 4,
      items: [
        {
          id: "8ff27e7f-e8ca-4f4a-b79b-9e7c0a5eefe3",
          text: "We switched to Gr8 Result six months ago and cut our tool stack from 9 apps to 1. Our team saves 12 hours a week and our lead-to-close rate is up 40%.",
          author: "David Waite",
          role: "CEO, Waite and Sea Health & Fitness",
          rating: 5,
          avatarUrl: "https://bvtxfphktypdqmlnveqf.supabase.co/storage/v1/object/public/assets/35ab846e-0764-498b-b1f8-7d2cf27d85a5/web-1779061738959-default-avatar.png",
          avatarAssetId: "asset:35ab846e-0764-498b-b1f8-7d2cf27d85a5/web-1779061738959-default-avatar.png",
        },
        {
          id: "225b5cab-fe01-4c8d-bc89-f68aaed376cf",
          text: "The CRM and email automation alone are worth the price. But the AI phone system? That's what blew our team away. We're handling 3x the leads without adding headcount.",
          author: "Josh Rohde",
          role: "Owner, Truline Cabinets.",
          rating: 5,
          avatarUrl: "",
          avatarAssetId: "8c9c5a3d-0583-4d0c-bdd2-7fb9383af9cf",
        },
        {
          id: "ef6e9cdc-a050-45c6-8d21-c70bb86cf89f",
          text: "Their onboarding team had us live in under a week. The website builder replaced our old drag-and-drop tool and the funnel templates are stunning.",
          author: "Ethan Cooper",
          role: "Marketing Director, Easyway Building Brokers",
          rating: 5,
          avatarUrl: "",
          avatarAssetId: "bb4b2b8d-cacd-489d-aa91-28e024a66a42",
        },
        {
          id: "92c11cc1-150a-4b49-801e-3e1f8578b8cd",
          text: "I've tried every all-in-one platform. Gr8 Result is the first one that doesn't sacrifice depth for breadth. Best decision we made this year.",
          author: "Sarah Reid",
          role: "Founder, Elan Interiors",
          rating: 5,
          avatarUrl: "",
          avatarAssetId: "22a6dd1e-d67b-4eca-abb7-575e411a2560",
        },
      ],
    },
  },
  [BlockTypes.PLATFORM_PRICING_PLANS]: {
    name: "Platform Pricing Plans",
    icon: "💳",
    category: "Conversion",
    description: "Locked Gr8 Result billing plans synced from the billing page",
    defaultProps: {
      title: "Choose Your Platform Plan",
      subtitle: "The same live platform pricing used on the billing page.",
      fullWidthBackground: true,
      backgroundColor: "#0f172a",
      showAddOns: true,
      ctaLabel: "Start Free Trial",
      lockedPlatformPricing: true,
    },
  },
  [BlockTypes.PRICING_TABLE]: {
    name: "Custom Pricing Table",
    icon: "💰",
    category: "Conversion",
    description: "Editable pricing plans for your own website",
    defaultProps: {
      title: "Pricing Plans",
      pricingVariant: "premium",
      backgroundColor: "#ffffff",
      spacingScale: "normal", // tight, normal, luxury
      pricingImageUrl: "",
      pricingImageAlt: "Pricing options",
      pricingImageMaxWidth: 980,
      pricingImageFit: "contain",
      pricingImageHotspots: [],
      currency: "$",
      defaultPeriod: "month",
      plans: [
        {
          id: "pricing-default-1",
          name: "Basic",
          price: "$49",
          description: "For individuals and small teams getting started.",
          includedFeatures: [
            "Team Seats — 2 users",
            "CRM Pipelines — 1",
            "Communities — 1",
            "Social Profiles — 3",
            "Automation Workflows — 5",
            "Calendar & Bookings",
            "Shared Phone Number",
            "Marketplace Access",
            "Reporting — Email & CRM stats",
            "Support — Email",
          ],
          features: [
            "Team Seats — 2 users",
            "CRM Pipelines — 1",
            "Communities — 1",
            "Social Profiles — 3",
            "Automation Workflows — 5",
            "Calendar & Bookings",
            "Shared Phone Number",
            "Marketplace Access",
            "Reporting — Email & CRM stats",
            "Support — Email",
          ],
          extras: [
            "14 days free, then 50% off first 3 months",
            "Email contacts — 5,000",
            "Email sends/mo — 50,000",
            "SMS credits/mo — 500",
            "Websites — 1",
            "Funnels — Landing pages only",
            "Projects Hub — 3 jobs · 5 projects · 2 users",
            "AI credits/mo — 50",
            "Storage — 5 GB",
          ],
          featureIcon: "tick",
          badge: "",
          cta: "Select This Plan",
          ctaUrl: "",
          highlighted: false,
          individualPrice: "$215",
        },
        {
          id: "pricing-default-2",
          name: "Professional",
          price: "$149",
          description: "For growing teams that need more capacity.",
          includedFeatures: [
            "Team Seats — 5 users",
            "CRM Pipelines — 3",
            "Communities — 3",
            "Social Profiles — 7",
            "Automation Workflows — 8",
            "SMS Scheduled Campaigns — 3",
            "Call Recording & AI Transcription",
            "Calendar & Bookings",
            "Shared Phone Number",
            "Affiliate Management",
            "Reporting — Email, SMS & Call Analytics",
            "Support — Priority Email",
          ],
          features: [
            "Team Seats — 5 users",
            "CRM Pipelines — 3",
            "Communities — 3",
            "Social Profiles — 7",
            "Automation Workflows — 8",
            "SMS Scheduled Campaigns — 3",
            "Call Recording & AI Transcription",
            "Calendar & Bookings",
            "Shared Phone Number",
            "Affiliate Management",
            "Reporting — Email, SMS & Call Analytics",
            "Support — Priority Email",
          ],
          extras: [
            "14 days free, then 50% off first 3 months",
            "Email contacts — 15,000",
            "Email sends/mo — 150,000",
            "SMS credits/mo — 2,500",
            "Websites — 2",
            "Funnels — 1 (+ extras at cost)",
            "Projects Hub — 15 jobs · 20 projects · dependencies",
            "AI credits/mo — 250",
            "Storage — 25 GB",
          ],
          featureIcon: "spark",
          badge: "Most Popular",
          cta: "Select This Plan",
          ctaUrl: "",
          highlighted: true,
          individualPrice: "$474",
        },
        {
          id: "pricing-default-3",
          name: "Business",
          price: "$299",
          description: "For established businesses that need advanced support.",
          includedFeatures: [
            "Team Seats — 10 users",
            "CRM Pipelines — 10",
            "Communities — Unlimited",
            "Social Profiles — 15",
            "Automation Workflows — 10",
            "SMS Scheduled Campaigns — 10",
            "AI Transcription + Sentiment",
            "AI Website Builder",
            "Shared Phone Number",
            "Reporting — Full Analytics + CSV export",
            "Support — Dedicated Onboarding",
          ],
          features: [
            "Team Seats — 10 users",
            "CRM Pipelines — 10",
            "Communities — Unlimited",
            "Social Profiles — 15",
            "Automation Workflows — 10",
            "SMS Scheduled Campaigns — 10",
            "AI Transcription + Sentiment",
            "AI Website Builder",
            "Shared Phone Number",
            "Reporting — Full Analytics + CSV export",
            "Support — Dedicated Onboarding",
          ],
          extras: [
            "14 days free, then 50% off first 3 months",
            "Email contacts — 40,000",
            "Email sends/mo — 400,000",
            "SMS credits/mo — 5,000",
            "Websites — 3",
            "Funnels — 3 (+ extras at cost)",
            "Projects Hub — Unlimited jobs & projects · resource allocation · critical path",
            "AI credits/mo — 750",
            "Storage — 100 GB",
          ],
          featureIcon: "arrow",
          badge: "Best Value",
          cta: "Select This Plan",
          ctaUrl: "",
          highlighted: false,
          individualPrice: "$913",
        },
        {
          id: "pricing-default-4",
          name: "Enterprise",
          price: "Custom",
          description: "For larger teams with custom requirements.",
          includedFeatures: [
            "Team Seats — Up to 25 users",
            "CRM Pipelines — Unlimited",
            "Communities — Unlimited",
            "Social Profiles — Unlimited",
            "Automation Workflows — Unlimited",
            "AI Call Transcription & Sentiment",
            "AI Content & Post Generation",
            "Shared Phone Number",
            "Reporting — Full Analytics + Scheduled Reports",
            "Support — Account Manager + SLA",
          ],
          features: [
            "Team Seats — Up to 25 users",
            "CRM Pipelines — Unlimited",
            "Communities — Unlimited",
            "Social Profiles — Unlimited",
            "Automation Workflows — Unlimited",
            "AI Call Transcription & Sentiment",
            "AI Content & Post Generation",
            "Shared Phone Number",
            "Reporting — Full Analytics + Scheduled Reports",
            "Support — Account Manager + SLA",
          ],
          extras: [
            "14 days free trial",
            "Email contacts — 200,000",
            "Email sends/mo — 2,000,000",
            "SMS credits/mo — 10,000",
            "Websites — 5",
            "Funnels — 10 (+ extras at cost)",
            "Projects Hub — Unlimited · API",
            "AI credits/mo — 5,000",
            "Storage — 500 GB",
          ],
          featureIcon: "tick",
          badge: "Enterprise",
          cta: "Select This Plan",
          ctaUrl: "",
          highlighted: false,
          individualPrice: "$1883",
        },
      ],
    },
  },
  [BlockTypes.CONTACT_FORM]: {
    name: "Contact Form",
    icon: "✉️",
    category: "Conversion",
    description: "Lead capture or contact form",
    defaultProps: {
      title: "Get in Touch",
      subtitle: "Fill out the form below",
      formVariant: "minimal-soft",
      formMaxWidth: 760,
      backgroundColor: "#ffffff",
      sectionGradient: "linear-gradient(180deg,#ffffff,#f8fafc)",
      cardBackgroundColor: "#ffffff",
      textColor: "#0f172a",
      subtleTextColor: "#475569",
      buttonBackgroundColor: "#0f172a",
      buttonTextColor: "#ffffff",
      inputBackgroundColor: "#ffffff",
      inputBorderColor: "#cbd5e1",
      inputTextColor: "#0f172a",
      submitAction: "none",
      bookingUrl: "https://nonfat-ungored-buford.ngrok-free.dev/u/gr8result?service=f775fc69-f59e-4fd8-ae4a-1e9bb7ecfe4f",
      mediaPosition: "none",
      mediaImage: "",
      mediaAlt: "Contact form image",
      fields: [
        { name: "name", label: "Your Name", type: "text", required: true, placeholder: "Jane Smith" },
        { name: "email", label: "Your Email", type: "email", required: true, placeholder: "jane@example.com" },
        { name: "message", label: "Message", type: "textarea", required: false, placeholder: "Tell us how we can help" },
      ],
      submitText: "Send Details",
    },
  },
  [BlockTypes.IMAGE_GALLERY]: {
    name: "Image Gallery",
    icon: "🖼️",
    category: "Media",
    description: "Grid of images",
    defaultProps: {
      title: "Visual Highlights",
      galleryVariant: "balanced-grid",
      images: [
        { src: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80", alt: "Team collaboration", caption: "Collaborative planning sessions" },
        { src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80", alt: "Creative meeting", caption: "Creative ideas in motion" },
        { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80", alt: "Workshop wall", caption: "Workshop outcomes and planning" },
      ],
      columns: 3,
      backgroundColor: "linear-gradient(180deg,#ffffff,#f8fafc)",
      textColor: "#0f172a",
      borderColor: "rgba(226,232,240,0.9)",
    },
  },
  [BlockTypes.VIDEO_EMBED]: {
    name: "Video",
    icon: "🎥",
    category: "Media",
    description: "Embedded YouTube or Vimeo video",
    defaultProps: {
      url: "",
      title: "Video Title",
      width: "100%",
      height: "500px",
    },
  },
  [BlockTypes.SPACE]: {
    name: "Spacer",
    icon: "⬆️",
    category: "Layout",
    description: "Add vertical space",
    defaultProps: {
      height: "40px",
      fullWidthBackground: false,
    },
  },
  [BlockTypes.DIVIDER]: {
    name: "Divider",
    icon: "─",
    category: "Layout",
    description: "Configurable separator line with width, style, colour, and spacing controls",
    defaultProps: {
      dividerType: "line",
      lineStyle: "solid",
      color: "#cbd5e1",
      secondaryColor: "#38bdf8",
      thickness: 1,
      width: 100,
      alignment: "center",
      paddingTop: 24,
      paddingBottom: 24,
      backgroundColor: "transparent",
      fullWidthBackground: false,
      showLabel: false,
      label: "",
      labelColor: "#64748b",
    },
  },
  [BlockTypes.COLUMNS_2]: {
    name: "Two Column",
    icon: "▌▌",
    category: "Layout",
    description: "Two content columns with text, images, and color controls",
    defaultProps: {
      title: "",
      leftTitle: "",
      leftContent: "",
      leftImage: "",
      rightTitle: "",
      rightContent: "",
      rightImage: "",
      ratio: "50-50",
      backgroundColor: "transparent",
      cardBackgroundColor: "#f8fafc",
      textColor: "#0f172a",
      borderColor: "#dbeafe",
      leftColumnBlock: null,
      rightColumnBlock: null,
    },
  },
  [BlockTypes.COLUMNS_3]: {
    name: "Three Column",
    icon: "▌▌▌",
    category: "Layout",
    description: "Three content columns with text, images, and color controls",
    defaultProps: {
      title: "",
      column1Title: "",
      column1: "",
      column1Image: "",
      column2Title: "",
      column2: "",
      column2Image: "",
      column3Title: "",
      column3: "",
      column3Image: "",
      backgroundColor: "transparent",
      cardBackgroundColor: "#f8fafc",
      textColor: "#0f172a",
      borderColor: "#dbeafe",
    },
  },
  [BlockTypes.GRID_SECTION]: {
    name: "Grid Section",
    icon: "▦",
    category: "Layout",
    description: "Adjustable card grid with repeatable items, icons, images, and motion controls",
    defaultProps: {
      title: "Our Services",
      columns: 4,
      backgroundColor: "transparent",
      textColor: "#0f172a",
      borderColor: "rgba(148,163,184,0.22)",
      columnBackgroundColor: "#ffffff",
      columnBorderColor: "rgba(148,163,184,0.18)",
      columnTitleColor: "#0f172a",
      columnBodyColor: "#475569",
      columnPadding: 18,
      columnRadius: 22,
      columnShadow: "soft",
      columnContentAlign: "left",
      columnGap: 24,
      columnsTopMargin: 18,
      blockMaxWidth: 1200,
      stretchToCanvas: true,
      sectionAnimation: "fade-up",
      cardAnimation: "fade-up",
      iconAnimation: "fade-up",
      imageAnimation: "zoom",
      titleAnimation: "fade-up",
      bodyAnimation: "fade-up",
      surfaceAnimationSpeed: 0.8,
      cardStagger: 0.08,
      gridVariant: "services",
      iconBackgroundColor: "#ffffff",
      iconColor: "#0f172a",
      iconSize: 20,
      imageRadius: 18,
      gridItemMinHeight: 0,
      items: [
        {
          title: "Social Media",
          eyebrow: "Content Creation",
          iconName: "social",
          content: "",
          link: "https://gr8result.com/social-media/",
          image: "/imported/gr8-services/social-media.jpg",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
        {
          title: "Software",
          eyebrow: "Business Software",
          iconName: "software",
          content: "",
          link: "https://gr8result.com/software/",
          image: "/imported/gr8-services/software.png",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
        {
          title: "Graphic Arts",
          eyebrow: "Graphic Design",
          iconName: "design",
          content: "",
          link: "https://gr8result.com/graphic-design/",
          image: "/imported/gr8-services/graphic-arts.png",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
        {
          title: "Websites",
          eyebrow: "Design and SEO",
          iconName: "web",
          content: "",
          link: "https://gr8result.com/website-development/",
          image: "/imported/gr8-services/websites.jpg",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
        {
          title: "Videos",
          eyebrow: "AI Avatars",
          iconName: "video",
          content: "",
          link: "https://gr8result.com/videos/",
          image: "/imported/gr8-services/videos.jpg",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
        {
          title: "SEO",
          eyebrow: "Organic Growth",
          iconName: "seo",
          content: "",
          link: "https://gr8result.com/seo/",
          image: "/imported/gr8-services/seo.jpg",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
        {
          title: "Email",
          eyebrow: "Email marketing",
          iconName: "email",
          content: "",
          link: "https://gr8result.com/email-marketing/",
          image: "/imported/gr8-services/email.jpg",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
        {
          title: "Digital Marketing",
          eyebrow: "Google & Meta Ads",
          iconName: "marketing",
          content: "",
          link: "https://gr8result.com/branding-design/",
          image: "/imported/gr8-services/digital-marketing.jpg",
          imageAlt: "Gr8 Result Digital Solutions.",
          imageHeight: 150,
        },
      ],
    },
  },
  [BlockTypes.ACCORDION]: {
    name: "Accordion",
    icon: "📋",
    category: "Interaction",
    description: "Expandable content sections",
    hiddenInLibrary: true,
    defaultProps: {
      title: "Frequently Asked Questions",
      faqMaxWidth: 980,
      faqStartCollapsed: false,
      faqAllowMultipleOpen: false,
      items: [
        { heading: "Question 1?", content: "Answer here" },
        { heading: "Question 2?", content: "Answer here" },
      ],
    },
  },
  [BlockTypes.FEATURE_ACCORDION]: {
    name: "Feature Accordion",
    icon: "🗂️",
    category: "Interaction",
    description: "Two-column expandable panels with image and text for showcasing features or services",
    defaultProps: {
      eyebrow: "What We Offer",
      title: "Everything you need to grow online",
      backgroundColor: "#0f172a",
      textColor: "#ffffff",
      accentColor: "#0ea5e9",
      imagePosition: "right",
      contentVerticalAlign: "top",
      itemLabelFontSize: 24,
      itemLabelLineHeight: 1.2,
      itemLabelPaddingTop: 20,
      itemLabelPaddingLeft: 32,
      imageFit: "contain",
      imageMaxHeight: 0,
      imageMaxWidth: 0,
      cardWidth: 1180,
      cardMinHeight: 650,
      cardPadding: 56,
      cardInset: 24,
      cardGap: 32,
      cardScrollGap: 240,
      cardHeight: 650,
      cardRadius: 28,
      accordionStickyTopOffset: 110,
      accordionHeaderHeight: 58,
      accordionStackGap: 8,
      expandedCardHeightMode: "viewport",
      expandedCardHeightPx: 720,
      lastCardRelease: true,
      scrollVhPerCard: 120,
      overlapDelayVh: 60,
      items: [
        {
          id: "feature-item-1",
          label: "Email Autoresponders",
          panelBg: "#0d9488",
          accentColor: "#5eead4",
          image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80",
          imageAlt: "Email automation dashboard",
          contentBlocks: [
            { id: "cb-1-1", type: "eyebrow", text: "Automation" },
            { id: "cb-1-2", type: "heading", text: "Automated emails that nurture your leads 24/7" },
            { id: "cb-1-3", type: "text", text: "Set up powerful autoresponder sequences that engage your audience from the moment they sign up. Deliver the right message at the right time without lifting a finger." },
            { id: "cb-1-4", type: "stat", number: "312%", label: "increase in open rates" },
            { id: "cb-1-5", type: "stat", number: "2x", label: "revenue growth" },
            { id: "cb-1-6", type: "tags", tags: ["Automation", "Email", "Nurturing"] },
            { id: "cb-1-7", type: "cta", text: "Learn More", link: "#" },
          ],
        },
        {
          id: "feature-item-2",
          label: "Email Broadcasts",
          panelBg: "#1a73e8",
          accentColor: "#93c5fd",
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
          imageAlt: "Broadcast campaign analytics",
          contentBlocks: [
            { id: "cb-2-1", type: "eyebrow", text: "Campaigns" },
            { id: "cb-2-2", type: "heading", text: "Reach your entire list with one powerful send" },
            { id: "cb-2-3", type: "text", text: "Launch targeted broadcast campaigns to your full list or segmented audiences. Track opens, clicks, and conversions in real time with beautiful analytics." },
            { id: "cb-2-4", type: "stat", number: "48%", label: "average open rate" },
            { id: "cb-2-5", type: "stat", number: "10k+", label: "emails sent per minute" },
            { id: "cb-2-6", type: "tags", tags: ["Broadcasts", "Analytics", "Segmentation"] },
            { id: "cb-2-7", type: "cta", text: "Explore Broadcasts", link: "#" },
          ],
        },
        {
          id: "feature-item-3",
          label: "Email Campaigns",
          panelBg: "#7c3aed",
          accentColor: "#c4b5fd",
          image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
          imageAlt: "Campaign builder interface",
          contentBlocks: [
            { id: "cb-3-1", type: "eyebrow", text: "Strategy" },
            { id: "cb-3-2", type: "heading", text: "End-to-end campaigns that convert" },
            { id: "cb-3-3", type: "text", text: "Plan, design, and execute complete email campaigns with our drag-and-drop builder. A/B test subject lines, preview on all devices, and optimise for maximum ROI." },
            { id: "cb-3-4", type: "stat", number: "3.8x", label: "average ROI" },
            { id: "cb-3-5", type: "stat", number: "99%", label: "deliverability rate" },
            { id: "cb-3-6", type: "tags", tags: ["Campaigns", "A/B Testing", "Drag & Drop"] },
            { id: "cb-3-7", type: "cta", text: "Start a Campaign", link: "#" },
          ],
        },
        {
          id: "feature-item-4",
          label: "Landing Pages",
          panelBg: "#1e1b4b",
          accentColor: "#818cf8",
          image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=1200&q=80",
          imageAlt: "Landing page builder",
          contentBlocks: [
            { id: "cb-4-1", type: "eyebrow", text: "Pages" },
            { id: "cb-4-2", type: "heading", text: "Beautiful landing pages that convert visitors into customers" },
            { id: "cb-4-3", type: "text", text: "Drag-and-drop page builder with proven templates. Publish in minutes and A/B test your way to higher conversions without touching a line of code." },
            { id: "cb-4-4", type: "stat", number: "60+", label: "proven templates" },
            { id: "cb-4-5", type: "stat", number: "4.9s", label: "avg load time" },
            { id: "cb-4-6", type: "tags", tags: ["Pages", "Templates", "A/B Testing"] },
            { id: "cb-4-7", type: "cta", text: "Browse Templates", link: "#" },
          ],
        },
        {
          id: "feature-item-5",
          label: "Sales Funnels",
          panelBg: "#831843",
          accentColor: "#f9a8d4",
          image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80",
          imageAlt: "Sales funnel pipeline",
          contentBlocks: [
            { id: "cb-5-1", type: "eyebrow", text: "Funnels" },
            { id: "cb-5-2", type: "heading", text: "End-to-end sales funnels that close deals on autopilot" },
            { id: "cb-5-3", type: "text", text: "Build multi-step funnels with upsells, downsells, and order bumps. Connect your checkout, email, and CRM in one seamless flow that maximises revenue per visitor." },
            { id: "cb-5-4", type: "stat", number: "22%", label: "avg conversion lift" },
            { id: "cb-5-5", type: "stat", number: "5 min", label: "funnel setup time" },
            { id: "cb-5-6", type: "tags", tags: ["Funnels", "Upsells", "Checkout"] },
            { id: "cb-5-7", type: "cta", text: "Build a Funnel", link: "#" },
          ],
        },
      ],
    },
  },
  [BlockTypes.STATS]: {
    name: "Stats Cards",
    icon: "📊",
    category: "Social Proof",
    description: "Display key statistics",
    defaultProps: {
      title: "A website should be the start of the sales system",
      subtitle: "Built to help you launch faster, capture more leads, and manage follow-up from one connected platform.",
      statsVariant: "editorial-band",
      backgroundColor: "linear-gradient(180deg,#ffffff,#f8fafc)",
      textColor: "#0f172a",
      borderColor: "rgba(226,232,240,0.92)",
      cardBackgroundColor: "rgba(255,255,255,0.9)",
      accentColor: "#0ea5e9",
      stats: [
        {
          number: "1",
          label: "All-In-One Platform",
          detail: "Build websites, funnels, landing pages, CRM, bookings, email and automation inside one workspace.",
        },
        {
          number: "24/7",
          label: "Lead Capture & Follow-Up",
          detail: "Capture enquiries around the clock and keep prospects moving with automated follow-up.",
        },
        {
          number: "0",
          label: "Code Needed",
          detail: "Update pages, forms, content and campaigns without waiting on a developer.",
        },
        {
          number: "100%",
          label: "Owned Inside Gr8 Result",
          detail: "Keep your website, marketing tools, leads and business systems together in Gr8 Result.",
        },
      ],
    },
  },
  [BlockTypes.TEAM]: {
    name: "Team Section",
    icon: "👥",
    category: "Social Proof",
    description: "Showcase team members",
    defaultProps: {
      title: "Meet the Team",
      subtitle: "Introduce the people clients will trust with the work.",
      teamVariant: "studio-cards",
      backgroundColor: "linear-gradient(180deg,#ffffff,#f8fafc)",
      textColor: "#0f172a",
      borderColor: "rgba(226,232,240,0.9)",
      members: [
        {
          id: "team-member-1",
          name: "Ava Bennett",
          role: "Client Strategy Lead",
          image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
          bio: "Shapes the offer, messaging, and customer journey for every launch.",
        },
        {
          id: "team-member-2",
          name: "Marcus Reed",
          role: "Creative Director",
          image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
          bio: "Turns strategy into bold visual systems, landing pages, and campaigns.",
        },
        {
          id: "team-member-3",
          name: "Nina Patel",
          role: "Automation Specialist",
          image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=900&q=80",
          bio: "Builds the follow-up, CRM, and reporting flows that keep leads moving.",
        },
      ],
    },
  },
  [BlockTypes.FAQ]: {
    name: "FAQ Section",
    icon: "❓",
    category: "Content",
    description: "Frequently asked questions",
    defaultProps: {
      title: "Common Questions",
      faqMaxWidth: 980,
      faqStartCollapsed: false,
      faqAllowMultipleOpen: false,
      items: [
        { id: "faq-default-1", question: "What is this?", answer: "This is the answer", heading: "What is this?", content: "This is the answer" },
        { id: "faq-default-2", question: "How does it work?", answer: "It works like this...", heading: "How does it work?", content: "It works like this..." },
      ],
    },
  },
  [BlockTypes.NEWSLETTER]: {
    name: "Newsletter Signup",
    icon: "📬",
    category: "Conversion",
    description: "Email subscriber form",
    defaultProps: {
      title: "Stay Updated",
      subtitle: "Get the latest tips and insights",
      placeholder: "Enter your email",
      buttonText: "Subscribe",
    },
  },
  [BlockTypes.TRUST_BADGES]: {
    name: "Trust Badges",
    icon: "✅",
    category: "Social Proof",
    description: "Display trust icons and certifications",
    defaultProps: {
      badges: [
        { icon: "🔒", label: "Secure" },
        { icon: "⭐", label: "Trusted" },
        { icon: "🏆", label: "Award Winning" },
      ],
    },
  },
  [BlockTypes.MARQUEE_STRIP]: {
    name: "Marquee Strip",
    icon: "🎞️",
    category: "Section",
    description: "Looping ticker-style text strip for kinetic messaging",
    defaultProps: {
      items: ["Strategy", "Design", "SEO", "Conversion"],
      speed: 24,
      direction: "left",
      dividerText: "*",
      dividerSize: 14,
      angle: 0,
      fontSize: 12,
      fontWeight: "800",
      fontStyle: "normal",
      textDecoration: "none",
      textStrokeWidth: 0,
      paddingTop: 16,
      paddingBottom: 16,
      itemPaddingX: 14,
      lineHeight: 1.08,
      marginTop: 0,
      marginBottom: 0,
      textTransform: "uppercase",
      backgroundColor: "#081120",
      textColor: "#f8fafc",
      textFillColor: "#f8fafc",
      textStrokeColor: "transparent",
      accentColor: "#7dd3fc",
      fullWidthBackground: true,
      sectionAnimation: "fade-in",
      sectionAnimationDelay: 0.04,
    },
  },
  [BlockTypes.WAVE_MARQUEE]: {
    name: "Wave Marquee",
    icon: "~",
    category: "Section",
    description: "Wavy scrolling text like a kinetic agency banner",
    defaultProps: {
      text: "FULL SERVICE MARKETING AGENCY",
      separator: " * ",
      repeatCount: 4,
      speed: 22,
      direction: "left",
      height: 190,
      amplitude: 42,
      wavelength: 640,
      angle: -2,
      fontSize: 22,
      fontWeight: "900",
      letterSpacing: 2.6,
      textTransform: "uppercase",
      backgroundColor: "#000000",
      textColor: "#00a99d",
      fullWidthBackground: true,
      sectionAnimation: "fade-in",
      sectionAnimationDelay: 0.04,
    },
  },
  [BlockTypes.IMAGE_STACK]: {
    name: "Layered Image Stack",
    icon: "🖼️",
    category: "Media",
    description: "Free-layout canvas with movable image, text, and logo layers",
    defaultProps: {
      title: "Layered Visual Canvas",
      fullWidthBackground: true,
      minHeight: "72vh",
      baseLayoutWidth: 1100,
      backgroundColor: "transparent",
      showGrid: true,
      snapToGrid: true,
      images: [],
    },
  },
  [BlockTypes.ICON_COUNTER]: {
    name: "Site Visit Counter",
    icon: "📈",
    category: "Social Proof",
    description: "Animated number counter with a decorative diamond icon — matches the WP homepage counter style.",
    defaultProps: {
      label: "Site Visits...and counting",
      targetNumber: 120,
      startNumber: 0,
      suffix: "",
      backgroundColor: "#0b0c1a",
      numberColor: "#0c8ce9",
      diamondColor: "rgba(255,255,255,0.15)",
      labelColor: "rgba(255,255,255,0.85)",
      numberFontSize: 78,
      numberFontFamily: "inherit",
      labelFontSize: 22,
      labelFontFamily: "inherit",
      labelFontWeight: "600",
      projectId: "",
      minHeight: "180px",
    },
  },
  [BlockTypes.CUSTOM_HTML]: {
    name: "Custom HTML",
    icon: "</>",
    category: "Widgets",
    description: "Paste any HTML, embed code, or third-party widget script",
    defaultProps: {
      html: "",
      backgroundColor: "transparent",
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
  [BlockTypes.HOVER_CARDS]: {
    name: "Hover Cards",
    icon: "🃏",
    category: "Section",
    description: "Carousel of image cards — hover to reveal a dark overlay with title, description, and a Learn More button",
    defaultProps: {
      sectionTitle: "Our Services",
      sectionTitleColor: "#0f172a",
      sectionTitleSize: 32,
      backgroundColor: "#f8fafc",
      cardColor: "#dde3ea",
      visibleCards: 3,
      cardHeight: 320,
      cardRadius: 12,
      cardGap: 16,
      cardPadding: 20,
      fullWidth: false,
      minCardWidth: 280,
      continuousLoop: true,
      continuousSpeed: 45,
      autoPlayInterval: 3500,
      paddingTop: 48,
      paddingBottom: 48,
      paddingSides: 40,
      maxWidth: 1200,
      hoverBackgroundColor: "rgba(0,0,0,0.85)",
      overlayColor: "rgba(0,0,0,0.85)",
      buttonText: "Learn more →",
      buttonColor: "#ffffff",
      buttonTextColor: "#0f172a",
      arrowBg: "#ffffff",
      arrowColor: "#0f172a",
      dotsColor: "#cbd5e1",
      dotsActiveColor: "#0f172a",
      cards: [
        { id: "hc-1", title: "Landing Pages", description: "Create stunning pages in minutes with our drag-and-drop editor.", image: "", cardColor: "#dbeafe", hoverBackgroundColor: "", link: "#" },
        { id: "hc-2", title: "Email Marketing", description: "Engage and grow your customer base with beautiful email campaigns.", image: "", cardColor: "#dcfce7", hoverBackgroundColor: "", link: "#" },
        { id: "hc-3", title: "Memberships", description: "Earn recurring revenue from your content with membership tools.", image: "", cardColor: "#fef3c7", hoverBackgroundColor: "", link: "#" },
        { id: "hc-4", title: "Form Builder", description: "Optimise growth with opt-in forms that convert visitors to leads.", image: "", cardColor: "#fae8ff", hoverBackgroundColor: "", link: "#" },
        { id: "hc-5", title: "Analytics", description: "Track every click, conversion, and customer journey in real time.", image: "", cardColor: "#ecfdf5", hoverBackgroundColor: "", link: "#" },
      ],
    },
  },
  [BlockTypes.TEMPLATE_SHOWCASE]: {
    name: "Template Showcase",
    icon: "Desktop",
    category: "Hero",
    description: "Animated website template wall with desktop and mobile previews",
    defaultProps: {
      eyebrow: "AI Website Builder",
      headline: "Launch a site that already feels custom",
      subheadline: "Pick a proven layout, let AI shape the copy, then customise every section with the same builder your clients use.",
      ctaText: "Start My Website",
      ctaLink: "#contact-us",
      secondaryCtaText: "View Templates",
      secondaryCtaLink: "#templates",
      fullWidthBackground: true,
      backgroundColor: "#080b14",
      textColor: "#f8fafc",
      mutedTextColor: "#b8c2d8",
      accentColor: "#24d3ee",
      secondaryAccentColor: "#8b5cf6",
      cardBackground: "#ffffff",
      speed: 34,
      reverse: false,
      showDeviceFocus: true,
      minHeight: "720px",
      stats: [
        { value: "80+", label: "industry layouts" },
        { value: "5 min", label: "AI first draft" },
        { value: "100%", label: "editable sections" },
      ],
      templates: [
        { title: "Electrician", category: "Trades", palette: "#fbbf24", image: "wires", cta: "Quote-ready" },
        { title: "Fitness Studio", category: "Bookings", palette: "#22c55e", image: "fitness", cta: "Class-ready" },
        { title: "Beauty Clinic", category: "Services", palette: "#ec4899", image: "beauty", cta: "Book online" },
        { title: "Real Estate", category: "Listings", palette: "#38bdf8", image: "property", cta: "Lead capture" },
        { title: "Restaurant", category: "Hospitality", palette: "#f97316", image: "food", cta: "Reserve now" },
        { title: "Accountant", category: "Professional", palette: "#6366f1", image: "finance", cta: "Consultation" },
        { title: "Solar", category: "Energy", palette: "#84cc16", image: "solar", cta: "Savings check" },
        { title: "Online Store", category: "Ecommerce", palette: "#14b8a6", image: "store", cta: "Shop now" },
      ],
    },
  },
  [BlockTypes.SIDE_SCROLL_ACCORDION]: {
    name: "Side Scroll Accordion",
    icon: "Side",
    category: "Interactive",
    description: "Scroll-down side accordion where cards slide in from the right and stack",
    defaultProps: {
      eyebrow: "Website growth system",
      title: "What your website needs to do",
      subtitle: "A finished business website needs relevant pages, useful copy, strong images, local SEO, lead capture and follow-up.",
      backgroundColor: "#07111f",
      textColor: "#ffffff",
      mutedTextColor: "#b8c2d8",
      accentColor: "#00d5ff",
      fullWidthBackground: true,
      displayMode: "side-stack",
      showButtons: true,
      buttonText: "Explore More",
      buttonUrl: "#contact-us",
      buttonFullWidth: false,
      peekWidth: 78,
      autoScroll: true,
      speed: 42,
      cardWidth: 410,
      cardHeight: 520,
      items: [
        {
          eyebrow: "SEO foundations",
          title: "Search-ready pages",
          body: "Build service pages, location copy, FAQs, metadata and internal links around the terms real buyers search for.",
          image: "/assets/website-builder/2208a52a-8175-477e-823c-fc6de7fe4afe/ai-website-builder-no-code.png",
          tags: ["SEO", "service pages", "local search"],
        },
        {
          eyebrow: "No code editing",
          title: "Drag, drop and publish",
          body: "Use visual controls for sections, images, buttons, forms, spacing and mobile layouts without touching code.",
          image: "/assets/website-builder/2208a52a-8175-477e-823c-fc6de7fe4afe/ai-website-builder-builder-preview.png",
          tags: ["drag and drop", "mobile", "publish"],
        },
        {
          eyebrow: "Lead conversion",
          title: "Forms connected to CRM",
          body: "Turn visitors into contacts, quote requests, booking enquiries and follow-up automations inside Gr8 Result.",
          image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=80",
          tags: ["CRM", "bookings", "automation"],
        },
      ],
    },
  },
  [BlockTypes.FRAMER_PORTFOLIO]: {
    name: "Framer Portfolio",
    icon: "🎨",
    category: "Templates",
    description: "Horizontal scrolling carousel of full-image cards — click to reveal summary + Learn More",
    defaultProps: {
      title: "Selected Projects",
      subtitle: "A collection of recent work",
      backgroundColor: "#0a0a0a",
      textColor: "#ffffff",
      accentColor: "#a78bfa",
      visibleCount: 2.5,
      cardHeight: 520,
      cardRadius: 12,
      autoScroll: false,
      scrollMode: "card",
      loopScroll: true,
      pauseOnHover: true,
      cardScrollInterval: 2500,
      continuousScrollSpeed: 45,
      buttonText: "Learn More",
      buttonColor: "#ffffff",
      buttonTextColor: "#0f172a",
      arrowBackgroundColor: "rgba(255,255,255,0.12)",
      arrowColor: "#ffffff",
      cards: [
        { id: "fp-1", title: "Brand Redesign", desc: "A full rebrand for a SaaS company.", image: "/templates/gallery/framer-animated-portfolio/project1.jpg", link: "#" },
        { id: "fp-2", title: "Animated Landing Page", desc: "A Framer-powered animated hero.", image: "/templates/gallery/framer-animated-portfolio/project2.jpg", link: "#" },
        { id: "fp-3", title: "Mobile App UI", desc: "A smooth, animated mobile UI.", image: "/templates/gallery/framer-animated-portfolio/project3.jpg", link: "#" },
      ],
      fullWidthBackground: true,
    },
  },
  [BlockTypes.CHART]: {
    name: "Savings Chart",
    icon: "📊",
    category: "Data",
    description: "Grouped bar chart comparing individual module costs vs. billing page pricing with savings callouts",
    defaultProps: {
      heading: "Stop Paying Full Price",
      subheading: "Every plan saves you real money — compared to buying each module separately",
      backgroundColor: "#0f172a",
      textColor: "#f8fafc",
      plans: getPlatformChartPlans(),
      showAnnualSavings: true,
      fullWidthBackground: true,
      baseLayoutWidth: 1500,
    },
  },
  [BlockTypes.FOOTER]: {
    name: "Footer",
    icon: "🔻",
    category: "Section",
    description: "Site footer with logo, nav links, newsletter signup, and copyright",
    defaultProps: {
      backgroundColor: "#0f172a",
      textColor: "#e2e8f0",
      linkColor: "#94a3b8",
      borderColor: "rgba(148,163,184,0.2)",
      logo: "",
      logoWidth: 48,
      brand: "Your Brand",
      tagline: "Building something amazing.",
      contactHeading: "Contact",
      contactEmail: "hello@yourbrand.com",
      contactPhone: "(555) 010-2026",
      contactAddress: "Your city, state",
      navHeading: "Navigation",
      navLinks: [
        { label: "Home", href: "#home" },
        { label: "About", href: "#about" },
        { label: "Services", href: "#services" },
        { label: "Contact", href: "#contact" },
      ],
      extraHeading: "Company",
      extraLinks: [
        { label: "Blog", href: "#blog" },
        { label: "Privacy Policy", href: "#privacy" },
        { label: "Terms", href: "#terms" },
      ],
      showNewsletter: true,
      newsletterHeading: "Stay Updated",
      newsletterSubtitle: "Get the latest news delivered to your inbox.",
      newsletterButtonText: "Subscribe",
      newsletterButtonColor: "#2563eb",
      newsletterButtonTextColor: "#ffffff",
      newsletterActionUrl: "",
      newsletterSubmitMethod: "post",
      newsletterFallbackEmail: "",
      copyrightText: "© 2025 Your Brand. All rights reserved.",
    },
  },

  [BlockTypes.COMPETITOR_COMPARISON]: {
    name: "Competitor Comparison",
    icon: "💸",
    category: "Conversion",
    description: "\"What you'd pay elsewhere\" savings table with competitor logos",
    defaultProps: COMPETITOR_COMPARISON_TEMPLATE_PROPS,
  },
  [BlockTypes.SCROLL_STACK]: {
    name: "Scroll Stack",
    icon: "🃏",
    category: "Interaction",
    description: "Full-page panels that stack as you scroll — image on one side, text on the other",
    defaultProps: {
      panels: [
        {
          id: "ss-panel-1",
          eyebrow: "Email Marketing",
          eyebrowDot: true,
          heading: "Maximise engagement with every contact",
          body: "Effortlessly engage with your audience at every stage. Automate follow-ups, personalise at scale, and never miss an opportunity.",
          showCta: true,
          ctaText: "Get Started",
          ctaUrl: "#",
          ctaStyle: "pill",
          image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1400&q=80",
          imageAlt: "Team collaborating",
          imageStyle: "card",
          imageCardBg: "rgba(255,255,255,0.15)",
          imagePosition: "right",
          backgroundColor: "#0d9488",
          textColor: "#ffffff",
          accentColor: "#5eead4",
        },
        {
          id: "ss-panel-2",
          eyebrow: "CRM",
          eyebrowDot: true,
          heading: "Manage everything, from anywhere",
          body: "A mobile experience that makes it easy to manage your pipeline on the go. Log calls, check statuses, and add activities whenever you need to.",
          showCta: true,
          ctaText: "Explore CRM",
          ctaUrl: "#",
          ctaStyle: "pill",
          image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1400&q=80",
          imageAlt: "Mobile app interface",
          imageStyle: "card",
          imageCardBg: "rgba(255,255,255,0.15)",
          imagePosition: "right",
          backgroundColor: "#1a73e8",
          textColor: "#ffffff",
          accentColor: "#93c5fd",
        },
        {
          id: "ss-panel-3",
          eyebrow: "AI Automation",
          eyebrowDot: true,
          heading: "Work smarter with built-in AI",
          body: "Your AI workforce runs around the clock, handling tasks, answering questions, and keeping your business moving — even while you sleep.",
          showCta: true,
          ctaText: "Explore AI features",
          ctaUrl: "#",
          ctaStyle: "pill",
          image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&w=1400&q=80",
          imageAlt: "AI interface",
          imageStyle: "card",
          imageCardBg: "rgba(255,255,255,0.15)",
          imagePosition: "right",
          backgroundColor: "#7c3aed",
          textColor: "#ffffff",
          accentColor: "#c4b5fd",
        },
      ],
    },
  },

  [BlockTypes.AVATAR_MORPH]: {
    name: "Avatar Morph Reveal",
    icon: "🧍",
    category: "Interactive",
    description: "Three avatar images that crossfade as the section scrolls into view. Feature blocks fly outward from the avatar like they're emerging from behind.",
    defaultProps: {
      eyebrow: "Powered by Intelligent Automation",
      title: "Watch the system come alive",
      subtitle: "Three simple actions — one unstoppable flow. Each step fuels the next.",
      ctaText: "See It In Action",
      ctaUrl: "#",
      backgroundColor: "#080e1b",
      accentColor: "#6366f1",
      textColor: "#ffffff",
      avatarArmsIn: "",
      avatarArmsMid: "",
      avatarArmsOut: "",
      flyBlocks: [],
    },
  },

  [BlockTypes.VIDEO_HERO]: {
    name: "Video Hero",
    icon: "🎬",
    category: "Hero",
    description: "Full-bleed locally-hosted video that lazy-loads when scrolled into view. Upload your video to Supabase — no external services.",
    defaultProps: {
      videoSrc: "",
      posterSrc: "",
      heightMode: "full",
      minHeight: 620,
      autoplay: true,
      muted: true,
      loop: true,
      showControls: false,
      startWithAudio: false,
      playAudioOnInteraction: false,
      objectFit: "cover",
      objectPosition: "top center",
      overlayColor: "#000000",
      overlayOpacity: 0.42,
      showText: true,
      eyebrow: "",
      title: "",
      subtitle: "",
      ctaText: "",
      ctaUrl: "#",
      textColor: "#ffffff",
      accentColor: "#6366f1",
    },
  },
};
