export const COMPETITOR_COMPARISON_ROWS = [
  { category: "CRM & PIPELINE MANAGEMENT",  logos: [{ domain: "hubspot.com", name: "HubSpot" }, { domain: "salesforce.com", name: "Salesforce" }, { domain: "pipedrive.com", name: "Pipedrive" }],             price: 97 },
  { category: "EMAIL MARKETING",             logos: [{ domain: "mailchimp.com", name: "Mailchimp" }, { domain: "activecampaign.com", name: "ActiveCampaign" }, { domain: "klaviyo.com", name: "Klaviyo" }],     price: 99 },
  { category: "FUNNELS & WEBSITE BUILDER",   logos: [{ domain: "clickfunnels.com", name: "ClickFunnels" }, { domain: "leadpages.com", name: "Leadpages" }, { domain: "unbounce.com", name: "Unbounce" }],       price: 97 },
  { category: "2-WAY SMS MARKETING",         logos: [{ domain: "twilio.com", name: "Twilio" }, { domain: "simpletexting.com", name: "SimpleTexting" }, { domain: "attentivemobile.com", name: "Attentive" }],  price: 89 },
  { category: "BOOKING & APPOINTMENTS",      logos: [{ domain: "calendly.com", name: "Calendly" }, { domain: "acuityscheduling.com", name: "Acuity" }, { domain: "squareup.com", name: "Square" }],             price: 29 },
  { category: "WORKFLOW AUTOMATIONS",        logos: [{ domain: "hubspot.com", name: "HubSpot" }, { domain: "zapier.com", name: "Zapier" }, { domain: "keap.com", name: "Keap" }],                               price: 169 },
  { category: "COURSES / PRODUCTS",          logos: [{ domain: "teachable.com", name: "Teachable" }, { domain: "kajabi.com", name: "Kajabi" }, { domain: "thinkific.com", name: "Thinkific" }],                 price: 99 },
  { category: "CALL TRACKING",               logos: [{ domain: "callrail.com", name: "CallRail" }, { domain: "twilio.com", name: "Twilio" }],                                                                   price: 49 },
  { category: "REPUTATION MANAGEMENT",       logos: [{ domain: "birdeye.com", name: "Birdeye" }, { domain: "podium.com", name: "Podium" }, { domain: "grade.us", name: "Grade.us" }],                          price: 159 },
  { category: "TRACKING & ANALYTICS",        logos: [{ domain: "amplitude.com", name: "Amplitude" }, { domain: "mixpanel.com", name: "Mixpanel" }],                                                            price: 299 },
  { category: "COMMUNITIES",                 logos: [{ domain: "skool.com", name: "Skool" }, { domain: "mightynetworks.com", name: "Mighty Networks" }, { domain: "circle.so", name: "Circle" }],              price: 89 },
  { category: "DOCUMENT SIGNING",            logos: [{ domain: "docusign.com", name: "DocuSign" }, { domain: "pandadoc.com", name: "PandaDoc" }],                                                              price: 47 },
  { category: "GHANTT CHARTS JOB BOARDS",    logos: [{ domain: "clickup.com", name: "ClickUp" }, { src: "https://bvtxfphktypdqmlnveqf.supabase.co/storage/v1/object/public/assets/35ab846e-0764-498b-b1f8-7d2cf27d85a5/web-1780184964941-aha-logo-2x.png", domain: "", name: "Aha" }], price: 39 },
];

export const COMPETITOR_COMPARISON_TEMPLATE_PROPS = {
  title: "What you'd pay elsewhere",
  eyebrow: "our All-in-One Platform",
  subtitle: "We replace every tool below — one platform, one price.",
  planName: "COMPETITOR ANALYSIS",
  planPrice: 359,
  planTagline: "Everything above, included",
  alignment: "center",
  textColor: "#ffffff",
  fontFamily: "system-ui",
  fontWeight: "700",
  lineHeight: 1.04,
  textFontSize: 40,
  textLineHeight: 1.04,
  backgroundColor: "#121c26",
  baseLayoutWidth: 1500,
  rows: COMPETITOR_COMPARISON_ROWS,
};
