import {useMemo,useState} from 'react';
import VerifiedProductImage from './VerifiedProductImage';
import {internalProductOptions,prepareInternalSelection} from '../../lib/product-library/internalSelection.js';
export default function InternalCataloguePicker({products,requirement,selection,onSelect,onBack,onSave}) {
 const [brand,setBrand]=useState(''),[range,setRange]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[active,setActive]=useState(null),[choices,setChoices]=useState({}),[error,setError]=useState('');
 const filtered=useMemo(()=>products.filter(p=>(!brand||p.brand===brand)&&(!range||p.range===range)&&[p.productName,p.model,p.profile,p.finish,p.description].join(' ').toLowerCase().includes(search.toLowerCase())),[products,brand,range,search]);
 const saved=selection?.selected_details||selection?.guidedSelection||{};
 const open=p=>{const options=internalProductOptions(p);setChoices({...Object.fromEntries(Object.entries(options).map(([k,v])=>[k,saved.productId===(p.productId||p.id)&&v.includes(saved[k])?saved[k]:v[0]||''])),quantity:saved.productId===(p.productId||p.id)?saved.quantity||1:1});setActive(p);setError('');};
 const price=p=>p.priceState==='Current Price'?new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(p.selectedCost):'Quote required';
 return <section data-testid="internal-catalogue-picker" style={{padding:20,display:'grid',gap:16}}>
  <div><button type="button" onClick={onBack}>Back to Interior selections</button> <button type="button" onClick={onSave}>Save Progress</button></div>
  <h2>{requirement.label}</h2><p>Choose from enabled Product Library products. {filtered.length} products available.</p>
  {saved.productId?<p data-testid="internal-saved-selection">Selected: {saved.brand} {saved.productName} · {saved.size} · {saved.finish} · {saved.function} · {saved.quantity} {saved.unit}</p>:null}
  <div style={{display:'flex',gap:12,flexWrap:'wrap'}}><label>Brand <select aria-label="Internal product brand" value={brand} onChange={e=>{setBrand(e.target.value);setRange('');setPage(0);}}><option value="">All brands</option>{[...new Set(products.map(p=>p.brand))].sort().map(b=><option key={b}>{b}</option>)}</select></label>
   <label>Range <select aria-label="Internal product range" value={range} onChange={e=>{setRange(e.target.value);setPage(0);}}><option value="">All ranges</option>{[...new Set(products.filter(p=>!brand||p.brand===brand).map(p=>p.range))].filter(Boolean).sort().map(r=><option key={r}>{r}</option>)}</select></label><label>Search <input aria-label="Search internal products" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(250px,1fr))',gap:16}}>{filtered.slice(page*24,page*24+24).map(p=><article key={p.id||p.productId} data-testid="internal-product-card" style={{padding:14,border:saved.productId===(p.productId||p.id)?'3px solid #1764d9':'1px solid #cbd5e1',borderRadius:10}}>
   <VerifiedProductImage src={p.imageUrl||p.primaryImageUrl} name={p.productName} style={{width:'100%',height:220}}/>{p.metadata?.productEntity?.attributes?.imageScope||p.attributes?.imageScope?<small>{p.metadata?.productEntity?.attributes?.imageScope||p.attributes?.imageScope}</small>:null}<strong>{p.brand}</strong><h3>{p.productName}</h3><p>{p.range} · {p.model}</p><p>{p.description}</p><p>{price(p)}</p>
   <button type="button" data-testid="select-internal-product" onClick={()=>open(p)} style={{background:'#1764d9',color:'white',padding:'10px 18px',fontWeight:700}}>{saved.productId===(p.productId||p.id)?'Selected — Change':'Select'}</button> <button type="button" onClick={()=>open(p)}>View Details</button>
  </article>)}</div>
  <div><button type="button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button> Page {page+1} of {Math.max(1,Math.ceil(filtered.length/24))} <button type="button" disabled={(page+1)*24>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  {active?<div role="dialog" aria-modal="true" aria-label="Internal product options" data-testid="internal-product-options" style={{position:'fixed',inset:0,zIndex:1500,background:'#0008',display:'grid',placeItems:'center'}}><section style={{background:'white',color:'#172337',padding:24,borderRadius:16,width:'min(620px,95vw)',maxHeight:'90vh',overflowY:'auto',display:'grid',gap:12}}><h3>{active.brand} {active.productName}</h3><VerifiedProductImage src={active.imageUrl||active.primaryImageUrl} name={active.productName} style={{width:'100%',height:160}}/><p>{active.description}</p>
   {Object.entries(internalProductOptions(active)).map(([key,values])=>values.length?<label key={key}>{key==='function'?'Function':key[0].toUpperCase()+key.slice(1)}<select aria-label={`Internal ${key}`} value={choices[key]} onChange={e=>setChoices(c=>({...c,[key]:e.target.value}))} style={{display:'block',width:'100%'}}>{values.map(v=><option key={v}>{v}</option>)}</select></label>:null)}
   <label>Quantity<input aria-label="Internal quantity" type="number" min="0.01" step="any" value={choices.quantity} onChange={e=>setChoices(c=>({...c,quantity:e.target.value}))}/></label>
   <p>{(()=>{try{return price(prepareInternalSelection(active,choices));}catch{return 'Enter a valid quantity';}})()}</p><small>{(active.metadata?.productEntity?.attributes||active.attributes)?.priceNote}</small>{(active.metadata?.productEntity?.attributes||active.attributes)?.priceRegion?<small>Published {(active.metadata?.productEntity?.attributes||active.attributes).priceRegion} price, GST inclusive.</small>:null}<a href={active.productUrl||active.officialProductUrl} target="_blank" rel="noreferrer">Official manufacturer product</a>{error?<p role="alert">{error}</p>:null}
   <button type="button" onClick={()=>{try{const next=prepareInternalSelection(active,choices);onSelect(requirement,next);setActive(null);}catch(e){setError(e.message);}}} style={{background:'#1764d9',color:'white',padding:12}}>Confirm Selection</button><button type="button" onClick={()=>setActive(null)}>Cancel</button>
  </section></div>:null}
 </section>;
}
