import {useEffect,useState} from 'react';
import {CS_TYPE} from '../../lib/builders/clientSelectionsTypography.js';
import {STAIR_STEPS,stairEntity,isCompleteStair,stairOptions,compatibleStairOptions,reconcileStairConfiguration,validateStairStep,prepareStairSelection,stairPricing} from '../../lib/product-library/stairSelection.js';
import {resolveStairFlight,stairHeightSnapshot} from '../../lib/construction-estimation/stairGeometry.js';
import StairHeightPanel from './StairHeightPanel.jsx';

// A job whose Job Setup has no second level still gets a stair: both heights are entered here.
const MANUAL_FLIGHT={flightKey:'manual',label:'Stair - no second level in Job Setup, enter the heights',ceilingHeight:{valueMm:null,source:'Not set in Job Setup',fieldLabel:'Lower ceiling height'},floorThickness:{valueMm:null,source:'Not set in Job Setup',fieldLabel:'upper floor system'}};

const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:14};
const money=value=>value==null?'Quote required':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(value);
const WizardType=()=><style>{`.stairWizard{font-size:${CS_TYPE.body}px;line-height:1.45}.stairWizard button,.stairWizard input,.stairWizard select{font-family:inherit;font-size:${CS_TYPE.button}px}.stairWizard small,.stairWizard p,.stairWizard label,.stairWizard li,.stairWizard td,.stairWizard th{font-size:${CS_TYPE.body}px}.stairWizard h2{font-size:${CS_TYPE.pageTitle}px;margin:0}.stairWizard h3{font-size:${CS_TYPE.cardTitle}px;margin:0}.stairWizard h4{font-size:${CS_TYPE.productName}px;margin:8px 0 0}.stairWizard [data-option-id] strong{font-size:${CS_TYPE.productName}px}.stairWizard .stairNav{min-height:48px;padding:12px 20px;border-radius:10px;border:1px solid #b8c6d8;background:#fff;color:#172337;font-weight:800;cursor:pointer}.stairWizard .stairNav.primary{background:#0f766e;border-color:#0f766e;color:#fff}.stairWizard .stairNav:disabled{opacity:.45;cursor:default}`}</style>;
function Cards({options,value,onChange,testId}){
 return <div style={grid}>{options.map(option=><button type="button" key={option.id} data-testid={testId} data-option-id={option.id} aria-pressed={value===option.id} onClick={()=>onChange(option.id)} style={{padding:12,border:value===option.id?'3px solid #1764d9':'1px solid #b8c6d8',borderRadius:10,background:value===option.id?'#edf5ff':'white',color:'#172337',textAlign:'left',cursor:'pointer'}}>{option.imageUrl?<img src={option.imageUrl} alt={option.name} style={{width:'100%',height:160,objectFit:'contain',background:'#f5f7fa'}}/>:null}<strong style={{display:'block',margin:'8px 0'}}>{option.name}</strong>{option.aliases?.length?<small>Also known as {option.aliases.join(', ')}</small>:null}{option.description?<p>{option.description}</p>:null}{option.typicalUse?<small style={{display:'block'}}>{option.typicalUse}</small>:null}{option.finishSuitability?<small style={{display:'block',marginTop:6}}>Suitable finishes: {option.finishSuitability}</small>:null}{option.availabilityStatus?<small style={{display:'block',marginTop:6}}>{option.availabilityStatus} · {option.allowanceRate!=null?`${money(option.allowanceRate)}/lm · Builder allowance, ex GST`:money(option.priceAdjustment)}</small>:null}{option.imageScope?<small style={{display:'block',marginTop:6}}>{option.imageScope}</small>:null}</button>)}</div>;
}
export default function StairSelectionWizard({products=[],stairFlights=[],selection,requirement={requirementKey:'stairs',label:'Stairs'},onSelect,onBack,backLabel='Back to Interior selections',onSave,storageKey,initialProductId='',preview=false}) {
 const stairs=products.filter(p=>isCompleteStair(p)&&stairEntity(p).active!==false&&!stairEntity(p).attributes.estimatingOnly);
 const saved=selection?.selected_details||selection?.guidedSelection||{};
 const [configuration,setConfiguration]=useState({productId:initialProductId,quantity:1,supplier:'Builder nominated supplier'}),[step,setStep]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 const product=stairs.find(p=>stairEntity(p).productId===configuration.productId),options=stairOptions(product),compatible=compatibleStairOptions(product,configuration);
 useEffect(()=>{if(!stairs.length)return;let draft;try{draft=storageKey?JSON.parse(localStorage.getItem(storageKey)||'null'):null;}catch{}const c=draft?.configuration||saved.stairConfiguration||{productId:initialProductId,quantity:1,supplier:'Builder nominated supplier'};const p=stairs.find(p=>stairEntity(p).productId===c.productId);setConfiguration(p?reconcileStairConfiguration(p,c):{quantity:1,supplier:'Builder nominated supplier'});setStep(p?Math.min(2,draft?.version===2?(draft?.step||0):[0,0,1,2,2,2][draft?.step||0]):0);setReady(true);},[storageKey,stairs.length]);
 useEffect(()=>{if(!ready||!storageKey)return;try{localStorage.setItem(storageKey,JSON.stringify({version:2,configuration,step,updatedAt:new Date().toISOString()}));}catch{}},[ready,storageKey,configuration,step]);
 const update=patch=>{setConfiguration(c=>({...c,...patch}));setError('');setConfirmed(false);};
 const chooseType=id=>{const p=stairs.find(p=>stairEntity(p).productId===id);setConfiguration(c=>{const next=reconcileStairConfiguration(p,c);if(stairEntity(p).attributes.finishIds.length===1)next.finishId=stairEntity(p).attributes.finishIds[0];return next;});setError('');setConfirmed(false);};
 const pricing=product?stairPricing(product,configuration):null;
 // Stair height: Job Setup values (stairFlightsFromJobSetup) through the one shared calculation
 // (stairGeometry.js). Overrides belong to this stair only; Job Setup is never changed from here.
 const flights=stairFlights.length?stairFlights:[MANUAL_FLIGHT];
 const flight=flights.find(f=>f.flightKey===configuration.flightKey)||flights[0];
 const heightOverrides=configuration.heightOverrides||{};
 const resolvedHeight=resolveStairFlight(flight,heightOverrides);
 const heightSignature=JSON.stringify(stairHeightSnapshot(resolvedHeight));
 useEffect(()=>{if(!ready||!resolvedHeight)return;const snapshot=JSON.parse(heightSignature);const floorHeightMm=resolvedHeight.floorToFloorMm??'';const risers=resolvedHeight.riserCount??'';setConfiguration(c=>c.flightKey===flight.flightKey&&c.floorHeightMm===floorHeightMm&&c.risers===risers&&JSON.stringify(c.stairHeight||null)===heightSignature?c:{...c,flightKey:flight.flightKey,floorHeightMm,risers,stairHeight:snapshot});},[ready,heightSignature,flight.flightKey]); // eslint-disable-line react-hooks/exhaustive-deps
 const setHeightOverride=(key,value)=>{const next={...heightOverrides};if(value===''||value===null||value===undefined)delete next[key];else next[key]=Number(value);update({heightOverrides:next});};
 const resetHeightOverride=key=>{const next={...heightOverrides};delete next[key];update({heightOverrides:next});};
 // With no stair systems enabled the draft-restore effect never runs, so say so instead of loading forever.
 if(!stairs.length)return <section className="stairWizard" data-testid="stair-selection-wizard-empty" style={{padding:20,display:'grid',gap:14,color:'#172337',background:'#fff',borderRadius:12,fontSize:18}}><WizardType/><div><button type="button" className="stairNav" onClick={onBack}>{preview?'Close stair preview':backLabel}</button></div><h2>Stairs</h2><p>No stair systems are enabled in the Product Library for this builder yet. Enable stair systems in the Product Library to make them selectable here.</p></section>;
 if(!ready)return <p>Loading stair configuration…</p>;
 return <section className="stairWizard" data-testid="stair-selection-wizard" data-stair-step={step} style={{padding:20,display:'grid',gap:18,color:'#172337',background:'#fff',borderRadius:12}}>
  <WizardType/><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><button type="button" className="stairNav" data-testid="stair-back" onClick={onBack}>{preview?'Close stair preview':backLabel}</button>{onSave?<button type="button" className="stairNav" onClick={onSave}>Save Progress</button>:null}</div>
  <h2>Stairs</h2><p>Choose one complete staircase. Timber, balustrade and handrail options come from Product Library.</p>
  <ol aria-label="Stair selection steps" style={{display:'flex',gap:20,flexWrap:'wrap',paddingLeft:22}}>{STAIR_STEPS.map((label,index)=><li key={label} aria-current={step===index?'step':undefined} style={{fontWeight:step===index?700:400,color:step===index?'#1764d9':'#475569'}}>{label}</li>)}</ol>
  <h3>{STAIR_STEPS[step]}</h3>
  {confirmed?<p role="status" data-testid="stair-confirmed">{preview?'Configuration preview complete.':'Stair selection confirmed and saved.'}</p>:null}
  {step===0?<Cards testId="stair-type-card" options={stairs.map(p=>{const e=stairEntity(p);return {id:e.productId,name:e.productName,imageUrl:e.primaryImageUrl,description:e.attributes.treadRiserTreatment};})} value={configuration.productId} onChange={chooseType}/>:null}
  {step===0&&product?<><Cards testId="stair-plan-card" options={compatible.configurations} value={configuration.configurationId} onChange={id=>update({configurationId:id,flights:options.configurations.find(p=>p.id===id).flights})}/><div style={grid}>{[['flights','Number of flights'],['widthMm','Width (mm)'],['quantity','Quantity']].map(([key,label])=><label key={key}>{label}<input aria-label={label} type="number" min="1" step="1" value={configuration[key]??''} onChange={e=>update({[key]:e.target.value})} style={{display:'block',width:'100%',padding:10}}/></label>)}<label>Supplier<select aria-label="Stair supplier" value={configuration.supplier||''} onChange={e=>update({supplier:e.target.value})} style={{display:'block',width:'100%',padding:10}}>{options.suppliers.map(v=><option key={v}>{v}</option>)}</select></label></div><StairHeightPanel flights={flights} flightKey={flight.flightKey} resolved={resolvedHeight} onFlight={key=>update({flightKey:key,heightOverrides:{}})} onOverride={setHeightOverride} onReset={resetHeightOverride}/></>:null}
  {step===1?<>{compatible.species.length?<><h4>Timber species {stairEntity(product).attributes?.requiresExposedTimberSpecies?'(required for exposed timber)':'(optional substrate)'}</h4><Cards testId="stair-species-card" options={compatible.species} value={configuration.speciesId} onChange={id=>update(reconcileStairConfiguration(product,{...configuration,speciesId:id}))}/></>:<p data-testid="stair-no-decorative-species">Decorative timber species is not required for carpet-grade stairs. Substrate is specified by the supplier.</p>}<h4>Finish</h4><Cards testId="stair-finish-card" options={compatible.finishes} value={configuration.finishId} onChange={id=>update({finishId:id})}/><p>{stairEntity(product).attributes?.treadRiserTreatment}</p></>:null}
  {step===2?<Cards testId="stair-balustrade-card" options={compatible.balustrades} value={configuration.balustradeId} onChange={id=>{const next=reconcileStairConfiguration(product,{...configuration,balustradeId:id});update(next);}}/>:null}
  {step===2&&options.balustrades.find(b=>b.id===configuration.balustradeId)?.allowanceRate!=null?<label>Balustrade length per stair (lm)<input aria-label="Balustrade length per stair (lm)" type="number" min="0.01" step="0.01" value={configuration.balustradeLengthLm||''} onChange={e=>update({balustradeLengthLm:e.target.value})}/><p>Builder estimating allowance, AUD excluding GST. Standard handrail is included; custom handrail changes require a quote.</p></label>:null}
  {step===2?<><h4>Handrail</h4><Cards testId="stair-handrail-card" options={compatible.handrails} value={configuration.handrailMaterialId} onChange={id=>{const h=compatible.handrails.find(h=>h.id===id);update({handrailMaterialId:id,handrailProfile:h.profiles.includes(configuration.handrailProfile)?configuration.handrailProfile:h.profiles[0],handrailFinish:h.finishes.includes(configuration.handrailFinish)?configuration.handrailFinish:h.finishes[0]});}}/>{configuration.handrailMaterialId?<div style={grid}>{[['handrailProfile','Handrail profile','profiles'],['handrailFinish','Handrail finish','finishes']].map(([key,label,field])=><label key={key}>{label}<select aria-label={label} value={configuration[key]||''} onChange={e=>update({[key]:e.target.value})} style={{display:'block',width:'100%',padding:10}}><option value="">Choose {label.toLowerCase()}</option>{compatible.handrails.find(h=>h.id===configuration.handrailMaterialId)?.[field].map(v=><option key={v}>{v}</option>)}</select></label>)}</div>:null}</>:null}
  {step===2&&product?<><img src={stairEntity(product).primaryImageUrl} alt={stairEntity(product).productName} style={{width:'100%',maxHeight:280,objectFit:'contain'}}/>{options.species.find(s=>s.id===configuration.speciesId)?.imageUrl?<img data-testid="stair-review-species-image" src={options.species.find(s=>s.id===configuration.speciesId).imageUrl} alt={options.species.find(s=>s.id===configuration.speciesId).name} style={{width:220,height:100,objectFit:'cover'}}/>:null}<p data-testid="stair-review-description">{(()=>{try{return prepareStairSelection(product,configuration).description;}catch(e){return e.message;}})()}</p><table data-testid="stair-price-breakdown"><tbody><tr><th>{pricing.pricingMode==='allowance'?'Builder allowance':pricing.pricingMode==='starting_price'?'Starting price':'Complete staircase'}</th><td>{money(pricing.baseAmount)}</td></tr>{pricing.upgrades.map(v=><tr key={v.group}><th>{v.group}: {v.label}</th><td>{money(v.amount)}{v.rate!=null?` (${money(v.rate)}/lm × ${v.quantity||0} lm per stair, ex GST)`:''}</td></tr>)}</tbody></table><p>Known allowance per stair: {money(pricing.knownAllowanceTotal)}. {pricing.baseAmount==null?'Complete stair price still requires a quote.':''}</p><p>{options.compatibilityNote}</p></>:null}
  {error?<p role="alert">{error}</p>:null}
  <div style={{display:'flex',justifyContent:'space-between'}}><button type="button" className="stairNav" disabled={step===0} onClick={()=>{setStep(s=>s-1);setError('');}}>Back</button>{step<2?<button type="button" className="stairNav primary" onClick={()=>{const error=validateStairStep(product,configuration,step);if(error){setError(error);return;}setStep(s=>s+1);setError('');}}>Continue</button>:<button type="button" className="stairNav primary" onClick={()=>{try{onSelect?.(requirement,prepareStairSelection(product,configuration));setConfirmed(true);setError('');}catch(e){setError(e.message);}}}>{preview?'Complete configuration preview':'Confirm Stair Selection'}</button>}</div>
 </section>;
}
