export const ganttStyles = {
  page: {
    minHeight: "100vh",
    background: "#f1f5f9",
    fontFamily: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    color: "#0f172a",
    fontSize: 14,
  },
  // Banner
  banner:      { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, background: "linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%)", padding: "20px 28px", flexWrap: "wrap" },
  bannerLeft:  { display: "flex", alignItems: "center", gap: 18 },
  bannerIcon:  { fontSize: 44, lineHeight: 1, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(255,255,255,0.16)", borderRadius: 999, width: 68, height: 68, flexShrink: 0 },
  bannerTitle: { margin: 0, fontSize: 26, fontWeight: 700, color: "#fff", lineHeight: 1.2 },
  bannerDesc:  { margin: "3px 0 0", fontSize: 13, opacity: 0.9, color: "#fff" },
  backBtnBanner: { background: "rgba(15,23,42,0.7)", color: "#fff", border: "1px solid rgba(255,255,255,0.2)", borderRadius: 8, padding: "9px 16px", fontSize: 13, cursor: "pointer", whiteSpace: "nowrap" },
  topBar: {
    display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "14px 28px", background: "white",
    borderBottom: "2px solid #e2e8f0", gap: 16,
    position: "sticky", top: 0, zIndex: 30,
    boxShadow: "0 2px 6px rgba(0,0,0,0.08)",
  },
  topBarLeft:  { display: "flex", alignItems: "center", gap: 20 },
  topBarRight: { display: "flex", alignItems: "center", gap: 10 },
  backLink:  { color: "#475569", textDecoration: "none", fontSize: 16, fontWeight: 500, whiteSpace: "nowrap" },
  pageTitle: { margin: 0, fontSize: 28, fontWeight: 700, color: "#0f172a", lineHeight: 1.2 },
  pageSub:   { margin: "2px 0 0", fontSize: 15, color: "#475569" },
  searchInput: {
    background: "#f8fafc", border: "1px solid #cbd5e1", borderRadius: 8,
    padding: "9px 14px", fontSize: 16, color: "#0f172a", outline: "none", width: 200,
  },
  outlineBtn: {
    background: "rgba(255,255,255,0.15)", border: "1px solid rgba(255,255,255,0.3)", borderRadius: 8,
    padding: "9px 18px", fontSize: 13, fontWeight: 600, cursor: "pointer", color: "#fff",
  },
  todayBtn: {
    background: "rgba(255,255,255,0.15)", border: "1px solid rgba(255,255,255,0.3)", borderRadius: 8,
    padding: "9px 18px", fontSize: 13, fontWeight: 600, cursor: "pointer", color: "#fff",
  },
  primaryBtn: {
    background: "#fff", color: "#7c3aed", border: "none", borderRadius: 8,
    padding: "10px 22px", fontSize: 13, fontWeight: 700, cursor: "pointer",
  },
  // Stats
  statsRow: {
    display: "flex", gap: 10, padding: "12px 28px",
    background: "white", borderBottom: "2px solid #e2e8f0", flexWrap: "wrap",
  },
  statCard: {
    display: "flex", alignItems: "center", gap: 14,
    padding: "14px 20px", borderRadius: 12, border: "1px solid",
    flex: 1, minWidth: 140,
  },
  statIcon:  { width: 46, height: 46, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, flexShrink: 0 },
  statValue: { fontSize: 28, fontWeight: 700, lineHeight: 1.1 },
  statLabel: { fontSize: 15, color: "#475569", marginTop: 3, fontWeight: 600 },
  statSubLabel: { fontSize: 12, color: "#64748b", marginTop: 1, fontWeight: 700, whiteSpace: "nowrap" },
  compactStatCard: { flex: "0 1 150px", minWidth: 130, padding: "10px 12px", gap: 10, borderRadius: 10 },
  compactStatIcon: { width: 36, height: 36, borderRadius: 8, fontSize: 18 },
  compactStatValue: { fontSize: 22 },
  jobSelectorCard: { flex: "1 1 320px", minWidth: 300, padding: "10px 12px", borderRadius: 10 },
  jobSelect: {
    minWidth: 170, maxWidth: 260, flex: "1 1 180px",
    background: "white", border: "1px solid #c4b5fd", borderRadius: 8,
    color: "#312e81", fontSize: 13, fontWeight: 800,
    padding: "8px 10px", outline: "none",
  },
  contractPanel: {
    margin: "12px 28px 0", padding: "14px 16px",
    background: "white", border: "2px solid #e2e8f0", borderRadius: 12,
    display: "grid", gridTemplateColumns: "minmax(360px, 1fr) minmax(360px, 1.2fr)",
    gap: 16, alignItems: "start",
  },
  contractFields: { display: "grid", gridTemplateColumns: "repeat(6, minmax(0, 1fr))", gap: 10 },
  contractField: {
    display: "flex", flexDirection: "column", gap: 5,
    color: "#334155", fontSize: 12, fontWeight: 900,
    textTransform: "uppercase", letterSpacing: "0.04em",
  },
  contractInput: {
    background: "#f8fafc", border: "1px solid #cbd5e1", borderRadius: 8,
    color: "#0f172a", fontSize: 14, fontWeight: 800,
    padding: "8px 9px", outline: "none", width: "100%", boxSizing: "border-box",
  },
  contractSummary: { display: "flex", alignItems: "stretch", gap: 8, flexWrap: "wrap" },
  contractSummaryItem: {
    minWidth: 132, flex: "1 1 132px",
    background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 8,
    padding: "8px 10px", display: "flex", flexDirection: "column", gap: 3,
  },
  contractStatus: {
    flex: "1 1 220px", border: "1px solid", borderRadius: 8,
    padding: "8px 10px", fontSize: 13, fontWeight: 900,
    display: "flex", alignItems: "center",
  },
  // Gantt layout
  ganttWrap: {
    display: "flex", margin: "16px 28px 0",
    background: "white", borderRadius: 14, border: "2px solid #e2e8f0",
    overflow: "hidden", boxShadow: "0 2px 8px rgba(0,0,0,0.08)", minHeight: 200,
  },
  leftCol: { width: 520, minWidth: 520, flexShrink: 0, borderRight: "2px solid #e2e8f0", overflow: "hidden" },
  nameHeader: {
    height: 90, display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "0 14px", borderBottom: "2px solid #e2e8f0",
    fontSize: 14, fontWeight: 700, color: "#1e293b", background: "#f1f5f9",
    letterSpacing: "0.05em", textTransform: "uppercase",
  },
  rightCol: { flex: 1, minWidth: 0, overflowX: "auto", overflowY: "hidden", position: "relative" },
  // Left rows
  projectRow: {
    display: "flex", alignItems: "center", gap: 8,
    padding: "0 10px 0 12px", height: 56,
    cursor: "pointer", borderBottom: "1px solid #cbd5e1",
    transition: "background 0.12s", userSelect: "none",
  },
  chevron:  { fontSize: 12, width: 16, flexShrink: 0, textAlign: "center" },
  dot:      { width: 12, height: 12, borderRadius: "50%", flexShrink: 0 },
  pName:    { fontSize: 17, fontWeight: 700, color: "#0f172a", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  pSub:     { fontSize: 14, color: "#475569", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  pctLabel: { fontSize: 15, fontWeight: 700, flexShrink: 0 },
  delBtn:   { background: "none", border: "none", color: "#94a3b8", cursor: "pointer", fontSize: 14, padding: "2px 6px", flexShrink: 0, lineHeight: 1 },
  rowActionBtn: {
    background: "#e2e8f0", border: "1px solid #cbd5e1", color: "#334155",
    borderRadius: 6, padding: "3px 7px", fontSize: 11, fontWeight: 700,
    cursor: "pointer", flexShrink: 0, lineHeight: 1.2,
  },
  headerGrid: { flex: 1, minWidth: 0, display: "grid", gridTemplateColumns: "44px minmax(0, 1fr) 138px", gap: 10, alignItems: "center" },
  phaseRow: {
    display: "flex", alignItems: "center", gap: 8,
    padding: "0 10px 0 32px", height: 48,
    cursor: "pointer", borderBottom: "1px solid #cbd5e1",
    background: "#f8fafc", userSelect: "none",
  },
  phChevron: { fontSize: 12, color: "#475569", width: 14, flexShrink: 0 },
  phName:    { flex: 1, fontSize: 16, fontWeight: 600, color: "#0f172a", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  progressSpacer: { width: 138, flexShrink: 0 },
  taskRow: {
    display: "flex", alignItems: "center", gap: 8,
    padding: "0 10px 0 48px", height: 40,
    borderBottom: "1px solid #d1d9e4", background: "#f8fafc",
  },
  orderBadge: {
    width: 34, height: 24, borderRadius: 6,
    background: "#eef2ff", border: "1px solid #c7d2fe", color: "#4338ca",
    fontSize: 13, fontWeight: 800, display: "inline-flex", alignItems: "center", justifyContent: "center",
    flexShrink: 0,
  },
  insertTaskBtn: {
    width: 22, height: 22, borderRadius: 6,
    background: "#7c3aed", border: "1px solid #6d28d9", color: "#fff",
    fontSize: 14, fontWeight: 900, lineHeight: 1,
    display: "inline-flex", alignItems: "center", justifyContent: "center",
    cursor: "pointer", flexShrink: 0,
  },
  taskDot:  { width: 9, height: 9, borderRadius: "50%", flexShrink: 0 },
  taskName: { flex: 1, minWidth: 0, fontSize: 15, color: "#1e293b", fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  statusStateBtn: {
    width: 138, border: "none", background: "transparent", color: "#334155",
    padding: "4px 2px", fontSize: 13, fontWeight: 700, cursor: "pointer",
    flexShrink: 0, display: "flex", alignItems: "center", gap: 8,
    justifyContent: "flex-start", textAlign: "left",
  },
  statusStateDot: {
    width: 18, height: 18, borderRadius: "50%", flexShrink: 0,
    boxShadow: "0 0 0 3px rgba(148,163,184,0.14)",
  },
  // Ruler
  monthBand: { display: "flex", height: 34, borderBottom: "1px solid #cbd5e1", background: "#f1f5f9" },
  monthCell: {
    display: "flex", alignItems: "center", paddingLeft: 8,
    fontSize: 14, fontWeight: 700, color: "#0f172a",
    borderRight: "1px solid #cbd5e1", flexShrink: 0,
    whiteSpace: "nowrap", overflow: "hidden",
  },
  dayBand: { display: "flex", height: 30, borderBottom: "2px solid #cbd5e1", background: "#f1f5f9" },
  dayCell: {
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: 12, color: "#475569", flexShrink: 0, fontWeight: 500,
    borderRight: "1px solid #e2e8f0",
  },
  contractDayBand: { display: "flex", height: 26, borderBottom: "2px solid #cbd5e1", background: "#f8fafc" },
  contractDayCell: {
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: 9, color: "#334155", flexShrink: 0,
    borderRight: "1px solid #e2e8f0", lineHeight: 1,
  },
  // Today line
  todayLine: {
    position: "absolute", top: 0, bottom: 0, width: 2,
    background: "#ef4444", zIndex: 5, pointerEvents: "none",
  },
  todayBadge: {
    position: "absolute", top: 4, left: "50%", transform: "translateX(-50%)",
    background: "#ef4444", color: "white",
    fontSize: 12, fontWeight: 700, padding: "3px 8px", borderRadius: 4, whiteSpace: "nowrap",
  },
  contractLine: {
    position: "absolute", top: 0, bottom: 0, width: 4,
    zIndex: 6, pointerEvents: "none",
  },
  contractBadge: {
    position: "absolute", top: 4, left: "50%", transform: "translateX(-50%)",
    color: "white", fontSize: 11, fontWeight: 900,
    padding: "4px 8px", borderRadius: 4, whiteSpace: "nowrap",
    boxShadow: "0 2px 8px rgba(15,23,42,0.25)",
  },
  delayBlockLabel: {
    position: "sticky", top: 62, left: 2, display: "inline-block",
    maxWidth: "100%", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap",
    background: "#b91c1c", color: "#fff", padding: "2px 5px",
    fontSize: 10, fontWeight: 800, lineHeight: 1.2,
  },
  delayDeleteBtn: {
    position: "sticky", top: 60, left: 0,
    marginLeft: 4, width: 20, height: 20,
    borderRadius: 999, border: "1px solid #fecaca",
    background: "#fff", color: "#b91c1c",
    fontSize: 14, fontWeight: 900, lineHeight: "18px",
    cursor: "pointer", pointerEvents: "auto",
    boxShadow: "0 1px 5px rgba(15,23,42,0.2)",
  },
  // Bars
  barRow: { borderBottom: "1px solid #cbd5e1", position: "relative", display: "flex", alignItems: "center" },
  track: { position: "absolute", height: 28, borderRadius: 7, top: "50%", transform: "translateY(-50%)" },
  fill:  { position: "absolute", height: 28, borderRadius: 7, top: "50%", transform: "translateY(-50%)" },
  barPct: { position: "absolute", top: "50%", transform: "translateY(-50%)", fontSize: 14, fontWeight: 700, whiteSpace: "nowrap" },
  eotPanel: {
    margin: "12px 28px 0", padding: "14px 18px",
    background: "#fff7ed", border: "2px solid #fed7aa", borderRadius: 10,
    display: "grid", gridTemplateColumns: "auto minmax(0, 1fr)", gap: "10px 18px",
    alignItems: "center",
  },
  eotMain: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" },
  eotKicker: {
    color: "#9a3412", fontSize: 12, fontWeight: 900,
    textTransform: "uppercase", letterSpacing: "0.05em",
  },
  eotDays: { color: "#c2410c", fontSize: 32, fontWeight: 900, lineHeight: 1 },
  eotLabel: { color: "#7c2d12", fontSize: 15, fontWeight: 800 },
  eotMeta: { color: "#9a3412", fontSize: 13, fontWeight: 700 },
  eotReasons: { display: "flex", flexWrap: "wrap", gap: 8, minWidth: 0 },
  eotReasonPill: {
    background: "#ffedd5", border: "1px solid #fdba74", color: "#7c2d12",
    borderRadius: 999, padding: "5px 10px", fontSize: 12, fontWeight: 800,
  },
  eotEmpty: { color: "#9a3412", fontSize: 13, fontWeight: 700 },
  eotRecent: {
    gridColumn: "1 / -1", color: "#9a3412",
    fontSize: 13, fontWeight: 700, borderTop: "1px solid #fed7aa", paddingTop: 8,
  },
  // Focus footer
  focusFooter: {
    position: "fixed", bottom: 0, left: 0, right: 0,
    background: "white", borderTop: "2px solid #e2e8f0",
    padding: "12px 28px", display: "flex", alignItems: "center", gap: 12,
    fontSize: 16, zIndex: 50, boxShadow: "0 -4px 16px rgba(0,0,0,0.1)",
  },
  footerBtn: {
    background: "#7c3aed", color: "#fff", border: "none", borderRadius: 8,
    padding: "8px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer",
    whiteSpace: "nowrap",
  },
  modeToggle: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  modeBtn: {
    border: "1px solid #cbd5e1", background: "#f8fafc", color: "#334155",
    borderRadius: 8, padding: "9px 10px", fontSize: 13, fontWeight: 800,
    cursor: "pointer", textAlign: "center",
  },
  modeBtnActive: {
    borderColor: "#7c3aed", background: "#ede9fe", color: "#4c1d95",
    boxShadow: "0 0 0 2px rgba(124,58,237,0.12)",
  },
  openFullBtn: {
    marginLeft: "auto", background: "#7c3aed", color: "white",
    borderRadius: 8, padding: "9px 22px", fontWeight: 700,
    fontSize: 16, textDecoration: "none", whiteSpace: "nowrap",
  },
  center: { textAlign: "center", padding: "60px 0", color: "#475569", fontSize: 16 },
  empty:  { textAlign: "center", padding: "80px 28px" },
  // Modal
  overlay:    { position: "fixed", inset: 0, background: "rgba(15,23,42,0.55)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000, padding: 20 },
  modal:      { background: "white", borderRadius: 16, padding: 28, width: "100%", maxWidth: 520, display: "flex", flexDirection: "column", gap: 14, boxShadow: "0 24px 64px rgba(0,0,0,0.18)" },
  modalTitle: { fontSize: 20, fontWeight: 700, color: "#0f172a", margin: 0 },
  fieldLabel: { display: "flex", flexDirection: "column", gap: 5, fontSize: 15, color: "#334155", fontWeight: 600 },
  fieldHint: { color: "#64748b", fontSize: 12, fontWeight: 700, lineHeight: 1.4 },
  input:      { background: "white", border: "1px solid #cbd5e1", borderRadius: 8, color: "#0f172a", fontSize: 16, padding: "10px 14px", outline: "none", width: "100%", boxSizing: "border-box" },
  cancelBtn:  { background: "white", color: "#475569", border: "1px solid #cbd5e1", borderRadius: 8, padding: "10px 20px", fontSize: 16, cursor: "pointer" },
  dangerBtn:  { background: "#fef2f2", color: "#b91c1c", border: "1px solid #fecaca", borderRadius: 8, padding: "8px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer" },
  insertFromEditBtn: {
    background: "#ede9fe", color: "#5b21b6", border: "1px solid #c4b5fd",
    borderRadius: 8, padding: "8px 14px", fontSize: 13, fontWeight: 800,
    cursor: "pointer", whiteSpace: "nowrap",
  },
  checkboxRow: { display: "flex", gap: 20, flexWrap: "wrap" },
  checkLabel: { display: "flex", alignItems: "center", gap: 8, fontSize: 15, color: "#334155", fontWeight: 600, cursor: "pointer" },
  modalActions: { display: "flex", gap: 10, justifyContent: "flex-end", marginTop: 4 },
  choiceBtn: { background: "#f8fafc", border: "1px solid #cbd5e1", color: "#334155", borderRadius: 8, padding: "9px 12px", fontSize: 14, fontWeight: 700, cursor: "pointer" },
  choiceBtnActive: { background: "#ede9fe", border: "1px solid #7c3aed", color: "#6d28d9" },
  plannerGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 14 },
  plannerSection: { display: "flex", flexDirection: "column", gap: 8 },
  plannerLabel: { color: "#0f172a", fontSize: 14, fontWeight: 900, textTransform: "uppercase", letterSpacing: "0.04em" },
  plannerSelectWrap: { display: "block" },
  plannerOptionGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 },
  plannerChoice: {
    border: "1px solid #cbd5e1", background: "#f8fafc", color: "#334155",
    borderRadius: 8, padding: "8px 10px", fontSize: 13, fontWeight: 800,
    cursor: "pointer", textAlign: "left",
  },
  plannerChoiceActive: { borderColor: "#0f766e", background: "#ccfbf1", color: "#115e59" },
  plannerStats: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 10 },
  plannerStatCard: {
    background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 8,
    padding: 12, display: "flex", flexDirection: "column", gap: 4,
  },
  plannerReviewGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  plannerReviewPanel: { border: "1px solid #e2e8f0", borderRadius: 8, padding: 12, background: "#fff" },
  plannerPanelTitle: { margin: "0 0 10px", color: "#0f172a", fontSize: 15, fontWeight: 900 },
  plannerPill: {
    display: "inline-flex", margin: "0 6px 6px 0", borderRadius: 999,
    background: "#ecfeff", border: "1px solid #a5f3fc", color: "#155e75",
    padding: "5px 9px", fontSize: 12, fontWeight: 800,
  },
  plannerEmpty: { color: "#64748b", fontSize: 13, fontWeight: 700 },
  plannerTradeList: { display: "flex", flexDirection: "column", gap: 6 },
  plannerTradeRow: {
    display: "flex", justifyContent: "space-between", gap: 10,
    borderBottom: "1px solid #e2e8f0", paddingBottom: 6,
    color: "#334155", fontSize: 13,
  },
  plannerGroupList: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 10, marginBottom: 12 },
  plannerGroupBlock: { background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 8, padding: 10 },
  plannerGroupTitle: { color: "#0f172a", fontSize: 13, fontWeight: 900, marginBottom: 6 },
  plannerGroupTasks: { display: "flex", flexDirection: "column", gap: 3, color: "#475569", fontSize: 12, fontWeight: 700 },
  plannerTableWrap: { overflow: "auto", border: "1px solid #e2e8f0", borderRadius: 8 },
  plannerTable: {
    width: "100%", borderCollapse: "collapse", fontSize: 12, color: "#334155",
  },
  miniBtn:    { background: "#e2e8f0", border: "1px solid #cbd5e1", borderRadius: 6, padding: "5px 12px", fontSize: 14, fontWeight: 600, cursor: "pointer", color: "#1e293b", whiteSpace: "nowrap" },
  legendRow:  { display: "flex", flexWrap: "wrap", gap: "8px 22px", padding: "14px 28px 18px", background: "white", borderTop: "2px solid #e2e8f0", margin: "0 0 80px" },
  legendItem: { display: "flex", alignItems: "center", gap: 8 },
  legendLabel: { fontSize: 14, color: "#334155", fontWeight: 600, whiteSpace: "nowrap" },
};


