export const ESTIMATE_WORKSHEET_SECTIONS = [
  {
    key: "projectBasics",
    label: "Project Basics",
    fields: [
      text("jobName", "Job Name", true),
      text("clientName", "Client"),
      text("siteAddress", "Site Address", true),
      select("projectType", "Project Type", ["Single Storey Home", "Double Storey Home", "Triple Storey Home", "Duplex", "Townhouses", "Renovation / Extension", "Commercial"], true),
      number("storeys", "Storeys"),
      number("totalLivingM2", "Total Living m2", true),
      number("groundFloorM2", "Ground Floor m2"),
      number("firstFloorM2", "First Floor m2"),
      number("secondFloorM2", "Second Floor m2"),
      number("garageM2", "Garage m2"),
      number("alfrescoM2", "Alfresco m2"),
      number("porchM2", "Porch m2"),
      number("balconyM2", "Balcony m2"),
    ],
  },
  {
    key: "siteworks",
    label: "Siteworks",
    fields: [
      select("siteSlope", "Site Slope", ["Flat Site", "Mild Slope", "Moderate Slope", "Steep Slope", "Heavy Cut & Fill"]),
      select("accessDifficulty", "Access Difficulty", ["Easy", "Moderate", "Restricted", "Difficult"]),
      number("cutFillM3", "Cut / Fill m3"),
      number("retainingWallLm", "Retaining Wall lm"),
      number("drivewayM2", "Driveway m2"),
      number("pathsM2", "Paths m2"),
      number("stormwaterPits", "Stormwater Pits"),
      number("agPipeLm", "Ag Pipe lm"),
      number("landscapingM2", "Landscaping m2"),
    ],
    allowanceCapable: true,
  },
  {
    key: "slabConcrete",
    label: "Slab & Concrete",
    fields: [
      select("slabType", "Slab Type", ["Waffle Pod", "Raft Slab", "Conventional Slab", "Suspended Slab", "Split Level Slab"]),
      number("slabAreaM2", "Slab Area m2", true),
      number("edgeBeamLm", "Edge Beam lm"),
      number("concreteM3", "Concrete m3"),
      number("reinforcementM2", "Reinforcement m2"),
      number("wafflePodsM2", "Waffle Pods m2"),
      number("pierCount", "Pier Count"),
      number("pierDepthM", "Pier Depth m"),
      number("suspendedSlabM2", "Suspended Slab m2"),
    ],
  },
  {
    key: "externalWalls",
    label: "External Walls",
    fields: [
      number("externalWallLm", "External Wall lm"),
      number("wallHeightM", "Wall Height m"),
      select("groundWallSystem", "Ground Wall System", ["Brick Veneer", "Blockwork", "Hebel", "Lightweight Cladding", "Rendered Cladding", "Mixed"]),
      select("upperWallSystem", "Upper Wall System", ["Brick Veneer", "Blockwork", "Hebel", "Lightweight Cladding", "Rendered Cladding", "Mixed"]),
      number("brickVeneerM2", "Brick Veneer m2"),
      number("blockworkM2", "Blockwork m2"),
      number("hebelM2", "Hebel m2"),
      number("lightweightCladdingM2", "Lightweight Cladding m2"),
      number("renderM2", "Render m2"),
    ],
  },
  {
    key: "internalWallsFraming",
    label: "Internal Walls & Framing",
    fields: [
      number("internalWallLm", "Internal Wall lm"),
      number("wallHeightM", "Wall Height m"),
      select("frameType", "Frame Type", ["Timber", "Steel", "Masonry", "Mixed"]),
      number("timberFrameLm", "Timber Frame lm"),
      number("steelFrameLm", "Steel Frame lm"),
      number("bracingPanels", "Bracing Panels"),
      checkbox("structuralSteelRequired", "Structural Steel Required"),
      number("structuralSteelTonnes", "Structural Steel tonnes"),
    ],
  },
  {
    key: "roof",
    label: "Roof",
    fields: [
      number("roofAreaM2", "Roof Area m2", true),
      number("roofPitchDegrees", "Roof Pitch"),
      select("roofType", "Roof Type", ["Colorbond", "Concrete Tile", "Terracotta Tile", "Flat Roof", "Skillion Roof"]),
      number("guttersLm", "Gutters lm"),
      number("fasciaLm", "Fascia lm"),
      number("downpipesCount", "Downpipes"),
      number("insulationM2", "Insulation m2"),
      number("sarkingM2", "Sarking m2"),
    ],
  },
  {
    key: "doorsWindows",
    label: "Doors & Windows",
    fields: [
      text("entryDoorType", "Entry Door Type"),
      text("entryDoorSize", "Entry Door Size"),
      number("internalDoorCount", "Internal Doors"),
      number("cavitySliderCount", "Cavity Sliders"),
      text("garageDoorType", "Garage Door Type"),
      text("garageDoorSize", "Garage Door Size"),
      number("windowCount", "Window Count"),
      number("slidingDoorCount", "Sliding Doors"),
      number("stackerDoorCount", "Stacker Doors"),
      number("securityScreenCount", "Security Screens"),
    ],
  },
  {
    key: "kitchenAppliances",
    label: "Kitchen & Appliances",
    fields: [
      text("oven", "Oven"),
      text("cooktop", "Cooktop"),
      text("rangehood", "Rangehood"),
      text("dishwasher", "Dishwasher"),
      checkbox("microwaveProvision", "Microwave Provision"),
      checkbox("fridgeTap", "Fridge Tap"),
      number("cabinetryLm", "Cabinetry lm"),
      select("benchtopType", "Benchtop Type", ["Stone", "Laminate", "Timber", "Stainless", "Allowance"]),
      number("benchtopM2", "Benchtop m2"),
    ],
    allowanceCapable: true,
  },
  {
    key: "bathroomsPlumbing",
    label: "Bathrooms & Plumbing",
    fields: [
      number("vanities", "Vanities"),
      number("basins", "Basins"),
      number("toilets", "Toilets"),
      number("showers", "Showers"),
      number("baths", "Baths"),
      number("tapwareSets", "Tapware Sets"),
      number("towelRails", "Towel Rails"),
      number("mirrors", "Mirrors"),
      number("accessories", "Accessories"),
      text("hotWaterSystem", "Hot Water System"),
    ],
    allowanceCapable: true,
  },
  {
    key: "electrical",
    label: "Electrical",
    fields: [
      number("powerPoints", "Power Points"),
      number("lights", "Lights"),
      number("downlights", "Downlights"),
      number("fans", "Fans"),
      number("switches", "Switches"),
      number("smokeAlarms", "Smoke Alarms"),
      number("dataPoints", "Data Points"),
      number("tvPoints", "TV Points"),
      number("solarKw", "Solar kW"),
      number("batteryKwh", "Battery kWh"),
      checkbox("evCharger", "EV Charger"),
    ],
    allowanceCapable: true,
  },
  {
    key: "liningsFinishes",
    label: "Linings & Finishes",
    fields: [
      number("plasterboardWallM2", "Plasterboard Wall m2"),
      number("ceilingM2", "Ceiling m2"),
      number("corniceLm", "Cornice lm"),
      number("skirtingLm", "Skirting lm"),
      number("architravesLm", "Architraves lm"),
      number("internalPaintM2", "Internal Paint m2"),
      number("externalPaintM2", "External Paint m2"),
    ],
  },
  {
    key: "flooringTiling",
    label: "Flooring & Tiling",
    fields: [
      number("carpetM2", "Carpet m2"),
      number("vinylHybridM2", "Vinyl / Hybrid m2"),
      number("timberFlooringM2", "Timber Flooring m2"),
      number("tileFloorM2", "Tile Floor m2"),
      number("wallTileM2", "Wall Tile m2"),
      number("waterproofingM2", "Waterproofing m2"),
    ],
  },
  {
    key: "joineryFitout",
    label: "Joinery & Fitout",
    fields: [
      number("wardrobes", "Wardrobes"),
      number("linenCupboards", "Linen Cupboards"),
      number("laundryCabinetryLm", "Laundry Cabinetry lm"),
      number("robeShelvingLm", "Robe Shelving lm"),
      number("shelvingLm", "Shelving lm"),
      number("storageUnits", "Storage Units"),
    ],
    allowanceCapable: true,
  },
  {
    key: "externalWorks",
    label: "External Works",
    fields: [
      number("decksM2", "Decks m2"),
      number("patiosM2", "Patios m2"),
      number("fencingLm", "Fencing lm"),
      number("turfM2", "Turf m2"),
      number("gardenBedsM2", "Garden Beds m2"),
      number("retainingLm", "Retaining lm"),
      checkbox("poolIncluded", "Pool Included"),
      number("shedM2", "Shed m2"),
    ],
    allowanceCapable: true,
  },
  {
    key: "allowancesSelections",
    label: "Allowances & Selections",
    fields: [
      number("pcItemCount", "PC Item Count"),
      number("provisionalSumCount", "Provisional Sum Count"),
      number("clientSelectionCount", "Client Selections"),
      text("supplierAllowances", "Supplier Allowances"),
      text("upgradeOptions", "Upgrade Options"),
    ],
    allowanceCapable: true,
  },
];

export const REQUIRED_ESTIMATE_FIELDS = [
  ["projectBasics", "jobName"],
  ["projectBasics", "siteAddress"],
  ["projectBasics", "projectType"],
  ["projectBasics", "totalLivingM2"],
  ["slabConcrete", "slabAreaM2"],
  ["roof", "roofAreaM2"],
];

function text(key, label, required = false) { return { key, label, type: "text", required }; }
function number(key, label, required = false) { return { key, label, type: "number", required }; }
function checkbox(key, label) { return { key, label, type: "checkbox" }; }
function select(key, label, options, required = false) { return { key, label, type: "select", options, required }; }
