// Generated by scripts/measure-door-image-subjects.mjs - do not edit by hand.
// Door subject box (fractions of the image) inside wide studio door shots.
export const DOOR_IMAGE_SUBJECTS = {
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22053744/PRU-21_HR-Clear-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22051104/Blonde-Oak_AWO-2_042_wHandle_HR-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22051311/Blonde-Oak_AWO-21_050_CLEAR-GLASS_wHandle_HR-Clear-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22051115/Blonde-Oak_AWO-2G_039_CLEAR-GLASS_wHandle_HR-Clear-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22051137/Blonde-Oak_AWO-5_029_wHandle_HR-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2026/07/14114435/EXADECO-1S-Angled-4K-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2026/07/14115022/EXADECO-WS-4S-Angled-4K-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6346,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2025/09/12100445/Flush-Standard-Entrance-Angled-1-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.005,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22053957/PSLM-201_HR-Clear-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22053925/PSC-4_HR-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.005,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/27052212/SUN-GRAND_HR-Left-Angled-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22054158/PURB-01_HR-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  },
  "https://cdn.corinthian.com.au/wp-content/uploads/2024/08/22054230/PURB-4_HR-Angled-4Kpx-1440x800.png": {
    "width": 1440,
    "height": 800,
    "x0": 0.3196,
    "x1": 0.6075,
    "y0": 0.0037,
    "y1": 1
  }
};
