// Blank product record and local-storage keys used by the Product Library page.

export const PRODUCT_LIBRARY_JOB_STORAGE_KEY = "gr8:product-library:job-file";
export const DEFAULT_JOB_FILE_NAME = "product-library-selections.gr8job";

export const EMPTY_PRODUCT = {
  product_code: "",
  product_name: "",
  supplier_name: "",
  brand: "",
  range: "",
  model: "",
  description: "",
  colour: "",
  finish: "",
  size: "",
  texture: "",
  primary_image: "",
  official_product_url: "",
  specification_url: "",
  supplier_url: "",
  width: "",
  height: "",
  depth: "",
  variant_name: "",
  gallery_images: "",
  rrp: "",
  builder_cost: "",
  client_price: "",
  currency: "AUD",
  gst_treatment: "GST inclusive",
  price_unit: "",
  price_status: "price_pending",
  price_source_url: "",
  price_verified_at: "",
  image_source_url: "",
  image_status: "missing",
  image_verified_at: "",
  region: "QLD",
  price_effective_date: "",
  discontinued: false,
  archived: false,
  active: true,
};
