// Maps a Supabase workspace product row onto the Product Library entity shape.
// Extracted from pages/modules/builders/product-library.js; logic unchanged.

import { paintMaterialCategory } from './paintCategoryCompatibility.js';

export function mapDbProductToEntity(product, categoryName = "", supplierName = "", brandName = "") {
  const entity = product.metadata?.productEntity || {};
  return {
    productId: product.id,
    workspace_id: product.workspace_id,
    globalProductId: product.global_product_id || null,
    selectionSlotIds: product.selection_slot_ids || [],
    unit: product.unit || '',
    supplierId: product.supplier_id || null,
    supplierSku: product.sku || '',
    productCode: product.sku || entity.productCode || "",
    organisationId: product.workspace_id || "",
    linkedQuoteItemCode: product.quote_structure_row_id || entity.linkedQuoteItemCode || "",
    approvedSourceKey: entity.approvedSourceKey || product.metadata?.approvedSourceKey || "",
    familyKey: entity.familyKey || product.metadata?.familyKey || "",
    topLevelArea: entity.topLevelArea || product.metadata?.topLevelArea || "",
    category: paintMaterialCategory((product.metadata?.builderCsvKey && entity.category) || categoryName || entity.category || product.quote_structure_section || ""),
    subcategory: entity.subcategory || product.selection_type || "",
    productType: entity.productType || product.selection_type || "",
    tags: entity.tags || [],
    compatibleAreaTypes: entity.compatibleAreaTypes || [],
    productName: product.product_name,
    supplier: supplierName || entity.supplier || "",
    brand: brandName || entity.brand || "",
    range: entity.range || product.metadata?.range || "",
    model: product.model || "",
    description: product.description || "",
    colour: entity.colour || product.metadata?.colour || "",
    finish: entity.finish || product.metadata?.finish || "",
    size: entity.size || product.metadata?.size || "",
    width: entity.width || entity.dimensions?.width || "",
    height: entity.height || entity.dimensions?.height || "",
    depth: entity.depth || entity.dimensions?.depth || "",
    dimensions: entity.dimensions || {},
    variants: entity.variants || [],
      primaryImage: product.primary_image_url || entity.primaryImage || "",
    thumbnail: product.primary_image_url || entity.thumbnail || "",
    galleryImages: entity.galleryImages || [],
    colourSwatches: entity.colourSwatches || [],
    imageAltText: entity.imageAltText || product.product_name,
    imageSource: entity.imageSource || "",
    officialProductURL: product.product_url || entity.officialProductURL || "",
    specificationURL: product.datasheet_pdf_url || entity.specificationURL || "",
      supplierURL: product.supplier_website_url || entity.supplierURL || "",
    RRP: entity.RRP || 0,
    builderCost: entity.builderCost || Number(product.base_allowance || 0),
    clientPrice: entity.clientPrice || Number(product.upgrade_cost || 0),
    allowance: Number(product.base_allowance || 0),
    upgradePrice: Number(product.upgrade_cost || 0),
    currency: entity.currency || "AUD",
    gstTreatment: entity.gstTreatment || "GST inclusive",
    priceSource: entity.priceSource || "workspace product",
    priceEffectiveDate: entity.priceEffectiveDate || entity.effectiveDate || "",
    effectiveDate: entity.priceEffectiveDate || entity.effectiveDate || "",
    priceStatus: entity.priceStatus || "workspace",
    active: product.active !== false,
    discontinued: entity.discontinued || false,
    archived: product.active === false,
    unavailable: entity.unavailable || false,
    imageReviewRequired: !product.primary_image_url,
    priceReviewRequired: !product.base_allowance && !product.upgrade_cost,
    raw: product,
  };
}

