import React from "react";
import {
  FaBullhorn, FaBullseye, FaCalendarAlt, FaCamera, FaChartLine, FaCheckCircle,
  FaCog, FaComments, FaEnvelope, FaGlobe, FaHdd, FaHeart, FaMapMarkerAlt,
  FaPaintBrush, FaPhone, FaSearch, FaShoppingCart, FaStar, FaUser, FaVideo,
  FaRocket, FaLightbulb, FaFire, FaThumbsUp, FaHandshake, FaGraduationCap,
  FaBoxOpen, FaMobileAlt, FaLaptop, FaDesktop, FaWifi, FaLock, FaShieldAlt,
  FaKey, FaDatabase, FaCloud, FaServer, FaCode, FaBug, FaTools, FaWrench,
  FaMicrophone, FaHeadphones, FaBell, FaBookmark, FaTag, FaTags, FaClipboard,
  FaChartBar, FaChartPie, FaTable, FaList, FaThList, FaFilter, FaSort,
  FaHome, FaBuilding, FaStore, FaWarehouse, FaFlag, FaTrophy, FaMedal,
  FaGift, FaMoneyBillWave, FaDollarSign, FaCreditCard, FaReceipt, FaPercent,
  FaUsers, FaUserTie, FaUserFriends, FaUserCheck, FaUserPlus, FaUserCog,
  FaRegClock, FaRegCalendar, FaRegCalendarAlt, FaRegEnvelope, FaRegBell,
  FaArrowRight, FaArrowLeft, FaArrowUp, FaArrowDown, FaExternalLinkAlt,
  FaLink, FaShareAlt, FaPaperPlane, FaReply, FaForward, FaDownload, FaUpload,
  FaFilePdf, FaFileImage, FaFileAlt, FaFile, FaFolder, FaFolderOpen,
  FaTrash, FaTrashAlt, FaEdit, FaPencilAlt, FaSave, FaPlus, FaMinus, FaTimes,
  FaInfoCircle, FaExclamationCircle, FaExclamationTriangle, FaQuestion,
  FaEye, FaEyeSlash, FaThumbsDown, FaHandPointRight, FaHandPointUp,
  FaSun, FaMoon, FaSnowflake, FaBolt, FaLeaf, FaTree, FaMountain, FaWater,
  FaRobot, FaBrain, FaMagic, FaSatelliteDish, FaMicroscope, FaFlask,
  FaGem, FaCrown, FaAward, FaCertificate, FaStamp, FaBadge,
  FaIndustry, FaHospital, FaSchool, FaUniversity, FaChurch,
  FaCar, FaBus, FaTruck, FaPlane, FaShip, FaMotorcycle,
  FaMapMarked, FaMap, FaCompass, FaRoute, FaDirections,
  FaPalette, FaBrush, FaSwatchbook, FaImage, FaImages, FaCrop,
  FaHeartbeat, FaDumbbell, FaRunning, FaSwimmer, FaBicycle,
  FaUtensils, FaCoffee, FaBeer, FaWineGlass, FaPizzaSlice,
  FaMusic, FaGuitar, FaDrum, FaHeadphonesAlt,
  FaGamepad, FaDice, FaPuzzlePiece, FaChess,
  FaMicrosoft,
} from "react-icons/fa";
import {
  MdAnalytics, MdAutoAwesome, MdBusiness, MdCampaign, MdContactPage,
  MdDashboard, MdEmail, MdGroups, MdInsights, MdIntegrationInstructions,
  MdNotifications, MdPayment, MdPeople, MdSchedule, MdSecurity,
  MdSmartphone, MdSpeed, MdSupport, MdTrendingUp, MdAccountTree, MdViewKanban,
  MdFormatQuote, MdArticle, MdWeb, MdOutlineStorefront, MdOutlineLocalOffer,
  MdOutlinePrecisionManufacturing, MdOutlineRocketLaunch, MdOutlineVerified,
  MdOutlineAutoFixHigh,
} from "react-icons/md";
import {
  Activity, AlertCircle, AlignLeft, Archive, Award,
  BarChart2, BarChart, Battery, Bell, BellRing, Bookmark,
  Box, Briefcase, Building, Building2, Calendar, CalendarCheck,
  Camera, Check, CheckCircle2, ChevronRight, Clock, Cloud,
  CloudLightning, Code2, Cog, Compass, CreditCard, Database,
  Download, Edit2, Edit3, ExternalLink, Eye, File, FileText,
  Filter, Flag, Flame, Folder, FolderOpen, Gift, Globe2, Globe,
  Grid, Hammer, Hash, Heart, HelpCircle, Home, Image, Inbox,
  Info, Key, Layers, Layout, LifeBuoy, Link, List, Lock,
  LogIn, LogOut, Mail, Map, MapPin, Maximize, Menu, MessageCircle,
  MessageSquare, Mic, MicOff, Minimize, Minus, Monitor, Moon,
  MoreHorizontal, MoreVertical, Music, Navigation, Package,
  Percent, Phone, PhoneCall, PhoneIncoming, Play, Plus,
  Power, Printer, RefreshCcw, RefreshCw, Search, Send, Server,
  Settings, Share2, ShieldCheck, ShieldOff, ShoppingBag, ShoppingCart,
  Sliders, Smartphone, Speaker, Star, Sun, Tag, Target, Terminal,
  ThumbsUp, ToggleLeft, ToggleRight, Trash2, TrendingDown, TrendingUp,
  Trophy, Tv, Umbrella, Upload, User, UserCheck, UserMinus, UserPlus,
  Users, Video, Voicemail, Volume2, Wifi, Wind, Wrench, Zap,
  ZoomIn, ZoomOut, Book, BookOpen, Cpu, DollarSign, Feather,
  Github, Gitlab, Globe2 as Globe2b, Headphones, Layers as Layers2,
  LayoutDashboard, LineChart, Lightbulb, Lock as Lock2, Megaphone,
  PenTool, Rss, Save, Shield, Scissors, Square, Triangle, Circle,
  Hexagon, Octagon, ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  CornerDownRight, Move, Repeat, Shuffle, SkipForward,
} from "lucide-react";
import {
  SiTiktok, SiX, SiSlack, SiNotion, SiZapier, SiHubspot,
  SiMailchimp, SiShopify, SiWordpress, SiWix, SiWebflow,
  SiStripe, SiPaypal, SiGoogleanalytics, SiGoogle,
  SiGooglemeet, SiZoom, SiAmazon, SiNetflix,
  SiSpotify, SiDropbox, SiTrello, SiAsana, SiJira, SiClickup,
  SiAirtable, SiGoogleads,
} from "react-icons/si";
import {
  FiBarChart2, FiCalendar, FiCamera, FiCheckCircle, FiCode, FiFeather,
  FiFlag, FiGlobe, FiHeart, FiLayout, FiLifeBuoy, FiMail, FiMapPin,
  FiMessageSquare, FiMonitor, FiPenTool, FiPhone, FiSearch, FiShoppingBag,
  FiStar, FiUser, FiVideo, FiZap,
} from "react-icons/fi";
import {
  BsCalendar2Event, BsCamera, BsCameraVideo, BsCart3, BsChatSquareText,
  BsCheckCircle, BsGear, BsGeoAlt, BsGlobe, BsGraphUpArrow, BsMegaphone,
  BsPalette, BsPerson, BsSearch, BsShieldCheck, BsStars, BsTelephone,
} from "react-icons/bs";

// ─── FontAwesome ──────────────────────────────────────────────────────────────
const FA_ICONS = [
  // Marketing
  { key: "social",        label: "Bullhorn",      group: "Marketing",    Icon: FaBullhorn },
  { key: "marketing",     label: "Target",        group: "Marketing",    Icon: FaBullseye },
  { key: "seo",           label: "Search",        group: "Marketing",    Icon: FaSearch },
  { key: "rocket",        label: "Rocket",        group: "Marketing",    Icon: FaRocket },
  { key: "lightbulb",     label: "Lightbulb",     group: "Marketing",    Icon: FaLightbulb },
  { key: "fire",          label: "Fire",          group: "Marketing",    Icon: FaFire },
  { key: "magic",         label: "Magic",         group: "Marketing",    Icon: FaMagic },
  { key: "percent",       label: "Percent",       group: "Marketing",    Icon: FaPercent },
  { key: "tag",           label: "Tag",           group: "Marketing",    Icon: FaTag },
  { key: "tags",          label: "Tags",          group: "Marketing",    Icon: FaTags },
  { key: "gift",          label: "Gift",          group: "Marketing",    Icon: FaGift },
  { key: "trophy",        label: "Trophy",        group: "Marketing",    Icon: FaTrophy },
  { key: "medal",         label: "Medal",         group: "Marketing",    Icon: FaMedal },
  { key: "award",         label: "Award",         group: "Marketing",    Icon: FaAward },
  { key: "certificate",   label: "Certificate",   group: "Marketing",    Icon: FaCertificate },
  { key: "crown",         label: "Crown",         group: "Marketing",    Icon: FaCrown },
  { key: "gem",           label: "Gem",           group: "Marketing",    Icon: FaGem },
  // Communication
  { key: "email",         label: "Email",         group: "Communication", Icon: FaEnvelope },
  { key: "phone",         label: "Phone",         group: "Communication", Icon: FaPhone },
  { key: "chat",          label: "Chat",          group: "Communication", Icon: FaComments },
  { key: "paper-plane",   label: "Send",          group: "Communication", Icon: FaPaperPlane },
  { key: "reply",         label: "Reply",         group: "Communication", Icon: FaReply },
  { key: "mobile",        label: "Mobile",        group: "Communication", Icon: FaMobileAlt },
  { key: "microphone",    label: "Microphone",    group: "Communication", Icon: FaMicrophone },
  { key: "headphones",    label: "Headphones",    group: "Communication", Icon: FaHeadphones },
  { key: "bell",          label: "Bell",          group: "Communication", Icon: FaBell },
  { key: "bookmark",      label: "Bookmark",      group: "Communication", Icon: FaBookmark },
  { key: "share",         label: "Share",         group: "Communication", Icon: FaShareAlt },
  { key: "link",          label: "Link",          group: "Communication", Icon: FaLink },
  // Technology
  { key: "software",      label: "Server",        group: "Technology",   Icon: FaHdd },
  { key: "web",           label: "Globe",         group: "Technology",   Icon: FaGlobe },
  { key: "laptop",        label: "Laptop",        group: "Technology",   Icon: FaLaptop },
  { key: "desktop",       label: "Desktop",       group: "Technology",   Icon: FaDesktop },
  { key: "wifi",          label: "Wi-Fi",         group: "Technology",   Icon: FaWifi },
  { key: "cloud",         label: "Cloud",         group: "Technology",   Icon: FaCloud },
  { key: "database",      label: "Database",      group: "Technology",   Icon: FaDatabase },
  { key: "server",        label: "Server",        group: "Technology",   Icon: FaServer },
  { key: "code",          label: "Code",          group: "Technology",   Icon: FaCode },
  { key: "robot",         label: "Robot",         group: "Technology",   Icon: FaRobot },
  { key: "brain",         label: "Brain (AI)",    group: "Technology",   Icon: FaBrain },
  { key: "satellite",     label: "Satellite",     group: "Technology",   Icon: FaSatelliteDish },
  { key: "lock",          label: "Lock",          group: "Technology",   Icon: FaLock },
  { key: "shield",        label: "Shield",        group: "Technology",   Icon: FaShieldAlt },
  { key: "key",           label: "Key",           group: "Technology",   Icon: FaKey },
  { key: "wrench",        label: "Wrench",        group: "Technology",   Icon: FaWrench },
  { key: "tools",         label: "Tools",         group: "Technology",   Icon: FaTools },
  { key: "bug",           label: "Bug",           group: "Technology",   Icon: FaBug },
  // Business
  { key: "calendar",      label: "Calendar",      group: "Business",     Icon: FaCalendarAlt },
  { key: "analytics",     label: "Analytics",     group: "Business",     Icon: FaChartLine },
  { key: "chart-bar",     label: "Bar Chart",     group: "Business",     Icon: FaChartBar },
  { key: "chart-pie",     label: "Pie Chart",     group: "Business",     Icon: FaChartPie },
  { key: "settings",      label: "Settings",      group: "Business",     Icon: FaCog },
  { key: "clipboard",     label: "Clipboard",     group: "Business",     Icon: FaClipboard },
  { key: "table",         label: "Table",         group: "Business",     Icon: FaTable },
  { key: "list",          label: "List",          group: "Business",     Icon: FaList },
  { key: "filter",        label: "Filter",        group: "Business",     Icon: FaFilter },
  { key: "location",      label: "Location",      group: "Business",     Icon: FaMapMarkerAlt },
  { key: "map",           label: "Map",           group: "Business",     Icon: FaMapMarked },
  { key: "compass",       label: "Compass",       group: "Business",     Icon: FaCompass },
  { key: "building",      label: "Building",      group: "Business",     Icon: FaBuilding },
  { key: "industry",      label: "Industry",      group: "Business",     Icon: FaIndustry },
  { key: "flag",          label: "Flag",          group: "Business",     Icon: FaFlag },
  { key: "folder",        label: "Folder",        group: "Business",     Icon: FaFolder },
  { key: "file",          label: "File",          group: "Business",     Icon: FaFile },
  { key: "file-pdf",      label: "PDF",           group: "Business",     Icon: FaFilePdf },
  { key: "download",      label: "Download",      group: "Business",     Icon: FaDownload },
  { key: "upload",        label: "Upload",        group: "Business",     Icon: FaUpload },
  // Commerce
  { key: "store",         label: "Store",         group: "Commerce",     Icon: FaStore },
  { key: "shop-cart",     label: "Cart",          group: "Commerce",     Icon: FaShoppingCart },
  { key: "money",         label: "Money",         group: "Commerce",     Icon: FaMoneyBillWave },
  { key: "dollar",        label: "Dollar",        group: "Commerce",     Icon: FaDollarSign },
  { key: "credit-card",   label: "Credit Card",   group: "Commerce",     Icon: FaCreditCard },
  { key: "receipt",       label: "Receipt",       group: "Commerce",     Icon: FaReceipt },
  { key: "box",           label: "Box",           group: "Commerce",     Icon: FaBoxOpen },
  { key: "warehouse",     label: "Warehouse",     group: "Commerce",     Icon: FaWarehouse },
  // People
  { key: "user",          label: "User",          group: "People",       Icon: FaUser },
  { key: "user-tie",      label: "User (Tie)",    group: "People",       Icon: FaUserTie },
  { key: "users",         label: "Users",         group: "People",       Icon: FaUsers },
  { key: "user-friends",  label: "Friends",       group: "People",       Icon: FaUserFriends },
  { key: "user-check",    label: "User Check",    group: "People",       Icon: FaUserCheck },
  { key: "user-plus",     label: "Add User",      group: "People",       Icon: FaUserPlus },
  { key: "user-cog",      label: "User Settings", group: "People",       Icon: FaUserCog },
  { key: "handshake",     label: "Handshake",     group: "People",       Icon: FaHandshake },
  { key: "thumbs-up",     label: "Thumbs Up",     group: "People",       Icon: FaThumbsUp },
  { key: "thumbs-down",   label: "Thumbs Down",   group: "People",       Icon: FaThumbsDown },
  // Education / Skills
  { key: "graduation",    label: "Graduation",    group: "Education",    Icon: FaGraduationCap },
  { key: "university",    label: "University",    group: "Education",    Icon: FaUniversity },
  { key: "school",        label: "School",        group: "Education",    Icon: FaSchool },
  { key: "microscope",    label: "Microscope",    group: "Education",    Icon: FaMicroscope },
  { key: "flask",         label: "Flask",         group: "Education",    Icon: FaFlask },
  // Media
  { key: "video",         label: "Video",         group: "Media",        Icon: FaVideo },
  { key: "camera",        label: "Camera",        group: "Media",        Icon: FaCamera },
  { key: "image",         label: "Image",         group: "Media",        Icon: FaImage },
  { key: "images",        label: "Images",        group: "Media",        Icon: FaImages },
  { key: "music",         label: "Music",         group: "Media",        Icon: FaMusic },
  { key: "headphones-alt", label: "Headphones",   group: "Media",        Icon: FaHeadphonesAlt },
  // Creative
  { key: "design",        label: "Paint Brush",   group: "Creative",     Icon: FaPaintBrush },
  { key: "palette",       label: "Palette",       group: "Creative",     Icon: FaPalette },
  { key: "brush",         label: "Brush",         group: "Creative",     Icon: FaBrush },
  { key: "swatchbook",    label: "Swatch",        group: "Creative",     Icon: FaSwatchbook },
  { key: "crop",          label: "Crop",          group: "Creative",     Icon: FaCrop },
  { key: "edit",          label: "Edit",          group: "Creative",     Icon: FaEdit },
  { key: "pencil",        label: "Pencil",        group: "Creative",     Icon: FaPencilAlt },
  // UI
  { key: "favorite",      label: "Heart",         group: "UI",           Icon: FaHeart },
  { key: "star",          label: "Star",          group: "UI",           Icon: FaStar },
  { key: "check",         label: "Check",         group: "UI",           Icon: FaCheckCircle },
  { key: "info",          label: "Info",          group: "UI",           Icon: FaInfoCircle },
  { key: "warning",       label: "Warning",       group: "UI",           Icon: FaExclamationTriangle },
  { key: "error",         label: "Error",         group: "UI",           Icon: FaExclamationCircle },
  { key: "home",          label: "Home",          group: "UI",           Icon: FaHome },
  { key: "arrow-right",   label: "Arrow Right",   group: "UI",           Icon: FaArrowRight },
  { key: "arrow-left",    label: "Arrow Left",    group: "UI",           Icon: FaArrowLeft },
  { key: "arrow-up",      label: "Arrow Up",      group: "UI",           Icon: FaArrowUp },
  { key: "arrow-down",    label: "Arrow Down",    group: "UI",           Icon: FaArrowDown },
  { key: "external-link", label: "External Link", group: "UI",           Icon: FaExternalLinkAlt },
  { key: "eye",           label: "Eye",           group: "UI",           Icon: FaEye },
  { key: "sun",           label: "Sun",           group: "UI",           Icon: FaSun },
  { key: "moon",          label: "Moon",          group: "UI",           Icon: FaMoon },
  { key: "bolt",          label: "Bolt",          group: "UI",           Icon: FaBolt },
  { key: "leaf",          label: "Leaf",          group: "UI",           Icon: FaLeaf },
  // Transport
  { key: "car",           label: "Car",           group: "Transport",    Icon: FaCar },
  { key: "truck",         label: "Truck",         group: "Transport",    Icon: FaTruck },
  { key: "plane",         label: "Plane",         group: "Transport",    Icon: FaPlane },
  { key: "ship",          label: "Ship",          group: "Transport",    Icon: FaShip },
  // Health & Fitness
  { key: "heartbeat",     label: "Heartbeat",     group: "Health",       Icon: FaHeartbeat },
  { key: "dumbbell",      label: "Dumbbell",      group: "Health",       Icon: FaDumbbell },
  { key: "running",       label: "Running",       group: "Health",       Icon: FaRunning },
  { key: "hospital",      label: "Hospital",      group: "Health",       Icon: FaHospital },
  // Food & Lifestyle
  { key: "coffee",        label: "Coffee",        group: "Lifestyle",    Icon: FaCoffee },
  { key: "utensils",      label: "Utensils",      group: "Lifestyle",    Icon: FaUtensils },
  { key: "pizza",         label: "Pizza",         group: "Lifestyle",    Icon: FaPizzaSlice },
  // Games
  { key: "gamepad",       label: "Gamepad",       group: "Leisure",      Icon: FaGamepad },
  { key: "chess",         label: "Chess",         group: "Leisure",      Icon: FaChess },
  { key: "puzzle",        label: "Puzzle",        group: "Leisure",      Icon: FaPuzzlePiece },
  { key: "dice",          label: "Dice",          group: "Leisure",      Icon: FaDice },
];

// ─── Lucide ───────────────────────────────────────────────────────────────────
const LUCIDE_ICONS = [
  { key: "lc-dashboard",     label: "Dashboard",       group: "Lucide",   Icon: LayoutDashboard },
  { key: "lc-activity",      label: "Activity",        group: "Lucide",   Icon: Activity },
  { key: "lc-alert",         label: "Alert",           group: "Lucide",   Icon: AlertCircle },
  { key: "lc-archive",       label: "Archive",         group: "Lucide",   Icon: Archive },
  { key: "lc-award",         label: "Award",           group: "Lucide",   Icon: Award },
  { key: "lc-barchart",      label: "Bar Chart",       group: "Lucide",   Icon: BarChart2 },
  { key: "lc-battery",       label: "Battery",         group: "Lucide",   Icon: Battery },
  { key: "lc-bell",          label: "Bell",            group: "Lucide",   Icon: Bell },
  { key: "lc-bell-ring",     label: "Bell Ring",       group: "Lucide",   Icon: BellRing },
  { key: "lc-bookmark",      label: "Bookmark",        group: "Lucide",   Icon: Bookmark },
  { key: "lc-box",           label: "Box",             group: "Lucide",   Icon: Box },
  { key: "lc-briefcase",     label: "Briefcase",       group: "Lucide",   Icon: Briefcase },
  { key: "lc-building",      label: "Building",        group: "Lucide",   Icon: Building2 },
  { key: "lc-calendar",      label: "Calendar",        group: "Lucide",   Icon: Calendar },
  { key: "lc-calendar-chk",  label: "Cal. Check",      group: "Lucide",   Icon: CalendarCheck },
  { key: "lc-camera",        label: "Camera",          group: "Lucide",   Icon: Camera },
  { key: "lc-check",         label: "Check",           group: "Lucide",   Icon: CheckCircle2 },
  { key: "lc-clock",         label: "Clock",           group: "Lucide",   Icon: Clock },
  { key: "lc-cloud",         label: "Cloud",           group: "Lucide",   Icon: Cloud },
  { key: "lc-cloud-zap",     label: "Cloud Zap",       group: "Lucide",   Icon: CloudLightning },
  { key: "lc-code",          label: "Code",            group: "Lucide",   Icon: Code2 },
  { key: "lc-cog",           label: "Settings",        group: "Lucide",   Icon: Cog },
  { key: "lc-compass",       label: "Compass",         group: "Lucide",   Icon: Compass },
  { key: "lc-credit",        label: "Credit Card",     group: "Lucide",   Icon: CreditCard },
  { key: "lc-database",      label: "Database",        group: "Lucide",   Icon: Database },
  { key: "lc-download",      label: "Download",        group: "Lucide",   Icon: Download },
  { key: "lc-edit",          label: "Edit",            group: "Lucide",   Icon: Edit3 },
  { key: "lc-eye",           label: "Eye",             group: "Lucide",   Icon: Eye },
  { key: "lc-file",          label: "File",            group: "Lucide",   Icon: FileText },
  { key: "lc-filter",        label: "Filter",          group: "Lucide",   Icon: Filter },
  { key: "lc-flag",          label: "Flag",            group: "Lucide",   Icon: Flag },
  { key: "lc-flame",         label: "Flame",           group: "Lucide",   Icon: Flame },
  { key: "lc-folder",        label: "Folder",          group: "Lucide",   Icon: FolderOpen },
  { key: "lc-gift",          label: "Gift",            group: "Lucide",   Icon: Gift },
  { key: "lc-globe",         label: "Globe",           group: "Lucide",   Icon: Globe },
  { key: "lc-grid",          label: "Grid",            group: "Lucide",   Icon: Grid },
  { key: "lc-hammer",        label: "Hammer",          group: "Lucide",   Icon: Hammer },
  { key: "lc-hash",          label: "Hash",            group: "Lucide",   Icon: Hash },
  { key: "lc-heart",         label: "Heart",           group: "Lucide",   Icon: Heart },
  { key: "lc-help",          label: "Help",            group: "Lucide",   Icon: HelpCircle },
  { key: "lc-home",          label: "Home",            group: "Lucide",   Icon: Home },
  { key: "lc-image",         label: "Image",           group: "Lucide",   Icon: Image },
  { key: "lc-inbox",         label: "Inbox",           group: "Lucide",   Icon: Inbox },
  { key: "lc-info",          label: "Info",            group: "Lucide",   Icon: Info },
  { key: "lc-key",           label: "Key",             group: "Lucide",   Icon: Key },
  { key: "lc-layers",        label: "Layers",          group: "Lucide",   Icon: Layers },
  { key: "lc-layout",        label: "Layout",          group: "Lucide",   Icon: Layout },
  { key: "lc-lifebuoy",      label: "Life Buoy",       group: "Lucide",   Icon: LifeBuoy },
  { key: "lc-link",          label: "Link",            group: "Lucide",   Icon: Link },
  { key: "lc-linechart",     label: "Line Chart",      group: "Lucide",   Icon: LineChart },
  { key: "lc-list",          label: "List",            group: "Lucide",   Icon: List },
  { key: "lc-lock",          label: "Lock",            group: "Lucide",   Icon: Lock },
  { key: "lc-mail",          label: "Mail",            group: "Lucide",   Icon: Mail },
  { key: "lc-map",           label: "Map",             group: "Lucide",   Icon: Map },
  { key: "lc-mappin",        label: "Map Pin",         group: "Lucide",   Icon: MapPin },
  { key: "lc-megaphone",     label: "Megaphone",       group: "Lucide",   Icon: Megaphone },
  { key: "lc-menu",          label: "Menu",            group: "Lucide",   Icon: Menu },
  { key: "lc-message",       label: "Message",         group: "Lucide",   Icon: MessageCircle },
  { key: "lc-messagesq",     label: "Message Box",     group: "Lucide",   Icon: MessageSquare },
  { key: "lc-mic",           label: "Microphone",      group: "Lucide",   Icon: Mic },
  { key: "lc-monitor",       label: "Monitor",         group: "Lucide",   Icon: Monitor },
  { key: "lc-moon",          label: "Moon",            group: "Lucide",   Icon: Moon },
  { key: "lc-music",         label: "Music",           group: "Lucide",   Icon: Music },
  { key: "lc-navigation",    label: "Navigation",      group: "Lucide",   Icon: Navigation },
  { key: "lc-package",       label: "Package",         group: "Lucide",   Icon: Package },
  { key: "lc-percent",       label: "Percent",         group: "Lucide",   Icon: Percent },
  { key: "lc-phone",         label: "Phone",           group: "Lucide",   Icon: Phone },
  { key: "lc-phone-call",    label: "Phone Call",      group: "Lucide",   Icon: PhoneCall },
  { key: "lc-play",          label: "Play",            group: "Lucide",   Icon: Play },
  { key: "lc-power",         label: "Power",           group: "Lucide",   Icon: Power },
  { key: "lc-printer",       label: "Printer",         group: "Lucide",   Icon: Printer },
  { key: "lc-refresh",       label: "Refresh",         group: "Lucide",   Icon: RefreshCw },
  { key: "lc-search",        label: "Search",          group: "Lucide",   Icon: Search },
  { key: "lc-send",          label: "Send",            group: "Lucide",   Icon: Send },
  { key: "lc-server",        label: "Server",          group: "Lucide",   Icon: Server },
  { key: "lc-settings",      label: "Settings",        group: "Lucide",   Icon: Settings },
  { key: "lc-share",         label: "Share",           group: "Lucide",   Icon: Share2 },
  { key: "lc-shield",        label: "Shield",          group: "Lucide",   Icon: ShieldCheck },
  { key: "lc-shop-bag",      label: "Shopping Bag",    group: "Lucide",   Icon: ShoppingBag },
  { key: "lc-shop-cart",     label: "Cart",            group: "Lucide",   Icon: ShoppingCart },
  { key: "lc-sliders",       label: "Sliders",         group: "Lucide",   Icon: Sliders },
  { key: "lc-smartphone",    label: "Smartphone",      group: "Lucide",   Icon: Smartphone },
  { key: "lc-speaker",       label: "Speaker",         group: "Lucide",   Icon: Speaker },
  { key: "lc-star",          label: "Star",            group: "Lucide",   Icon: Star },
  { key: "lc-sun",           label: "Sun",             group: "Lucide",   Icon: Sun },
  { key: "lc-tag",           label: "Tag",             group: "Lucide",   Icon: Tag },
  { key: "lc-target",        label: "Target",          group: "Lucide",   Icon: Target },
  { key: "lc-terminal",      label: "Terminal",        group: "Lucide",   Icon: Terminal },
  { key: "lc-thumbsup",      label: "Thumbs Up",       group: "Lucide",   Icon: ThumbsUp },
  { key: "lc-trash",         label: "Trash",           group: "Lucide",   Icon: Trash2 },
  { key: "lc-trend-up",      label: "Trending Up",     group: "Lucide",   Icon: TrendingUp },
  { key: "lc-trend-dn",      label: "Trending Down",   group: "Lucide",   Icon: TrendingDown },
  { key: "lc-trophy",        label: "Trophy",          group: "Lucide",   Icon: Trophy },
  { key: "lc-tv",            label: "TV",              group: "Lucide",   Icon: Tv },
  { key: "lc-umbrella",      label: "Umbrella",        group: "Lucide",   Icon: Umbrella },
  { key: "lc-upload",        label: "Upload",          group: "Lucide",   Icon: Upload },
  { key: "lc-user",          label: "User",            group: "Lucide",   Icon: User },
  { key: "lc-user-chk",      label: "User Check",      group: "Lucide",   Icon: UserCheck },
  { key: "lc-user-plus",     label: "Add User",        group: "Lucide",   Icon: UserPlus },
  { key: "lc-users",         label: "Users",           group: "Lucide",   Icon: Users },
  { key: "lc-video",         label: "Video",           group: "Lucide",   Icon: Video },
  { key: "lc-voicemail",     label: "Voicemail",       group: "Lucide",   Icon: Voicemail },
  { key: "lc-volume",        label: "Volume",          group: "Lucide",   Icon: Volume2 },
  { key: "lc-wifi",          label: "Wifi",            group: "Lucide",   Icon: Wifi },
  { key: "lc-wind",          label: "Wind",            group: "Lucide",   Icon: Wind },
  { key: "lc-wrench",        label: "Wrench",          group: "Lucide",   Icon: Wrench },
  { key: "lc-zap",           label: "Zap",             group: "Lucide",   Icon: Zap },
  { key: "lc-book",          label: "Book",            group: "Lucide",   Icon: Book },
  { key: "lc-bookopen",      label: "Book Open",       group: "Lucide",   Icon: BookOpen },
  { key: "lc-cpu",           label: "CPU",             group: "Lucide",   Icon: Cpu },
  { key: "lc-dollar",        label: "Dollar",          group: "Lucide",   Icon: DollarSign },
  { key: "lc-headphones",    label: "Headphones",      group: "Lucide",   Icon: Headphones },
  { key: "lc-lightbulb",     label: "Lightbulb",       group: "Lucide",   Icon: Lightbulb },
  { key: "lc-pentool",       label: "Pen Tool",        group: "Lucide",   Icon: PenTool },
  { key: "lc-rss",           label: "RSS",             group: "Lucide",   Icon: Rss },
  { key: "lc-save",          label: "Save",            group: "Lucide",   Icon: Save },
  { key: "lc-scissors",      label: "Scissors",        group: "Lucide",   Icon: Scissors },
  { key: "lc-arrow-right",   label: "Arrow Right",     group: "Lucide",   Icon: ArrowRight },
  { key: "lc-arrow-left",    label: "Arrow Left",      group: "Lucide",   Icon: ArrowLeft },
  { key: "lc-arrow-up",      label: "Arrow Up",        group: "Lucide",   Icon: ArrowUp },
  { key: "lc-arrow-down",    label: "Arrow Down",      group: "Lucide",   Icon: ArrowDown },
  { key: "lc-move",          label: "Move",            group: "Lucide",   Icon: Move },
  { key: "lc-repeat",        label: "Repeat",          group: "Lucide",   Icon: Repeat },
  { key: "lc-skip",          label: "Skip",            group: "Lucide",   Icon: SkipForward },
];

// ─── Material Design ──────────────────────────────────────────────────────────
const MD_ICONS = [
  { key: "md-analytics",      label: "Analytics",       group: "Material", Icon: MdAnalytics },
  { key: "md-autoawesome",    label: "Auto Awesome",    group: "Material", Icon: MdAutoAwesome },
  { key: "md-business",       label: "Business",        group: "Material", Icon: MdBusiness },
  { key: "md-campaign",       label: "Campaign",        group: "Material", Icon: MdCampaign },
  { key: "md-contact",        label: "Contact Page",    group: "Material", Icon: MdContactPage },
  { key: "md-dashboard",      label: "Dashboard",       group: "Material", Icon: MdDashboard },
  { key: "md-email",          label: "Email",           group: "Material", Icon: MdEmail },
  { key: "md-groups",         label: "Groups",          group: "Material", Icon: MdGroups },
  { key: "md-insights",       label: "Insights",        group: "Material", Icon: MdInsights },
  { key: "md-integrations",   label: "Integrations",    group: "Material", Icon: MdIntegrationInstructions },
  { key: "md-notifications",  label: "Notifications",   group: "Material", Icon: MdNotifications },
  { key: "md-payment",        label: "Payment",         group: "Material", Icon: MdPayment },
  { key: "md-people",         label: "People",          group: "Material", Icon: MdPeople },
  { key: "md-schedule",       label: "Schedule",        group: "Material", Icon: MdSchedule },
  { key: "md-security",       label: "Security",        group: "Material", Icon: MdSecurity },
  { key: "md-smartphone",     label: "Smartphone",      group: "Material", Icon: MdSmartphone },
  { key: "md-speed",          label: "Speed",           group: "Material", Icon: MdSpeed },
  { key: "md-support",        label: "Support",         group: "Material", Icon: MdSupport },
  { key: "md-trending",       label: "Trending Up",     group: "Material", Icon: MdTrendingUp },
  { key: "md-workflow",       label: "Workflow",        group: "Material", Icon: MdAccountTree },
  { key: "md-quote",          label: "Quote",           group: "Material", Icon: MdFormatQuote },
  { key: "md-article",        label: "Article",         group: "Material", Icon: MdArticle },
  { key: "md-web",            label: "Web",             group: "Material", Icon: MdWeb },
  { key: "md-storefront",     label: "Storefront",      group: "Material", Icon: MdOutlineStorefront },
  { key: "md-offer",          label: "Local Offer",     group: "Material", Icon: MdOutlineLocalOffer },
  { key: "md-manufacturing",  label: "Manufacturing",   group: "Material", Icon: MdOutlinePrecisionManufacturing },
  { key: "md-rocket",         label: "Rocket Launch",   group: "Material", Icon: MdOutlineRocketLaunch },
  { key: "md-verified",       label: "Verified",        group: "Material", Icon: MdOutlineVerified },
  { key: "md-autofix",        label: "Auto Fix",        group: "Material", Icon: MdOutlineAutoFixHigh },
];

// ─── Simple Icons (brand logos) ───────────────────────────────────────────────
const SI_ICONS = [
  { key: "si-tiktok",      label: "TikTok",          group: "Brand Logos", Icon: SiTiktok },
  { key: "si-x",           label: "X",               group: "Brand Logos", Icon: SiX },
  { key: "si-slack",       label: "Slack",           group: "Brand Logos", Icon: SiSlack },
  { key: "si-notion",      label: "Notion",          group: "Brand Logos", Icon: SiNotion },
  { key: "si-zapier",      label: "Zapier",          group: "Brand Logos", Icon: SiZapier },
  { key: "si-hubspot",     label: "HubSpot",         group: "Brand Logos", Icon: SiHubspot },
  { key: "si-mailchimp",   label: "Mailchimp",       group: "Brand Logos", Icon: SiMailchimp },
  { key: "si-shopify",     label: "Shopify",         group: "Brand Logos", Icon: SiShopify },
  { key: "si-wordpress",   label: "WordPress",       group: "Brand Logos", Icon: SiWordpress },
  { key: "si-wix",         label: "Wix",             group: "Brand Logos", Icon: SiWix },
  { key: "si-webflow",     label: "Webflow",         group: "Brand Logos", Icon: SiWebflow },
  { key: "si-stripe",      label: "Stripe",          group: "Brand Logos", Icon: SiStripe },
  { key: "si-paypal",      label: "PayPal",          group: "Brand Logos", Icon: SiPaypal },
  { key: "si-ga",          label: "Google Analytics",group: "Brand Logos", Icon: SiGoogleanalytics },
  { key: "si-gmb",         label: "Google Business", group: "Brand Logos", Icon: SiGoogle },
  { key: "si-meet",        label: "Google Meet",     group: "Brand Logos", Icon: SiGooglemeet },
  { key: "si-zoom",        label: "Zoom",            group: "Brand Logos", Icon: SiZoom },
  { key: "si-ms",          label: "Microsoft",       group: "Brand Logos", Icon: FaMicrosoft },
  { key: "si-amazon",      label: "Amazon",          group: "Brand Logos", Icon: SiAmazon },
  { key: "si-spotify",     label: "Spotify",         group: "Brand Logos", Icon: SiSpotify },
  { key: "si-dropbox",     label: "Dropbox",         group: "Brand Logos", Icon: SiDropbox },
  { key: "si-trello",      label: "Trello",          group: "Brand Logos", Icon: SiTrello },
  { key: "si-asana",       label: "Asana",           group: "Brand Logos", Icon: SiAsana },
  { key: "si-jira",        label: "Jira",            group: "Brand Logos", Icon: SiJira },
  { key: "si-clickup",     label: "ClickUp",         group: "Brand Logos", Icon: SiClickup },
  { key: "si-airtable",    label: "Airtable",        group: "Brand Logos", Icon: SiAirtable },
  { key: "si-monday",      label: "Monday",          group: "Brand Logos", Icon: MdViewKanban },
  { key: "si-gads",        label: "Google Ads",      group: "Brand Logos", Icon: SiGoogleads },
];

// ─── Feather ──────────────────────────────────────────────────────────────────
const FEATHER_GRID_ICONS = [
  { key: "fi-search",     label: "Search",    group: "Feather", Icon: FiSearch },
  { key: "fi-mail",       label: "Mail",      group: "Feather", Icon: FiMail },
  { key: "fi-phone",      label: "Phone",     group: "Feather", Icon: FiPhone },
  { key: "fi-chat",       label: "Message",   group: "Feather", Icon: FiMessageSquare },
  { key: "fi-monitor",    label: "Monitor",   group: "Feather", Icon: FiMonitor },
  { key: "fi-video",      label: "Video",     group: "Feather", Icon: FiVideo },
  { key: "fi-camera",     label: "Camera",    group: "Feather", Icon: FiCamera },
  { key: "fi-design",     label: "Pen Tool",  group: "Feather", Icon: FiPenTool },
  { key: "fi-layout",     label: "Layout",    group: "Feather", Icon: FiLayout },
  { key: "fi-shop",       label: "Shop Bag",  group: "Feather", Icon: FiShoppingBag },
  { key: "fi-calendar",   label: "Calendar",  group: "Feather", Icon: FiCalendar },
  { key: "fi-chart",      label: "Chart",     group: "Feather", Icon: FiBarChart2 },
  { key: "fi-code",       label: "Code",      group: "Feather", Icon: FiCode },
  { key: "fi-globe",      label: "Globe",     group: "Feather", Icon: FiGlobe },
  { key: "fi-location",   label: "Map Pin",   group: "Feather", Icon: FiMapPin },
  { key: "fi-life-buoy",  label: "Support",   group: "Feather", Icon: FiLifeBuoy },
  { key: "fi-user",       label: "User",      group: "Feather", Icon: FiUser },
  { key: "fi-heart",      label: "Heart",     group: "Feather", Icon: FiHeart },
  { key: "fi-star",       label: "Star",      group: "Feather", Icon: FiStar },
  { key: "fi-check",      label: "Check",     group: "Feather", Icon: FiCheckCircle },
  { key: "fi-feather",    label: "Feather",   group: "Feather", Icon: FiFeather },
  { key: "fi-flag",       label: "Flag",      group: "Feather", Icon: FiFlag },
  { key: "fi-zap",        label: "Zap",       group: "Feather", Icon: FiZap },
];

// ─── Bootstrap ────────────────────────────────────────────────────────────────
const BOOTSTRAP_GRID_ICONS = [
  { key: "bs-megaphone",  label: "Megaphone",    group: "Bootstrap", Icon: BsMegaphone },
  { key: "bs-search",     label: "Search",       group: "Bootstrap", Icon: BsSearch },
  { key: "bs-phone",      label: "Telephone",    group: "Bootstrap", Icon: BsTelephone },
  { key: "bs-chat",       label: "Chat",         group: "Bootstrap", Icon: BsChatSquareText },
  { key: "bs-globe",      label: "Globe",        group: "Bootstrap", Icon: BsGlobe },
  { key: "bs-video",      label: "Cam Video",    group: "Bootstrap", Icon: BsCameraVideo },
  { key: "bs-camera",     label: "Camera",       group: "Bootstrap", Icon: BsCamera },
  { key: "bs-palette",    label: "Palette",      group: "Bootstrap", Icon: BsPalette },
  { key: "bs-cart",       label: "Cart",         group: "Bootstrap", Icon: BsCart3 },
  { key: "bs-calendar",   label: "Calendar",     group: "Bootstrap", Icon: BsCalendar2Event },
  { key: "bs-chart",      label: "Graph",        group: "Bootstrap", Icon: BsGraphUpArrow },
  { key: "bs-gear",       label: "Gear",         group: "Bootstrap", Icon: BsGear },
  { key: "bs-person",     label: "Person",       group: "Bootstrap", Icon: BsPerson },
  { key: "bs-location",   label: "Geo",          group: "Bootstrap", Icon: BsGeoAlt },
  { key: "bs-check",      label: "Check Circle", group: "Bootstrap", Icon: BsCheckCircle },
  { key: "bs-shield",     label: "Shield",       group: "Bootstrap", Icon: BsShieldCheck },
  { key: "bs-stars",      label: "Stars",        group: "Bootstrap", Icon: BsStars },
];

// ─── Social SVG files ─────────────────────────────────────────────────────────
const FILE_GRID_ICONS = [
  { key: "facebook-file",       label: "Facebook",        group: "Social Files", src: "/email-assets/social/facebook.svg" },
  { key: "facebook-file-png",   label: "Facebook PNG",    group: "Social Files", src: "/email-assets/social/facebook.png" },
  { key: "instagram-file",      label: "Instagram",       group: "Social Files", src: "/email-assets/social/instagram.svg" },
  { key: "instagram-file-png",  label: "Instagram PNG",   group: "Social Files", src: "/email-assets/social/instagram.png" },
  { key: "linkedin-file",       label: "LinkedIn",        group: "Social Files", src: "/email-assets/social/linkedin.svg" },
  { key: "linkedin-file-png",   label: "LinkedIn PNG",    group: "Social Files", src: "/email-assets/social/linkedin.png" },
  { key: "pinterest-file",      label: "Pinterest",       group: "Social Files", src: "/email-assets/social/pinterest.svg" },
  { key: "pinterest-file-png",  label: "Pinterest PNG",   group: "Social Files", src: "/email-assets/social/pinterest.png" },
  { key: "youtube-file",        label: "YouTube",         group: "Social Files", src: "/email-assets/social/youtube.svg" },
  { key: "youtube-file-png",    label: "YouTube PNG",     group: "Social Files", src: "/email-assets/social/youtube.png" },
  { key: "x-file",              label: "X",               group: "Social Files", src: "/email-assets/social/x.svg" },
  { key: "x-file-png",          label: "X PNG",           group: "Social Files", src: "/email-assets/social/x.png" },
  { key: "tiktok-file",         label: "TikTok",          group: "Social Files", src: "/email-assets/social/tiktok.svg" },
  { key: "whatsapp-file",       label: "WhatsApp",        group: "Social Files", src: "/email-assets/social/whatsapp.svg" },
  { key: "telegram-file",       label: "Telegram",        group: "Social Files", src: "/email-assets/social/telegram.svg" },
  { key: "discord-file",        label: "Discord",         group: "Social Files", src: "/email-assets/social/discord.svg" },
  { key: "reddit-file",         label: "Reddit",          group: "Social Files", src: "/email-assets/social/reddit.svg" },
  { key: "snapchat-file",       label: "Snapchat",        group: "Social Files", src: "/email-assets/social/snapchat.svg" },
  { key: "threads-file",        label: "Threads",         group: "Social Files", src: "/email-assets/social/threads.svg" },
  { key: "bluesky-file",        label: "Bluesky",         group: "Social Files", src: "/email-assets/social/bluesky.svg" },
  { key: "googlebusiness-file", label: "Google Business", group: "Social Files", src: "/email-assets/social/googlebusiness.svg" },
  { key: "lemon8-file",         label: "Lemon8",          group: "Social Files", src: "/email-assets/social/lemon8.svg" },
];

export const GRID_ICON_LIBRARY = [
  ...FA_ICONS,
  ...LUCIDE_ICONS,
  ...MD_ICONS,
  ...SI_ICONS,
  ...FEATHER_GRID_ICONS,
  ...BOOTSTRAP_GRID_ICONS,
  ...FILE_GRID_ICONS,
];

export const GRID_ICON_LIBRARY_MAP = GRID_ICON_LIBRARY.reduce((acc, item) => {
  acc[item.key] = item;
  return acc;
}, {});

export function renderGridLibraryIcon(iconName, props = {}) {
  const entry = GRID_ICON_LIBRARY_MAP[String(iconName || "").trim()];
  if (!entry) return null;
  if (entry.Icon) {
    const IconComponent = entry.Icon;
    return <IconComponent aria-hidden="true" focusable="false" {...props} />;
  }
  if (entry.src) {
    const size = props.size || 24;
    return <img src={entry.src} alt={entry.label || "Icon"} style={{ width: size, height: size, objectFit: "contain", display: "block", pointerEvents: "none" }} />;
  }
  return null;
}