export default {
  siteName: "Northline Creative",
  navCtaLabel: "Book Strategy Call",
  navCtaHref: "/contact",
  home: {
    objective: "Turn agency traffic into qualified enquiries.",
    hero: { eyebrow: "GROWTH AGENCY", title: "Campaigns, funnels, and automation built to move revenue", subtitle: "A sharper agency site for studios and growth teams selling strategy, paid traffic, funnel design, and conversion work.", primaryLabel: "Book strategy call", primaryHref: "/contact", secondaryLabel: "Capabilities", secondaryHref: "/services", imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=80" },
    stats: { title: "Agency proof markers", items: [{ value: "48h", label: "proposal turnaround" }, { value: "12", label: "core service plays" }, { value: "4.8/5", label: "client satisfaction" }] },
    services: { title: "What the agency sells", subtitle: "Build around service lines that map to revenue outcomes.", items: [{ title: "Funnel builds", text: "Landing pages, upsells, offers, and booking paths." }, { title: "Paid acquisition", text: "Campaign launch, creative testing, and budget optimisation." }, { title: "Automation", text: "Lead routing, follow-up, nurture, and reporting systems." }] },
    features: { title: "Why buyers say yes", subtitle: "Reduce hesitation with operational clarity.", items: [{ title: "Fast launch cycles", text: "Move from brief to live assets without long agency drag." }, { title: "Visible ROI", text: "Tie the work to leads, booked calls, and pipeline movement." }, { title: "Senior execution", text: "Show that strategic thinking is not delegated away." }] },
    testimonials: { title: "Recent wins", items: [{ quote: "They rebuilt the offer path and our conversion rate moved in the first month.", name: "Talia Reed", role: "SaaS Founder" }, { quote: "The biggest difference was the clarity around the buyer journey.", name: "Brent Walsh", role: "Agency Client" }] },
    cta: { title: "Need a stronger acquisition system?", subtitle: "Use this starter to sell the strategy, proof, and next step properly.", buttonLabel: "Book a strategy call", buttonHref: "/contact" },
  },
  about: { pageTitle: "About", objective: "Explain the agency approach and who leads delivery.", title: "A positioning page for agencies that want to sound commercial, not fluffy", text: "Northline Creative partners with service brands and digital operators that need sharper offer presentation, cleaner campaigns, and stronger conversion paths. This page gives space to explain methodology, standards, and how the agency thinks.", bullets: ["Commercial strategy", "Fast execution", "Revenue-focused optimisation"], imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=80", team: { title: "Leadership", members: [{ name: "Grace North", role: "Founder", bio: "Leads positioning, growth strategy, and offer design." }, { name: "Callum Reid", role: "Performance Director", bio: "Handles campaigns, data, and optimisation loops." }] }, stats: { title: "What matters here", items: [{ value: "Paid", label: "acquisition depth" }, { value: "Offer", label: "strategy clarity" }, { value: "Fast", label: "execution rhythm" }] } },
  servicesPage: { pageTitle: "Capabilities", objective: "Help buyers compare service lines and understand what each one does.", hero: { eyebrow: "CAPABILITIES", title: "Show the stack, not just a vague list of agency services", subtitle: "Separate execution categories clearly so buyers understand what they are engaging you for.", primaryLabel: "Talk to us", primaryHref: "/contact", secondaryLabel: "View results", secondaryHref: "/results" }, services: { title: "Agency services", subtitle: "Use service names your market already understands.", items: [{ title: "Offer and funnel design", text: "Reshape the buyer journey before traffic hits the page." }, { title: "Ads and creative", text: "Launch and refine high-velocity paid acquisition systems." }, { title: "CRM and automation", text: "Close the follow-up gap after the lead is generated." }] }, features: { title: "How projects run", subtitle: "Buyers want delivery clarity.", items: [{ title: "Audit and strategy", text: "Review funnel friction, offer structure, and acquisition opportunities." }, { title: "Build and launch", text: "Create the site, campaign assets, and automation flow." }, { title: "Optimise", text: "Iterate around real conversion data, not opinion." }] }, pricing: { title: "Engagement models", subtitle: "Swap these with retainers, audits, or sprints.", plans: [{ name: "Audit", price: "$900", bullets: ["Strategy review", "Offer diagnosis", "Action plan"], primary: false }, { name: "Build Sprint", price: "$3,500", bullets: ["Funnel build", "Campaign assets", "Launch support"], primary: true }, { name: "Retainer", price: "$2,000", period: "/mo", bullets: ["Ongoing optimisation", "Reporting", "Testing backlog"], primary: false }] }, faq: { title: "Questions before engaging", items: [{ q: "Do you work with small teams?", a: "Yes. This page is ideal for explaining fit, budgets, and engagement minimums." }, { q: "Can you improve existing pages?", a: "Yes. Position audits and optimisation services alongside new builds." }] } },
  proofPage: { pageTitle: "Results", slug: "results", objective: "Turn case studies into believable proof.", gallery: { title: "Campaign and funnel snapshots", images: [{ src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80", alt: "Analytics dashboard" }, { src: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80", alt: "Funnel planning" }, { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80", alt: "Team review" }] }, stats: { title: "How to frame outcomes", items: [{ value: "+37%", label: "conversion lift" }, { value: "2.4x", label: "lead volume" }, { value: "18d", label: "time to launch" }] }, testimonials: { title: "Client language", items: [{ quote: "They made the funnel easier to understand and easier to buy from.", name: "Noah Hart", role: "Founder" }, { quote: "It felt like someone finally aligned the campaign with the offer.", name: "Ella Chen", role: "Marketing Lead" }] }, cta: { title: "Want results like this?", subtitle: "Use this page to push readers into a call while proof is fresh.", buttonLabel: "Book a strategy call", buttonHref: "/contact" } },
  contactPage: { pageTitle: "Contact", objective: "Capture qualified leads with enough context to start well.", hero: { eyebrow: "LET'S TALK", title: "Invite the right kind of client enquiry", subtitle: "Ask for business model, traffic source, funnel stage, and revenue goal so the form filters weak leads naturally.", primaryLabel: "Send enquiry", primaryHref: "#contact", secondaryLabel: "See services", secondaryHref: "/services" }, contact: { title: "Tell us about the campaign or funnel", subtitle: "Position this as a planning enquiry, not a generic contact form." }, faq: { title: "Before submitting", items: [{ q: "What budget range should I mention?", a: "Give prospects a clear minimum if that matters to qualification." }, { q: "Can I request an audit only?", a: "Yes. Make that option obvious if you use audits as an entry offer." }] } },
};
