import { SHARED_LIBRARY_EXPANSION_IMAGES } from '../seed-library-images.js';

export default {
  siteName: "Northstar Studio",
  navCtaLabel: "Start Project",
  navCtaHref: "/contact",
  librarySeedImages: SHARED_LIBRARY_EXPANSION_IMAGES,
  home: {
    objective: "Position the studio as a premium digital partner and move qualified visitors into a serious project conversation.",
    hero: {
      eyebrow: "PREMIUM DIGITAL PRESENCE",
      title: "Premium websites built to make established businesses look as credible online as they are in person",
      subtitle: "Northstar Studio designs conversion-focused websites for service brands, consultants, and growing companies that need stronger positioning, clearer offers, and a digital presence that feels commercially sharp from the first scroll.",
      primaryLabel: "Start project",
      primaryHref: "/contact",
      secondaryLabel: "See services",
      secondaryHref: "/services",
      imageUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80",
    },
    stats: { title: "Built to create confidence quickly", items: [{ value: "4", label: "core pages mapped" }, { value: "1", label: "clear buyer journey" }, { value: "100%", label: "editable after launch" }] },
    services: { title: "What the site is designed to do", subtitle: "Every section is there to help the business sound clearer, stronger, and easier to buy from.", items: [{ title: "Clarify the offer", text: "Turn vague capability into a sharper message that tells the right buyer exactly what the business does and why it matters." }, { title: "Build trust early", text: "Use proof, positioning, and stronger page structure to make the company feel credible before the enquiry form ever appears." }, { title: "Move people forward", text: "Guide visitors into the next step with cleaner calls to action, better pacing, and sections that support a real decision." }] },
    features: { title: "Why businesses choose this style of site", subtitle: "It is structured like a commercial website, not a placeholder homepage with extra sections added later.", items: [{ title: "A real page hierarchy", text: "Home, about, services, and contact pages each do a distinct job in the buyer journey instead of repeating the same message." }, { title: "Stronger visual pacing", text: "Content, imagery, proof, and calls to action are layered deliberately so the site feels designed rather than assembled." }, { title: "Ready to tailor", text: "The structure is polished enough to present well now, while still being simple for the client to rewrite around their own brand and offer." }] },
    gallery: { title: "Presentation highlights", images: [{ src: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80", alt: "Workspace" }, { src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80", alt: "Team strategy" }, { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80", alt: "Meeting room" }] },
    testimonials: { title: "What clients say after launch", items: [{ quote: "The finished site finally matched the level of the business. It felt more premium, more focused, and much easier for prospects to understand.", name: "Mason Lee", role: "Consulting Founder" }, { quote: "We stopped sounding generic online. The site now gives people confidence before the first conversation even starts.", name: "Ava Grant", role: "Service Business Owner" }] },
    faq: { title: "Common questions before starting", items: [{ q: "Can this be tailored to a specific industry?", a: "Yes. The structure is intentionally broad, but the copy, imagery, service framing, and proof sections can be rewritten around a specific market very quickly." }, { q: "Is this just a one-page design stretched across multiple pages?", a: "No. Each page has a separate job, which is why the site feels more complete and more commercially useful from the start." }] },
    cta: { title: "Need a site that feels sharper, clearer, and easier to trust?", subtitle: "Use this foundation to shape a premium business website around your brand, offer, proof, and ideal buyer journey.", buttonLabel: "Open in builder", buttonHref: "/contact" },
  },
  about: {
    pageTitle: "About",
    objective: "Build trust by showing the studio's thinking, standards, and commercial approach behind the work.",
    title: "A studio built for businesses that need more than a nicer-looking homepage",
    text: "Northstar Studio works with businesses that have already outgrown generic websites, fragmented messaging, and low-trust first impressions. We design digital experiences that clarify the offer, sharpen the positioning, and help the company feel more established at every stage of the buyer journey.",
    bullets: ["Strategy-led messaging", "Senior design direction", "Commercially focused execution"],
    imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=80",
    team: { title: "Who clients work with", members: [{ name: "Alex Morgan", role: "Founder", bio: "Leads brand positioning, page direction, and the overall commercial story behind each project." }, { name: "Jordan Patel", role: "Strategy Lead", bio: "Shapes user flow, service framing, and the structure that turns interest into qualified enquiries." }] },
    stats: { title: "What this page should reinforce", items: [{ value: "Senior", label: "thinking behind the work" }, { value: "Clear", label: "market positioning" }, { value: "Trusted", label: "delivery process" }] },
  },
  servicesPage: {
    pageTitle: "Services",
    objective: "Explain the studio's core services clearly enough that buyers can understand what they need and how the engagement moves forward.",
    hero: { eyebrow: "SERVICES", title: "Website projects shaped around clarity, credibility, and conversion", subtitle: "Northstar Studio helps businesses tighten their positioning, present their offer more convincingly, and launch websites that feel more commercially complete from day one.", primaryLabel: "Book a consult", primaryHref: "/contact", secondaryLabel: "See pricing", secondaryHref: "/contact" },
    services: { title: "Core services", subtitle: "Each offer is designed to improve how the business is understood, trusted, and contacted online.", items: [{ title: "Positioning and planning", text: "Clarify the offer, buyer journey, service architecture, and page structure before design begins so the site communicates with more precision." }, { title: "Full website design and build", text: "Create polished multi-page websites with stronger visual hierarchy, sharper messaging, and a cleaner path from first impression to enquiry." }, { title: "Refinement and optimisation", text: "Improve existing sites through structural edits, clearer calls to action, tighter page pacing, and conversion-focused content upgrades." }] },
    features: { title: "How projects run", subtitle: "The delivery process is built to feel organised, deliberate, and easy for the client to follow.", items: [{ title: "Discovery and direction", text: "We review the business, audience, current positioning, and commercial goals before shaping the first pass of the site." }, { title: "Design and build", text: "Pages, visuals, messaging, and conversion flow are developed together so the final result feels consistent instead of pieced together." }, { title: "Refine and launch", text: "Feedback is folded into the live build, then the project is polished into a finished site that is ready to present confidently." }] },
    pricing: { title: "Typical engagement paths", subtitle: "These packages read like a finished service menu now, while still being easy for the client to rename or restructure later.", plans: [{ name: "Foundation Site", price: "$1,500", period: "", bullets: ["Core page structure", "Messaging direction", "Launch-ready layout"], primary: false }, { name: "Growth Website", price: "$3,900", period: "", bullets: ["Full multi-page build", "Positioning support", "Conversion-focused refinement"], primary: true }, { name: "Ongoing Support", price: "$650", period: "/mo", bullets: ["Monthly improvements", "Campaign page support", "Priority updates"], primary: false }] },
    faq: { title: "Before you enquire", items: [{ q: "Do you help with copy as well as design?", a: "Yes. Projects can include copy guidance, page messaging support, and structural rewrites where the current wording is weakening the site." }, { q: "Can the finished site still be edited later?", a: "Yes. The site is built to feel finished in the preview, but the client can still change copy, services, imagery, and calls to action after handover." }] },
  },
  contactPage: {
    pageTitle: "Contact",
    objective: "Capture serious enquiries and make the next step feel clear.",
    hero: { eyebrow: "GET STARTED", title: "Use the contact page as a real conversion page", subtitle: "Invite the right prospects to enquire, apply, or request a proposal with confidence.", primaryLabel: "Send enquiry", primaryHref: "#contact", secondaryLabel: "Back to home", secondaryHref: "/" },
    contact: { title: "Tell us about the project", subtitle: "Ask for business goals, current site gaps, timeline, and budget so better leads qualify themselves." },
    faq: { title: "What happens next", items: [{ q: "How quickly do you reply?", a: "Most businesses use this section to set expectations around response time and next steps." }, { q: "Can I request a quote?", a: "Yes. Frame the form around proposal, booking, or discovery call requests." }] },
  },
};
