import type { AreaTypeId, OrganisationId, ProductReferenceId, ProductVariantId, SupplierId } from "../shared/ids";
import type { RequirementCategory } from "../requirements/requirementTypes";
import type { Money } from "../shared/money";

export type ProductCompatibility = {
  category: RequirementCategory;
  subtype?: string;
  areaTypeIds?: AreaTypeId[];
  traits?: string[];
  internalExternal?: "internal" | "external" | "both";
  requirementTags?: string[];
  compatibleAreaTypeIds?: AreaTypeId[];
  wetAreaSuitable?: boolean;
  mountingType?: string;
  installationType?: string;
  size?: string;
  width?: string;
  configuration?: string;
  fuelType?: string;
};

export type ProductReference = {
  id: ProductReferenceId;
  organisationId: OrganisationId;
  catalogueProductId?: string;
  productCode?: string;
  name: string;
  brand?: string;
  range?: string;
  model?: string;
  colour?: string;
  finish?: string;
  material?: string;
  description?: string;
  imageUrl?: string;
  technicalDocumentUrls?: string[];
  productUrl?: string;
  supplierId?: SupplierId;
  supplierName?: string;
  supplierSku?: string;
  defaultVariantId?: ProductVariantId;
  requiresVariant?: boolean;
  unit: string;
  active: boolean;
  discontinued?: boolean;
  availabilityStatus?: "available" | "unavailable" | "supplier_quote_required" | "discontinued";
  priceEffectiveDate?: string;
  priceExpiresAt?: string;
  priceSource?: string;
  builderCost?: Money;
  rrp?: Money;
  allowance?: Money;
  gstTreatment?: "gst_inclusive" | "gst_exclusive" | "not_applicable";
  tierId?: "tier_classic" | "tier_premier" | "tier_premium" | "tier_optional_upgrade" | "tier_custom_only";
  categoryName?: string;
  subcategoryName?: string;
  productType?: string;
  compatibility: ProductCompatibility;
  unitCost?: Money;
};

export type ProductVariantReference = {
  id: ProductVariantId;
  productReferenceId: ProductReferenceId;
  name: string;
  sku?: string;
  description?: string;
  colour?: string;
  finish?: string;
  size?: string;
  width?: string;
  fuelType?: string;
  unitCost?: Money;
  builderCost?: Money;
  priceEffectiveDate?: string;
  priceExpiresAt?: string;
  active: boolean;
};
