// Shared styles object used by PageBuilderCanvas and its sub-modules.
// Extracted here to avoid circular imports.

const styles = {
  container: {
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: 12,
    minHeight: 0,
    minWidth: 0,
    height: "100%",
    maxHeight: "100dvh",
    background: "#0c121a",
    color: "#e6eef5",
    fontFamily: "system-ui, -apple-system, sans-serif",
    overflow: "hidden",
  },
  keyframesNote: {},
  header: {
    position: "sticky",
    top: 0,
    zIndex: 40,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 12px",
    gap: 8,
    background: "linear-gradient(135deg,#153052,#10243e)",
    borderBottom: "1px solid #2c3f62",
    boxShadow: "0 12px 28px rgba(2,6,23,0.28)",
    minWidth: 0,
    overflow: "hidden",
  },
  headerTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 600,
    whiteSpace: "nowrap",
    flexShrink: 0,
    opacity: 0.7,
  },
  primaryActionGroup: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginLeft: 6,
  },
  previewBtn: {
    background: "linear-gradient(135deg,#8b5cf6,#3b82f6)",
    color: "#ffffff",
    border: "1px solid rgba(255,255,255,0.18)",
    borderRadius: 8,
    padding: "10px 16px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 10px 22px rgba(59,130,246,0.28)",
  },
  saveBtn: {
    background: "#86efac",
    color: "#04202e",
    border: "none",
    borderRadius: 8,
    padding: "10px 16px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  headerActions: {
    display: "flex",
    gap: 6,
    alignItems: "center",
    flexWrap: "wrap",
    flex: 1,
    minWidth: 0,
  },
  textToolbar: {
    position: "fixed",
    zIndex: 80,
    width: "min(calc(100vw - 24px), 1120px)",
    background: "linear-gradient(180deg, #eff7ff 0%, #d9ecff 100%)",
    border: "1px solid rgba(96,165,250,0.4)",
    borderRadius: 16,
    boxShadow: "0 18px 44px rgba(15,23,42,0.18)",
    overflow: "hidden",
  },
  textToolbarHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    background: "rgba(239,247,255,0.96)",
    borderBottom: "1px solid rgba(96,165,250,0.28)",
  },
  textToolbarTitle: {
    color: "#16324f",
    fontSize: 22,
    fontWeight: 600,
    letterSpacing: "0.02em",
    textTransform: "uppercase",
  },
  textToolbarDoneBtn: {
    background: "#12385d",
    border: "1px solid rgba(17,24,39,0.14)",
    color: "#ffffff",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
    boxShadow: "0 10px 24px rgba(18,56,93,0.18)",
  },
  textToolbarSubtitle: {
    color: "#33536f",
    fontSize: 16,
    fontWeight: 500,
    cursor: "move",
    userSelect: "none",
  },
  toolbarDragGlyph: {
    color: "#4d78a5",
    fontSize: 16,
    letterSpacing: "0.08em",
    cursor: "move",
    userSelect: "none",
  },
  textToolbarBody: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    flexWrap: "wrap",
    color: "#0f2f4d",
    borderRadius: 8,
    padding: "10px 14px 12px",
    fontSize: 16,
    fontWeight: 500,
  },
  textToolbarBtn: {
    background: "#ffffff",
    border: "1px solid rgba(96,165,250,0.34)",
    color: "#16324f",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 16,
    fontWeight: 500,
    cursor: "pointer",
    minHeight: 44,
    whiteSpace: "nowrap",
  },
  textToolbarActionChip: {
    background: "#ffffff",
    border: "1px solid rgba(37,99,235,0.44)",
    color: "#0f2f4d",
    borderRadius: 8,
    padding: "5px 10px",
    fontSize: 16,
    fontWeight: 500,
    cursor: "pointer",
    minHeight: 30,
    textAlign: "center",
    boxShadow: "0 1px 0 rgba(37,99,235,0.08)",
  },
  textToolbarMiniActionChip: {
    background: "#ffffff",
    border: "1px solid rgba(37,99,235,0.44)",
    color: "#0f2f4d",
    borderRadius: 8,
    padding: "5px 10px",
    fontSize: 16,
    fontWeight: 500,
    cursor: "pointer",
    minHeight: 30,
    minWidth: 56,
    textAlign: "center",
    boxShadow: "0 1px 0 rgba(37,99,235,0.08)",
  },
  textToolbarIconBtn: {
    background: "#ffffff",
    border: "1px solid rgba(37,99,235,0.44)",
    color: "#0f2f4d",
    borderRadius: 8,
    width: 32,
    height: 32,
    padding: 0,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
    boxShadow: "0 1px 0 rgba(37,99,235,0.08)",
  },
  textToolbarChip: {
    background: "#fffdf5",
    border: "1px solid rgba(185,121,6,0.28)",
    color: "#5b4100",
    borderRadius: 10,
    padding: "9px 12px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "center",
  },
  textToolbarSizeChip: {
    background: "#fffdf5",
    border: "1px solid rgba(185,121,6,0.28)",
    color: "#5b4100",
    borderRadius: 10,
    padding: "8px 0",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    minWidth: 0,
  },
  textToolbarChipActive: {
    background: "#f59e0b",
    color: "#111827",
    borderColor: "#b87906",
    boxShadow: "0 8px 16px rgba(245,158,11,0.24)",
  },
  textToolbarSelect: {
    background: "#ffffff",
    border: "1px solid rgba(37,99,235,0.44)",
    color: "#0f2f4d",
    borderRadius: 8,
    padding: "5px 8px",
    fontSize: 16,
    fontWeight: 500,
    minHeight: 30,
  },
  textToolbarInlineGroup: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  textToolbarFormattingGroup: {
    alignItems: "flex-start",
  },
  textToolbarButtonRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  textToolbarInlineDivider: {
    width: 1,
    alignSelf: "stretch",
    minHeight: 54,
    background: "rgba(71,104,135,0.18)",
    flex: "0 0 auto",
  },
  textToolbarSelectStack: {
    display: "grid",
    gap: 6,
  },
  textToolbarChipGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(48px, 1fr))",
    gap: 6,
  },
  textToolbarActionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(72px, 1fr))",
    gap: 6,
  },
  textToolbarSizeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(48px, 1fr))",
    gap: 6,
  },
  textToolbarDivider: {
    width: 1,
    height: 28,
    background: "rgba(121,85,0,0.22)",
    flex: "0 0 auto",
  },
  textToolbarColorStack: {
    display: "grid",
    gap: 6,
    flex: "0 0 auto",
  },
  textToolbarColorGroup: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  textToolbarSwatchesInline: {
    display: "grid",
    gridTemplateColumns: "repeat(9, 22px)",
    gap: 6,
    alignItems: "center",
  },
  textToolbarLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "#173a5d",
    fontSize: 16,
    fontWeight: 500,
    flex: "0 0 auto",
  },
  textToolbarLabelSpaced: {
    marginLeft: 10,
  },
  textToolbarColorGroupWrap: {
    gap: 14,
  },
  textToolbarColor: {
    width: 38,
    height: 38,
    padding: 2,
    borderRadius: 8,
    border: "1px solid rgba(96,165,250,0.34)",
    background: "#ffffff",
    cursor: "pointer",
  },
  textToolbarSwatches: {
    width: 22,
    height: 22,
    gap: 4,
    alignItems: "center",
  },
  textToolbarSwatch: {
    width: 22,
    height: 22,
    borderRadius: 6,
    border: "1px solid rgba(71,104,135,0.28)",
    cursor: "pointer",
    padding: 0,
  },
  tabRow: {
    display: "flex",
    gap: 8,
    flexWrap: "nowrap",
    marginBottom: 12,
    overflowX: "auto",
    overflowY: "hidden",
    paddingBottom: 4,
    scrollbarWidth: "thin",
  },
  tabChip: {
    background: "#102036",
    border: "1px solid #2b3650",
    color: "#cde5ff",
    borderRadius: 999,
    padding: "5px 9px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
    flex: "0 0 auto",
  },
  tabChipActive: {
    background: "#7df9a1",
    borderColor: "#7df9a1",
    color: "#04202e",
  },
  panelToggleBtn: {
    background: "#18314f",
    border: "1px solid #40628d",
    color: "#eff6ff",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.2,
    cursor: "pointer",
  },
  panelToggleBtnActive: {
    background: "#27507f",
    borderColor: "#7dd3fc",
    color: "#ffffff",
  },
  workspace: {
    display: "grid",
    gridTemplateColumns: "248px minmax(0, 1.85fr) minmax(220px, 280px)",
    gap: 12,
    padding: 8,
    overflow: "hidden",
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    alignItems: "stretch",
    justifyContent: "stretch",
    position: "relative",
    isolation: "isolate",
  },
  workspaceNarrow: {
    gridTemplateColumns: "1fr",
  },
  leftPanelShell: {
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    display: "grid",
    position: "sticky",
    top: 0,
    alignSelf: "start",
    zIndex: 30,
  },
  library: {
    background: "#111827",
    border: "1px solid #1e2d45",
    borderRadius: 12,
    padding: 12,
    overflowY: "auto",
    maxHeight: "none",
    height: "100%",
    minHeight: 0,
    minWidth: 248,
    width: 248,
  },
  libraryTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 600,
    marginBottom: 4,
    color: "#7dd3fc",
  },
  librarySubtitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 600,
    color: "#bfd4ea",
    marginBottom: 12,
  },
  categoryList: {
    display: "grid",
    gap: 10,
  },
  categoryGroup: {
    display: "grid",
    gap: 6,
  },
  categoryTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 600,
    textTransform: "uppercase",
    color: "#64748b",
    letterSpacing: 0.5,
  },
  widgetFilterRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 10,
  },
  widgetFilterChip: {
    background: "#1b3354",
    border: "1px solid #4c6f9d",
    color: "#f8fbff",
    borderRadius: 999,
    padding: "7px 11px",
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.15,
    cursor: "pointer",
  },
  widgetFilterChipActive: {
    background: "#86efac",
    borderColor: "#86efac",
    color: "#04202e",
  },
  blocksList: {
    display: "grid",
    gap: 6,
  },
  blockCard: {
    background: "#1e2d3d",
    border: "1px solid #2b3650",
    borderRadius: 8,
    padding: 10,
    cursor: "grab",
    display: "grid",
    gap: 4,
    gridTemplateColumns: "30px 1fr",
    alignItems: "center",
    fontSize: 16,
    transition: "all 0.2s",
  },
  blockIcon: {
    fontSize: 22,
    textAlign: "center",
  },
  blockName: {
    fontSize: 16,
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  canvas: {
    background: "#0d1422",
    borderRadius: 0,
    padding: "0 0 100px",
    overflowY: "auto",
    overflowX: "hidden",
    position: "relative",
    zIndex: 1,
    isolation: "isolate",
    contain: "paint",
    minWidth: 0,
    width: "100%",
    minHeight: 0,
    height: "100%",
  },
  canvasViewport: {
    width: "100%",
    minWidth: 0,
    overflow: "visible",
    position: "relative",
    isolation: "isolate",
    contain: "layout style",
    transform: "translateZ(0)",
    minHeight: "60vh",
  },
  sidePanelShell: {
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    maxHeight: "calc(100dvh - 76px)",
    display: "grid",
    gap: 12,
    position: "sticky",
    top: 0,
    alignSelf: "start",
    zIndex: 30,
    overflowY: "auto",
    overflowX: "hidden",
    paddingBottom: 120,
    paddingRight: 4,
    scrollbarGutter: "stable",
  },
  canvasGridBg: {
    backgroundImage: "linear-gradient(rgba(148,163,184,0.12) 1px, transparent 1px), linear-gradient(90deg, rgba(148,163,184,0.12) 1px, transparent 1px)",
    backgroundSize: "24px 24px",
  },
  canvasLabel: {
    position: "absolute",
    bottom: 16,
    right: 16,
    fontSize: 16,
    color: "#475569",
    pointerEvents: "none",
    zIndex: 9,
    background: "rgba(15,23,42,0.7)",
    padding: "2px 8px",
    borderRadius: 4,
    letterSpacing: "0.04em",
  },
  blocksList: {
    display: "grid",
    gap: 0,
    marginTop: 0,
  },
  emptyState: {
    textAlign: "center",
    padding: 40,
    color: "#64748b",
    fontSize: 16,
  },
  canvasEndSpacer: {
    height: 120,
    minHeight: 120,
    pointerEvents: "none",
  },
  globalBlockBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#0c1e38",
    border: "1px solid #2563eb",
    borderRadius: 8,
    color: "#7dd3fc",
    fontSize: 16,
    fontWeight: 600,
    padding: "7px 14px",
    margin: "6px 0",
    userSelect: "none",
    pointerEvents: "none",
  },
  globalBlockPreviewWrap: {
    display: "grid",
    gap: 0,
    margin: 0,
    cursor: "pointer",
  },
  globalBlockPreviewWrapSelected: {
    borderRadius: 20,
    boxShadow: "0 0 0 2px rgba(14,165,233,0.38)",
  },
  globalBlockPreviewSurface: {
    overflow: "visible",
  },
  blockPreviewError: {
    display: "grid",
    gap: 6,
    minHeight: 140,
    alignContent: "center",
    padding: 24,
    background: "#fff7ed",
    border: "1px solid #fdba74",
    color: "#7c2d12",
    fontSize: 14,
    lineHeight: 1.4,
  },
  blockPreviewErrorTitle: {
    fontSize: 16,
    fontWeight: 700,
  },
  blockPreviewErrorText: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    overflowWrap: "anywhere",
  },
  globalBlockBannerHint: {
    marginLeft: "auto",
    fontSize: 16,
    opacity: 0.55,
    fontWeight: 400,
    fontStyle: "normal",
  },
  canvasBlock: {
    background: "transparent",
    border: "0 solid transparent",
    borderRadius: 0,
    padding: 0,
    cursor: "default",
    transition: "outline 0.15s",
    minWidth: 0,
    position: "relative",
    boxShadow: "none",
  },
  blockActionBar: {
    position: "absolute",
    left: 14,
    top: 14,
    zIndex: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    width: "calc(100% - 28px)",
    pointerEvents: "auto",
  },
  blockActionLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  blockActionLabel: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 32,
    padding: "6px 12px",
    borderRadius: 999,
    background: "rgba(15,23,42,0.86)",
    border: "1px solid rgba(148,163,184,0.28)",
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    backdropFilter: "blur(10px)",
  },
  blockActionButtons: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  blockActionBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 32,
    padding: "6px 12px",
    borderRadius: 10,
    background: "rgba(255,255,255,0.96)",
    border: "1px solid rgba(148,163,184,0.32)",
    color: "#0f172a",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 10px 24px rgba(15,23,42,0.18)",
  },
  blockActionBtnIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    borderRadius: 10,
    background: "rgba(255,255,255,0.96)",
    border: "1px solid rgba(148,163,184,0.32)",
    color: "#0f172a",
    fontSize: 16,
    cursor: "pointer",
    boxShadow: "0 10px 24px rgba(15,23,42,0.18)",
  },
  blockActionBtnDanger: {
    color: "#991b1b",
  },
  blockPreviewShell: {
    position: "relative",
    overflow: "hidden",
  },
  blockInfoPill: {
    position: "absolute",
    right: 14,
    bottom: 14,
    zIndex: 4,
    width: 36,
    height: 36,
    borderRadius: 999,
    display: "grid",
    placeItems: "center",
    background: "rgba(15,23,42,0.76)",
    border: "1px solid rgba(148,163,184,0.28)",
    boxShadow: "0 10px 24px rgba(15,23,42,0.18)",
    backdropFilter: "blur(10px)",
    pointerEvents: "none",
  },
  sectionResizeHandle: {
    position: "absolute",
    left: "50%",
    bottom: -18,
    transform: "translateX(-50%)",
    zIndex: 6,
    borderRadius: 999,
    border: "1px solid rgba(37,99,235,0.42)",
    background: "linear-gradient(135deg, #ffffff, #dbeafe)",
    color: "#0f3f73",
    boxShadow: "0 14px 30px rgba(15,23,42,0.24)",
    padding: "10px 18px",
    minWidth: 124,
    minHeight: 40,
    fontSize: 16,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    cursor: "ns-resize",
    touchAction: "none",
  },
  dragHandle: {
    background: "#0f172a",
    border: "1px solid #2b3650",
    color: "#9fb0c5",
    borderRadius: 6,
    width: 24,
    height: 24,
    fontSize: 16,
    lineHeight: 1,
    cursor: "grab",
    display: "inline-grid",
    placeItems: "center",
    padding: 0,
    marginRight: 2,
  },
  canvasBlockSelected: {
    outline: "2px solid #0ea5e9",
    outlineOffset: -2,
    border: "0 solid transparent",
    background: "transparent",
    boxShadow: "0 0 0 4px rgba(14,165,233,0.10)",
  },
  canvasBlockHovered: {
    outline: "1px solid rgba(14,165,233,0.58)",
    outlineOffset: -1,
    boxShadow: "0 0 0 3px rgba(14,165,233,0.06)",
  },
  blockHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingBottom: 8,
    borderBottom: "1px solid #1e2d45",
  },
  blockInfo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 16,
  },
  blockType: {
    fontSize: 16,
    fontWeight: 600,
    color: "#dbeafe",
  },
  blockControls: {
    display: "flex",
    gap: 4,
  },
  miniBtn: {
    background: "none",
    border: "none",
    fontSize: 16,
    cursor: "pointer",
    padding: 4,
    opacity: 0.7,
    transition: "opacity 0.2s",
  },
  blockPreview: {
    fontSize: 16,
    color: "#9fb0c5",
    minHeight: 40,
    minWidth: 0,
    maxWidth: "100%",
    overflow: "hidden",
    position: "relative",
    paddingTop: 0,
  },
  blockPreviewWithOverlay: {
    paddingTop: 42,
  },
  blockPreviewFullWidth: {
    maxWidth: "none",
    overflow: "hidden",
    position: "relative",
  },
  blockPreviewStickyNav: {
    paddingTop: 0,
    overflow: "hidden",
  },
  animationPopover: {
    position: "fixed",
    zIndex: 82,
    width: 980,
    maxWidth: "calc(100vw - 24px)",
    background: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)",
    border: "1px solid rgba(148,163,184,0.32)",
    borderRadius: 16,
    boxShadow: "0 24px 48px rgba(15,23,42,0.22)",
    overflow: "hidden",
  },
  animationPopoverHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "12px 14px",
    borderBottom: "1px solid rgba(148,163,184,0.18)",
    background: "linear-gradient(135deg, #eff6ff, #f8fafc)",
  },
  animationPopoverHeaderMain: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  animationPopoverActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flex: "0 0 auto",
  },
  animationPopoverTitle: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: 600,
  },
  animationPopoverSubtitle: {
    color: "#64748b",
    fontSize: 16,
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  animationPreviewBtn: {
    background: "linear-gradient(135deg, #38bdf8, #2563eb)",
    border: "1px solid rgba(59,130,246,0.3)",
    color: "#ffffff",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  animationPopoverBody: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 12,
    padding: 14,
    alignItems: "start",
    overflow: "visible",
  },
  animationFieldset: {
    display: "grid",
    gap: 8,
    padding: 12,
    borderRadius: 12,
    background: "#f8fafc",
    border: "1px solid rgba(148,163,184,0.22)",
  },
  animationPresetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(108px, 1fr))",
    gap: 8,
  },
  animationPresetChip: {
    background: "#183b5b",
    border: "1px solid rgba(15,23,42,0.16)",
    color: "#f8fbff",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "center",
  },
  animationPresetChipActive: {
    background: "linear-gradient(135deg,#f59e0b,#f97316)",
    borderColor: "rgba(251,191,36,0.6)",
    color: "#111827",
    boxShadow: "0 10px 24px rgba(249,115,22,0.28)",
  },
  animationOptionsGrid: {
    display: "grid",
    gap: 10,
  },
  animationOptionGroup: {
    display: "grid",
    gap: 6,
  },
  animationMiniLabel: {
    display: "block",
    fontSize: 16,
    fontWeight: 600,
    color: "#244868",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  animationChipRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(76px, 1fr))",
    gap: 8,
  },
  animationValueChip: {
    background: "#224a6f",
    border: "1px solid rgba(15,23,42,0.16)",
    color: "#f8fbff",
    borderRadius: 10,
    padding: "9px 10px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "center",
  },
  animationValueChipActive: {
    background: "rgba(59,130,246,0.12)",
    borderColor: "rgba(59,130,246,0.42)",
    color: "#0f172a",
  },
  dropZone: {
    height: 0,
    display: "grid",
    alignItems: "center",
    overflow: "visible",
  },
  dropZoneActive: {
    height: 20,
  },
  dropLine: {
    height: 0,
    borderRadius: 99,
    background: "transparent",
    transition: "all 0.15s ease",
  },
  dropLineActive: {
    height: 4,
    background: "#22c55e",
    boxShadow: "0 0 0 2px rgba(34,197,94,0.2)",
  },
  properties: {
    background: "#0b1220",
    border: "1px solid #20314b",
    borderRadius: 12,
    padding: 16,
    overflowY: "visible",
    overflowX: "hidden",
    maxHeight: "none",
    height: "auto",
    minHeight: 0,
    minWidth: 0,
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
  },
  propertiesTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    marginBottom: 12,
    color: "#7dd3fc",
  },
  noSelection: {
    margin: 0,
    fontSize: 16,
    color: "#64748b",
    textAlign: "center",
    padding: 20,
  },
  propertyGrid: {
    display: "grid",
    gap: 10,
  },
  sectionCard: {
    display: "grid",
    gap: 8,
    padding: 12,
    borderRadius: 10,
    background: "#1d2c43",
    border: "1px solid #4a6488",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.06), 0 6px 16px rgba(2,6,23,0.22)",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
  },
  propertyField: {
    display: "grid",
    gap: 4,
  },
  numberField: {
    display: "grid",
    gap: 6,
  },
  stackSm: {
    display: "grid",
    gap: 8,
  },
  inlineToggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 16,
    color: "#dbeafe",
    minHeight: 24,
  },
  checkboxInput: {
    width: 18,
    height: 18,
    margin: 0,
    flexShrink: 0,
    cursor: "pointer",
    appearance: "auto",
    WebkitAppearance: "checkbox",
    accentColor: "#38bdf8",
    colorScheme: "dark",
    backgroundColor: "#0f172a",
    border: "1px solid rgba(148,163,184,0.55)",
    borderRadius: 4,
  },
  propertyLabel: {
    fontSize: 16,
    fontWeight: 600,
    textTransform: "uppercase",
    color: "#9db3c2",
    letterSpacing: 0.5,
  },
  presetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
  },
  inlineChipRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 6,
  },
  presetChip: {
    background: "#152238",
    border: "1px solid #2b3650",
    color: "#dbeafe",
    borderRadius: 10,
    padding: "9px 10px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 24,
  },
  presetChipActive: {
    background: "#173459",
    borderColor: "#2d6cdf",
    color: "#ffffff",
  },
  propertyInput: {
    background: "#0d1522",
    border: "1px solid #2b3650",
    color: "#e6eef5",
    borderRadius: 6,
    padding: 8,
    fontSize: 16,
    minHeight: 24,
    fontFamily: "inherit",
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
  },
  formatBtn: {
    background: "#1e2d3d",
    border: "1px solid #2b3650",
    color: "#e6eef5",
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  linkRowCard: {
    display: "grid",
    gap: 8,
    padding: 10,
    borderRadius: 10,
    border: "1px solid #2b3650",
    background: "#111827",
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
  },
  linkRowHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  linkActions: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    justifyContent: "flex-end",
    minWidth: 0,
  },
  linkMoveBtn: {
    background: "#173459",
    border: "1px solid #2d6cdf",
    color: "#dbeafe",
    borderRadius: 8,
    minWidth: 28,
    minHeight: 24,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  linkRowTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "#dbeafe",
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  subLinkList: {
    display: "grid",
    gap: 8,
  },
  subLinkCard: {
    display: "grid",
    gap: 8,
    padding: 10,
    borderRadius: 10,
    border: "1px solid #24334d",
    background: "#0d1522",
  },
  subLinkTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "#93c5fd",
  },
  linkRowDelete: {
    background: "transparent",
    border: "1px solid #7f1d1d",
    color: "#fca5a5",
    borderRadius: 999,
    padding: "4px 8px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 24,
    minWidth: 24,
  },
  iconDeleteBtn: {
    background: "transparent",
    border: "1px solid #7f1d1d",
    color: "#fca5a5",
    borderRadius: 999,
    width: 28,
    height: 28,
    padding: 0,
    fontSize: 18,
    lineHeight: 1,
    fontWeight: 600,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
  },
  secondaryBtn: {
    background: "#173459",
    border: "1px solid #2d6cdf",
    color: "#dbeafe",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 24,
  },
  aiActionBtn: {
    background: "linear-gradient(135deg,#7df9a1,#00d4ff)",
    border: "1px solid rgba(125, 249, 161, 0.45)",
    color: "#04202e",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 24,
  },
  aiHint: {
    margin: 0,
    fontSize: 16,
    color: "#9fb0c5",
    lineHeight: 1.35,
  },
  aiErrorText: {
    margin: 0,
    fontSize: 16,
    color: "#fca5a5",
    lineHeight: 1.35,
  },
  colorGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 10,
  },
  pricingColorGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 10,
  },
  compactColorField: {
    display: "grid",
    gap: 4,
    minWidth: 0,
    width: "100%",
  },
  compactColorLabel: {
    fontSize: 16,
    fontWeight: 600,
    textTransform: "uppercase",
    color: "#9db3c2",
    letterSpacing: 0.4,
    lineHeight: 1.15,
    overflowWrap: "anywhere",
  },
  compactColorRow: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 6,
    alignItems: "stretch",
    minWidth: 0,
  },
  compactColorInput: {
    width: "100%",
    height: 32,
    padding: 2,
    borderRadius: 8,
    border: "1px solid #2b3650",
    background: "#0d1522",
    boxSizing: "border-box",
  },
  compactColorSwatches: {
    display: "flex",
    gap: 5,
    flexWrap: "wrap",
    alignItems: "center",
  },
  colorField: {
    display: "grid",
    gap: 6,
  },
  colorLabel: {
    fontSize: 16,
    fontWeight: 600,
    color: "#94a3b8",
  },
  colorInput: {
    width: "100%",
    height: 38,
    padding: 4,
    borderRadius: 8,
    border: "1px solid #2b3650",
    background: "#0d1522",
    cursor: "pointer",
  },
  colorSwatchRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    alignItems: "center",
  },
  colorSwatch: {
    width: 24,
    height: 24,
    borderRadius: 999,
    border: "2px solid rgba(148,163,184,0.28)",
    cursor: "pointer",
    background: "#0f172a",
  },
  assetPicker: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 8,
  },
  assetChip: {
    background: "#173459",
    border: "1px solid #2d6cdf",
    color: "#dbeafe",
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 24,
    minWidth: 24,
  },
  assetUploadCta: {
    background: "linear-gradient(135deg,#7df9a1,#00d4ff)",
    color: "#04202e",
    borderRadius: 999,
    padding: "6px 10px",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 24,
    minWidth: 24,
  },
  hiddenInput: {
    display: "none",
  },
  assetThumbBtn: {
    width: 52,
    height: 52,
    padding: 0,
    borderRadius: 10,
    overflow: "hidden",
    border: "1px solid #2b3650",
    background: "linear-gradient(45deg, rgba(148,163,184,0.16) 25%, transparent 25%, transparent 50%, rgba(148,163,184,0.16) 50%, rgba(148,163,184,0.16) 75%, transparent 75%, transparent), #0d1522",
    backgroundSize: "12px 12px",
    cursor: "pointer",
  },
  assetThumbPreview: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  assetPickerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(52px, 1fr))",
    gap: 8,
    marginTop: 8,
    maxHeight: 220,
    overflowY: "auto",
    paddingRight: 4,
  },
  assetPickerEmpty: {
    gridColumn: "1 / -1",
    fontSize: 16,
    lineHeight: 1.5,
    color: "#94a3b8",
    padding: "6px 0",
  },
  assetLibraryActionRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 8,
  },
  assetLibraryBtn: {
    padding: "9px 12px",
    borderRadius: 10,
    border: "1px solid rgba(56,189,248,0.26)",
    background: "rgba(14,165,233,0.14)",
    color: "#e0f2fe",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  assetLibraryBtnSecondary: {
    padding: "9px 12px",
    borderRadius: 10,
    border: "1px solid rgba(148,163,184,0.2)",
    background: "rgba(15,23,42,0.52)",
    color: "#e2e8f0",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 220,
    background: "rgba(2,6,23,0.72)",
    backdropFilter: "blur(10px)",
    display: "grid",
    placeItems: "center",
    padding: 20,
  },
  modalCard: {
    width: "min(1040px, 100%)",
    maxHeight: "min(82vh, 880px)",
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr)",
    gap: 14,
    background: "#0b1220",
    border: "1px solid rgba(56,189,248,0.18)",
    borderRadius: 18,
    boxShadow: "0 28px 70px rgba(2,6,23,0.42)",
    padding: 18,
    overflow: "hidden",
  },
  modalHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: "#e0f2fe",
  },
  modalSubtitle: {
    fontSize: 16,
    lineHeight: 1.5,
    color: "#94a3b8",
  },
  modalCloseBtn: {
    padding: "10px 14px",
    borderRadius: 10,
    border: "1px solid rgba(148,163,184,0.22)",
    background: "rgba(15,23,42,0.9)",
    color: "#e2e8f0",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  modalToolbar: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    alignItems: "center",
  },
  modalSearchInput: {
    flex: "1 1 280px",
    minWidth: 0,
    background: "#0d1522",
    border: "1px solid #2b3650",
    color: "#e6eef5",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 16,
  },
  modalUploadBtn: {
    padding: "10px 14px",
    borderRadius: 10,
    background: "linear-gradient(135deg,#7df9a1,#00d4ff)",
    color: "#04202e",
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalAssetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: 12,
    overflowY: "auto",
    paddingRight: 4,
    alignContent: "start",
  },
  modalSectionTitle: {
    gridColumn: "1 / -1",
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: 0,
    textTransform: "uppercase",
    marginTop: 4,
  },
  modalAssetCard: {
    display: "grid",
    gap: 8,
    padding: 10,
    borderRadius: 8,
    border: "1px solid #24334d",
    background: "#101827",
    cursor: "pointer",
    textAlign: "left",
  },
  modalAssetCardSelected: {
    border: "1px solid #38bdf8",
    boxShadow: "0 0 0 1px rgba(56,189,248,0.25)",
  },
  modalAssetPreview: {
    width: "100%",
    aspectRatio: "1 / 1",
    objectFit: "cover",
    borderRadius: 8,
    background: "#0d1522",
    display: "block",
  },
  modalAssetName: {
    fontSize: 16,
    lineHeight: 1.4,
    color: "#dbeafe",
    overflowWrap: "anywhere",
  },
  modalEmptyState: {
    gridColumn: "1 / -1",
    padding: 18,
    borderRadius: 12,
    border: "1px dashed #24334d",
    color: "#94a3b8",
    fontSize: 16,
    textAlign: "center",
  },
};


export { styles };
