// Website Page Builder Block Components
// Used by the drag-drop canvas editor for building website pages

const BlockTypes = {
  NAV_BAR: "nav-bar",
  HERO: "hero",
  PARALLAX: "parallax",
  TEXT: "text",
  IMAGE: "image",
  CTA_BUTTON: "cta-button",
  FEATURE_LIST: "feature-list",
  TESTIMONIAL: "testimonial",
  PRICING_TABLE: "pricing-table",
  CONTACT_FORM: "contact-form",
  IMAGE_GALLERY: "image-gallery",
  VIDEO_EMBED: "video-embed",
  SPACE: "space",
  DIVIDER: "divider",
  COLUMNS_2: "columns-2",
  COLUMNS_3: "columns-3",
  ACCORDION: "accordion",
  STATS: "stats",
  TEAM: "team",
  FAQ: "faq",
  NEWSLETTER: "newsletter",
  TRUST_BADGES: "trust-badges",
  IMAGE_STACK: "image-stack",
  FOOTER: "footer",
};

const BlockDefinitions = {
  [BlockTypes.NAV_BAR]: {
    name: "Navigation Bar",
    icon: "🧭",
    category: "Section",
    description: "Top navigation with brand, links, and CTA",
    defaultProps: {
      variant: "split-dark",
      fullWidthBackground: true,
      showLogo: false,
      logo: "",
      logoWidth: 44,
      stickyMode: "normal",
      mobileMenuStyle: "hamburger",
      brand: "Your Brand",
      brandFontSize: 18,
      links: [
        { label: "Home", href: "#home", highlighted: true, children: [] },
        { label: "About", href: "#about" },
        { label: "Services", href: "#services" },
        { label: "Contact", href: "#contact" },
      ],
      linkFontSize: 16,
      linkHoverEffect: "fill",
      linkHoverBackgroundColor: "rgba(255,255,255,0.14)",
      linkHoverTextColor: "#ffffff",
      activeLinkBackgroundColor: "rgba(255,255,255,0.18)",
      activeLinkTextColor: "#ffffff",
      ctaText: "Get Started",
      ctaLink: "#contact",
      ctaFontSize: 16,
      backgroundColor: "#0b1220",
      borderColor: "rgba(148,163,184,0.24)",
      textColor: "#e2e8f0",
      buttonColor: "#ffffff",
      buttonTextColor: "#0f172a",
    },
  },
  [BlockTypes.HERO]: {
    name: "Hero Section",
    icon: "🎬",
    category: "Section",
    description: "Large hero banner with headline and CTA",
    defaultProps: {
      heroVariant: "spotlight",
      headline: "Your Compelling Headline Here",
      subheadline: "Supporting text that explains the main value",
      ctaText: "Get Started",
      ctaLink: "#",
      headlineAlignment: "center",
      headlineColor: "#ffffff",
      headlineFontFamily: "system-ui, -apple-system, sans-serif",
      headlineFontWeight: "700",
      headlineFontSize: 52,
      subheadlineFontSize: 20,
      textColor: "#e2e8f0",
      fontFamily: "system-ui, -apple-system, sans-serif",
      fontWeight: "400",
      buttonColor: "#2563eb",
      buttonTextColor: "#ffffff",
      fullWidthBackground: true,
      enableParallax: false,
      backgroundStyle: "solid",
      backgroundColor: "#0f172a",
      backgroundImage: "",
      backgroundVideoUrl: "",
      backgroundPosition: "center center",
      minHeight: "420px",
    },
  },
  [BlockTypes.PARALLAX]: {
    name: "Parallax Section",
    icon: "🌊",
    category: "Section",
    description: "Movable parallax text over a background image",
    defaultProps: {
      headline: "Parallax Headline",
      subheadline: "Drag this text box anywhere over the background.",
      ctaText: "Get Started",
      ctaLink: "#",
      headlineAlignment: "center",
      verticalAlign: "center",
      contentX: 50,
      contentY: 58,
      contentWidth: 680,
      contentHeight: 220,
      floatingImage: "",
      floatingX: 76,
      floatingY: 58,
      floatingWidth: 220,
      floatingHeight: 220,
      headlineColor: "#ffffff",
      headlineFontFamily: "system-ui, -apple-system, sans-serif",
      headlineFontWeight: "700",
      headlineFontSize: 52,
      subheadlineFontSize: 20,
      textColor: "#e2e8f0",
      fontFamily: "system-ui, -apple-system, sans-serif",
      fontWeight: "400",
      buttonColor: "#2563eb",
      buttonTextColor: "#ffffff",
      fullWidthBackground: true,
      enableParallax: true,
      backgroundStyle: "image",
      backgroundColor: "#0f172a",
      backgroundImage: "https://placehold.co/1600x900/0f172a/1e293b?text=%20",
      backgroundVideoUrl: "",
      backgroundPosition: "center center",
      minHeight: "480px",
    },
  },
  [BlockTypes.TEXT]: {
    name: "Text Section",
    icon: "📝",
    category: "Content",
    description: "Rich text content area",
    defaultProps: {
      text: "Enter your text here. You can use multiple paragraphs and formatting.",
      alignment: "left", // left, center, right
      textSize: "medium", // legacy fallback
      textFontSize: 18,
      fontFamily: "system-ui", // system-ui, Georgia, Arial, etc
      fontWeight: "400", // 300, 400, 500, 600, 700, 800, 900
      minHeight: "220px",
      fullWidthBackground: false,
      enableParallax: false,
      textColor: "#e6eef5",
      backgroundColor: "#111827",
      backgroundImage: "",
      paddingTop: 48,
      paddingBottom: 48,
      textAnimation: "fade-in",
    },
  },
  [BlockTypes.IMAGE]: {
    name: "Image",
    icon: "🖼️",
    category: "Media",
    description: "Add a full-width image with caption",
    defaultProps: {
      src: "",
      alt: "Image",
      width: "100%",
      height: "400px",
      caption: "",
      fullWidthBackground: true,
    },
  },
  [BlockTypes.CTA_BUTTON]: {
    name: "Call-to-Action Button",
    icon: "🔘",
    category: "Conversion",
    description: "Prominent button to drive action",
    defaultProps: {
      eyebrow: "Ready to take the next step?",
      title: "Turn attention into action",
      description: "Use this CTA block to push visitors toward a booking, quote, purchase, or signup.",
      text: "Click Here",
      link: "#",
      note: "Fast setup. Clear next step. Better conversions.",
      style: "spotlight-pill",
      size: "large", // small, medium, large
      alignment: "center",
      backgroundColor: "linear-gradient(135deg,#eff6ff,#ffffff)",
      textColor: "#0f172a",
      buttonColor: "linear-gradient(135deg,#0ea5e9,#2563eb)",
      buttonTextColor: "#ffffff",
      borderColor: "rgba(191,219,254,0.9)",
    },
  },
  [BlockTypes.FEATURE_LIST]: {
    name: "List Block",
    icon: "☰",
    category: "Content",
    description: "Card-style list section similar to the email editor",
    defaultProps: {
      title: "Key Features",
      items: [
        {
          title: "Feature 1",
          body: "Add a short supporting sentence for this feature.",
          image: "https://placehold.co/960x720/e0f2fe/0f172a?text=Feature+1",
        },
        {
          title: "Feature 2",
          body: "Use each card to explain a specific benefit or deliverable.",
          image: "https://placehold.co/960x720/fef3c7/1f2937?text=Feature+2",
        },
        {
          title: "Feature 3",
          body: "Images can be swapped per card to create a richer section.",
          image: "https://placehold.co/960x720/dcfce7/14532d?text=Feature+3",
        },
      ],
      layout: "vertical",
      featureVariant: "cards",
      featureCardWidth: 320,
      bulletStyle: "check",
      spacingScale: "normal",
      backgroundColor: "#ffffff",
      itemBackgroundColor: "#eff6ff",
      textColor: "#0f172a",
      borderColor: "#dbeafe",
    },
  },
  [BlockTypes.TESTIMONIAL]: {
    name: "Testimonial",
    icon: "💬",
    category: "Social Proof",
    description: "Customer testimonial or quote",
    defaultProps: {
      text: "This is a great product/service!",
      author: "Customer Name",
      role: "CEO at Company",
      avatar: "",
      rating: 5,
      testimonialVariant: "spotlight", // spotlight, bubble
      spacingScale: "normal", // tight, normal, luxury
    },
  },
  [BlockTypes.PRICING_TABLE]: {
    name: "Pricing Table",
    icon: "💰",
    category: "Conversion",
    description: "Pricing plans comparison",
    defaultProps: {
      title: "Our Pricing",
      pricingVariant: "premium", // premium, clean
      spacingScale: "normal", // tight, normal, luxury
      plans: [
        {
          id: "pricing-default-1",
          name: "Starter",
          price: "$29",
          description: "A polished entry point for smaller launches.",
          includedFeatures: ["Core setup", "Launch checklist", "Email support"],
          features: ["Core setup", "Launch checklist", "Email support"],
          extras: ["Add-on automations", "Extra revisions"],
          featureIcon: "tick",
          badge: "",
          cta: "Get Started",
        },
        {
          id: "pricing-default-2",
          name: "Signature",
          price: "$99",
          description: "The standout package with the richest delivery and strongest visual emphasis.",
          includedFeatures: ["Strategy workshop", "Priority build", "Conversion polish", "Priority support"],
          features: ["Strategy workshop", "Priority build", "Conversion polish", "Priority support"],
          extras: ["VIP onboarding", "Funnel review", "Advanced automations"],
          featureIcon: "spark",
          badge: "",
          cta: "Choose Signature",
          highlighted: true,
        },
        {
          id: "pricing-default-3",
          name: "Premier",
          price: "$179",
          description: "For larger offers that need more extras and a higher-touch rollout.",
          includedFeatures: ["Custom rollout", "Launch assets", "Weekly reviews"],
          features: ["Custom rollout", "Launch assets", "Weekly reviews"],
          extras: ["White-glove migration", "Dedicated training"],
          featureIcon: "arrow",
          badge: "",
          cta: "Book a Call",
        },
      ],
    },
  },
  [BlockTypes.CONTACT_FORM]: {
    name: "Contact Form",
    icon: "✉️",
    category: "Conversion",
    description: "Lead capture or contact form",
    defaultProps: {
      title: "Get in Touch",
      subtitle: "Fill out the form below",
      formVariant: "minimal-soft",
      formMaxWidth: 760,
      backgroundColor: "#ffffff",
      sectionGradient: "linear-gradient(180deg,#ffffff,#f8fafc)",
      cardBackgroundColor: "#ffffff",
      textColor: "#0f172a",
      subtleTextColor: "#475569",
      buttonBackgroundColor: "#0f172a",
      buttonTextColor: "#ffffff",
      inputBackgroundColor: "#ffffff",
      inputBorderColor: "#cbd5e1",
      inputTextColor: "#0f172a",
      submitAction: "none",
      bookingUrl: "https://nonfat-ungored-buford.ngrok-free.dev/u/gr8result?service=f775fc69-f59e-4fd8-ae4a-1e9bb7ecfe4f",
      mediaPosition: "none",
      mediaImage: "",
      mediaAlt: "Contact form image",
      fields: [
        { name: "name", label: "Your Name", type: "text", required: true, placeholder: "Jane Smith" },
        { name: "email", label: "Your Email", type: "email", required: true, placeholder: "jane@example.com" },
        { name: "message", label: "Message", type: "textarea", required: false, placeholder: "Tell us how we can help" },
      ],
      submitText: "Send Details",
    },
  },
  [BlockTypes.IMAGE_GALLERY]: {
    name: "Image Gallery",
    icon: "🖼️",
    category: "Media",
    description: "Grid of images",
    defaultProps: {
      title: "Visual Highlights",
      galleryVariant: "balanced-grid",
      images: [
        { src: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80", alt: "Team collaboration", caption: "Collaborative planning sessions" },
        { src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80", alt: "Creative meeting", caption: "Creative ideas in motion" },
        { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80", alt: "Workshop wall", caption: "Workshop outcomes and planning" },
      ],
      columns: 3,
      backgroundColor: "linear-gradient(180deg,#ffffff,#f8fafc)",
      textColor: "#0f172a",
      borderColor: "rgba(226,232,240,0.9)",
    },
  },
  [BlockTypes.VIDEO_EMBED]: {
    name: "Video",
    icon: "🎥",
    category: "Media",
    description: "Embedded YouTube or Vimeo video",
    defaultProps: {
      url: "",
      title: "Video Title",
      width: "100%",
      height: "500px",
    },
  },
  [BlockTypes.SPACE]: {
    name: "Spacer",
    icon: "⬆️",
    category: "Layout",
    description: "Add vertical space",
    defaultProps: {
      height: "40px",
    },
  },
  [BlockTypes.DIVIDER]: {
    name: "Divider",
    icon: "─",
    category: "Layout",
    description: "Visual separator line",
    defaultProps: {
      style: "line", // line, dots, dashes
      color: "#ccc",
    },
  },
  [BlockTypes.COLUMNS_2]: {
    name: "Two Column",
    icon: "▌▌",
    category: "Layout",
    description: "Two content columns with text, images, and color controls",
    defaultProps: {
      title: "",
      leftTitle: "",
      leftContent: "",
      leftImage: "",
      rightTitle: "",
      rightContent: "",
      rightImage: "",
      ratio: "50-50",
      backgroundColor: "transparent",
      cardBackgroundColor: "#f8fafc",
      textColor: "#0f172a",
      borderColor: "#dbeafe",
    },
  },
  [BlockTypes.COLUMNS_3]: {
    name: "Three Column",
    icon: "▌▌▌",
    category: "Layout",
    description: "Three content columns with text, images, and color controls",
    defaultProps: {
      title: "",
      column1Title: "",
      column1: "",
      column1Image: "",
      column2Title: "",
      column2: "",
      column2Image: "",
      column3Title: "",
      column3: "",
      column3Image: "",
      backgroundColor: "transparent",
      cardBackgroundColor: "#f8fafc",
      textColor: "#0f172a",
      borderColor: "#dbeafe",
    },
  },
  [BlockTypes.ACCORDION]: {
    name: "Accordion",
    icon: "📋",
    category: "Interaction",
    description: "Expandable content sections",
    hiddenInLibrary: true,
    defaultProps: {
      title: "Frequently Asked Questions",
      faqMaxWidth: 980,
      faqStartCollapsed: false,
      faqAllowMultipleOpen: false,
      items: [
        { heading: "Question 1?", content: "Answer here" },
        { heading: "Question 2?", content: "Answer here" },
      ],
    },
  },
  [BlockTypes.STATS]: {
    name: "Stats Cards",
    icon: "📊",
    category: "Social Proof",
    description: "Display key statistics",
    defaultProps: {
      title: "Our Impact",
      subtitle: "Show the proof points that make the offer feel credible at a glance.",
      statsVariant: "editorial-band",
      backgroundColor: "linear-gradient(180deg,#ffffff,#f8fafc)",
      textColor: "#0f172a",
      borderColor: "rgba(226,232,240,0.92)",
      cardBackgroundColor: "rgba(255,255,255,0.9)",
      accentColor: "#0ea5e9",
      stats: [
        {
          number: "500+",
          label: "Customers",
          detail: "Brands and service businesses supported in the last 24 months.",
        },
        {
          number: "$2M",
          label: "Revenue Generated",
          detail: "Attributed pipeline and direct sales driven by optimized funnels.",
        },
        {
          number: "98%",
          label: "Satisfaction",
          detail: "Average post-project client rating across delivery and communication.",
        },
      ],
    },
  },
  [BlockTypes.TEAM]: {
    name: "Team Section",
    icon: "👥",
    category: "Social Proof",
    description: "Showcase team members",
    defaultProps: {
      title: "Meet the Team",
      subtitle: "Introduce the people clients will trust with the work.",
      teamVariant: "studio-cards",
      backgroundColor: "linear-gradient(180deg,#ffffff,#f8fafc)",
      textColor: "#0f172a",
      borderColor: "rgba(226,232,240,0.9)",
      members: [
        {
          id: "team-member-1",
          name: "Ava Bennett",
          role: "Client Strategy Lead",
          image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
          bio: "Shapes the offer, messaging, and customer journey for every launch.",
        },
        {
          id: "team-member-2",
          name: "Marcus Reed",
          role: "Creative Director",
          image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
          bio: "Turns strategy into bold visual systems, landing pages, and campaigns.",
        },
        {
          id: "team-member-3",
          name: "Nina Patel",
          role: "Automation Specialist",
          image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=900&q=80",
          bio: "Builds the follow-up, CRM, and reporting flows that keep leads moving.",
        },
      ],
    },
  },
  [BlockTypes.FAQ]: {
    name: "FAQ Section",
    icon: "❓",
    category: "Content",
    description: "Frequently asked questions",
    defaultProps: {
      title: "Common Questions",
      faqMaxWidth: 980,
      faqStartCollapsed: false,
      faqAllowMultipleOpen: false,
      items: [
        { id: "faq-default-1", question: "What is this?", answer: "This is the answer", heading: "What is this?", content: "This is the answer" },
        { id: "faq-default-2", question: "How does it work?", answer: "It works like this...", heading: "How does it work?", content: "It works like this..." },
      ],
    },
  },
  [BlockTypes.NEWSLETTER]: {
    name: "Newsletter Signup",
    icon: "📬",
    category: "Conversion",
    description: "Email subscriber form",
    defaultProps: {
      title: "Stay Updated",
      subtitle: "Get the latest tips and insights",
      placeholder: "Enter your email",
      buttonText: "Subscribe",
    },
  },
  [BlockTypes.TRUST_BADGES]: {
    name: "Trust Badges",
    icon: "✅",
    category: "Social Proof",
    description: "Display trust icons and certifications",
    defaultProps: {
      badges: [
        { icon: "🔒", label: "Secure" },
        { icon: "⭐", label: "Trusted" },
        { icon: "🏆", label: "Award Winning" },
      ],
    },
  },
  [BlockTypes.IMAGE_STACK]: {
    name: "Layered Image Stack",
    icon: "🖼️",
    category: "Media",
    description: "Free-layout canvas with movable image, text, and logo layers",
    defaultProps: {
      title: "Layered Visual Canvas",
      fullWidthBackground: true,
      minHeight: "72vh",
      backgroundColor: "transparent",
      showGrid: true,
      snapToGrid: true,
      images: [
        { id: "layer-1", kind: "image", src: "", assetId: "", x: 40, y: 40, width: 280, height: 190, rotation: -6, radius: 18, zIndex: 1 },
        { id: "text-layer-1", kind: "text", content: "Headline Text", x: 420, y: 96, width: 360, height: 140, rotation: 0, radius: 16, zIndex: 2, fontSize: 40, fontWeight: "700", textAlign: "center", verticalAlign: "center", textColor: "#0f172a", background: "rgba(255,255,255,0.92)" },
        { id: "layer-2", kind: "image", src: "", assetId: "", x: 240, y: 220, width: 250, height: 180, rotation: 6, radius: 18, zIndex: 3 },
      ],
    },
  },
  [BlockTypes.FOOTER]: {
    name: "Footer",
    icon: "🔻",
    category: "Section",
    description: "Site footer with logo, nav links, newsletter signup, and copyright",
    defaultProps: {
      backgroundColor: "#0f172a",
      textColor: "#e2e8f0",
      linkColor: "#94a3b8",
      borderColor: "rgba(148,163,184,0.2)",
      logo: "",
      logoWidth: 48,
      brand: "Your Brand",
      tagline: "Building something amazing.",
      contactHeading: "Contact",
      contactEmail: "hello@yourbrand.com",
      contactPhone: "(555) 010-2026",
      contactAddress: "Your city, state",
      navHeading: "Navigation",
      navLinks: [
        { label: "Home", href: "#home" },
        { label: "About", href: "#about" },
        { label: "Services", href: "#services" },
        { label: "Contact", href: "#contact" },
      ],
      extraHeading: "Company",
      extraLinks: [
        { label: "Blog", href: "#blog" },
        { label: "Privacy Policy", href: "#privacy" },
        { label: "Terms", href: "#terms" },
      ],
      showNewsletter: true,
      newsletterHeading: "Stay Updated",
      newsletterSubtitle: "Get the latest news delivered to your inbox.",
      newsletterButtonText: "Subscribe",
      newsletterButtonColor: "#2563eb",
      newsletterButtonTextColor: "#ffffff",
      newsletterActionUrl: "",
      newsletterSubmitMethod: "post",
      newsletterFallbackEmail: "",
      copyrightText: "© 2025 Your Brand. All rights reserved.",
    },
  },
};

export { BlockTypes, BlockDefinitions };
