import { ESTIMATION_TRADE_CATEGORIES } from "../data/tradeCategories.js";

export const EXTERNAL_WALL_ASSEMBLIES = [
  {
    id: "brick_veneer",
    name: "Brick Veneer External Walls",
    category: "External Walls",
    trade: ESTIMATION_TRADE_CATEGORIES.MASONRY,
    appliesWhen: (input) => input.wallConstruction === "Brick Veneer" || input.groundExternalWall === "Brick Veneer",
    quantityBasis: "externalWallM2",
    scheduleDay: 62,
    materials: [{ materialId: "bricks", factor: 1 }],
  },
  {
    id: "blockwork",
    name: "Blockwork External Walls",
    category: "External Walls",
    trade: ESTIMATION_TRADE_CATEGORIES.MASONRY,
    appliesWhen: (input) => input.wallConstruction === "Blockwork" || input.groundExternalWall === "Blockwork",
    quantityBasis: "externalWallM2",
    scheduleDay: 60,
    materials: [{ materialId: "blocks", factor: 1 }],
  },
  {
    id: "hebel",
    name: "Hebel External Walls",
    category: "External Walls",
    trade: ESTIMATION_TRADE_CATEGORIES.CLADDING,
    appliesWhen: (input) => input.wallConstruction === "Hebel" || input.firstExternalWall === "Hebel",
    quantityBasis: "externalWallM2",
    scheduleDay: 62,
    materials: [{ materialId: "hebel_panels", factor: 1 }],
  },
  {
    id: "lightweight_cladding",
    name: "Lightweight Cladding External Walls",
    category: "External Walls",
    trade: ESTIMATION_TRADE_CATEGORIES.CLADDING,
    appliesWhen: (input) => input.wallConstruction === "Lightweight Cladding" || input.firstExternalWall === "Lightweight cladding",
    quantityBasis: "upperExternalWallM2",
    scheduleDay: 68,
    materials: [{ materialId: "lightweight_cladding", factor: 1 }],
  },
  {
    id: "rendered_cladding",
    name: "Rendered Cladding",
    category: "External Walls",
    trade: ESTIMATION_TRADE_CATEGORIES.CLADDING,
    appliesWhen: (input) => input.wallConstruction === "Rendered Cladding" || input.wallConstruction === "Rendered cladding",
    quantityBasis: "externalWallM2",
    scheduleDay: 72,
    materials: [{ materialId: "render_system", factor: 1 }],
  },
];
